"""Generated by codegen/generate.py -- DO NOT EDIT BY HAND.

Regenerate with `python3 codegen/generate.py` from pyvar-client/ after any
change to the API's request schemas. See that script's own module
docstring for what "generated" means here and why.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pyvar_client._client import Client


class LiquidityNamespace:
    """Generated methods for this domain -- see pyvar_client._generated's
    own module docstring."""

    def __init__(self, client: "Client") -> None:
        self._client = client

    def asset_encumbrance_ratio(
        self, *, encumbered_assets: float, total_assets: float
    ) -> dict[str, Any]:
        """Asset encumbrance ratio (EBA reporting).

        ``encumbrance = encumbered assets / total assets``. High encumbrance reduces
        the unencumbered asset pool available to monetise in stress.

        Returns:
            The raw API response as a dict.
        """
        body = {"encumbered_assets": encumbered_assets, "total_assets": total_assets}
        return self._client._request(
            "POST", "/api/v1/liquidity/asset_encumbrance_ratio", json_body=body
        )

    def available_stable_funding_asf_calc(
        self,
        *,
        funding_amounts: list[float] | list[list[float]],
        asf_factors: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """Available Stable Funding for the NSFR numerator.

        ASF is the weighted sum of funding sources by their ASF factor. Basel III
        assigns higher factors to more stable funding (e.g. capital and >1y funding
        = 100%, stable retail deposits = 95%, less-stable = 90%, wholesale <1y
        typically 50% or 0%).

        Returns:
            The raw API response as a dict.
        """
        body = {"funding_amounts": funding_amounts, "asf_factors": asf_factors}
        return self._client._request(
            "POST", "/api/v1/liquidity/available_stable_funding_asf_calc", json_body=body
        )

    def cash_flow_ladder_1_year(
        self,
        *,
        bucket_inflows: list[float] | list[list[float]],
        bucket_outflows: list[float] | list[list[float]],
        opening_balance: float = 0.0,
        buckets: list[str] | None = None,
    ) -> dict[str, Any]:
        """One-year bucketed contractual cash-flow ladder.

        Aggregates inflows and outflows into the standard maturity buckets and
        computes the per-bucket and cumulative liquidity gap.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "bucket_inflows": bucket_inflows,
            "bucket_outflows": bucket_outflows,
            "opening_balance": opening_balance,
            "buckets": buckets,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/cash_flow_ladder_1_year", json_body=body
        )

    def cash_flow_ladder_30_day(
        self,
        *,
        daily_inflows: list[float] | list[list[float]],
        daily_outflows: list[float] | list[list[float]],
        opening_balance: float = 0.0,
    ) -> dict[str, Any]:
        """30-day daily contractual cash-flow ladder.

        Projects the daily net and cumulative liquidity position over a 30-day
        horizon. The minimum cumulative balance (including the opening balance) is
        the tightest liquidity point — if negative the institution faces a funding
        shortfall on that day.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "daily_inflows": daily_inflows,
            "daily_outflows": daily_outflows,
            "opening_balance": opening_balance,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/cash_flow_ladder_30_day", json_body=body
        )

    def central_bank_facility_eligibility(
        self,
        *,
        asset_ratings: list[float] | list[list[float]],
        min_rating: int,
        asset_values: list[float] | list[list[float]],
        cb_haircuts: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """Central-bank facility collateral eligibility and borrowing capacity.

        Filters assets meeting the central bank's minimum credit rating (encoded as
        an ordinal where higher = better) and computes the post-central-bank-haircut
        borrowing capacity from eligible assets.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "asset_ratings": asset_ratings,
            "min_rating": min_rating,
            "asset_values": asset_values,
            "cb_haircuts": cb_haircuts,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/central_bank_facility_eligibility", json_body=body
        )

    def collateral_availability_analysis(
        self,
        *,
        collateral_values: list[float] | list[list[float]],
        haircuts: list[float] | list[list[float]],
        already_pledged: list[float] | list[list[float]] | None = None,
    ) -> dict[str, Any]:
        """Collateral availability — post-haircut monetisable value.

        Computes the net realisable collateral value after haircuts and netting off
        already-pledged amounts — the counterbalancing capacity available to raise
        secured funding.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "collateral_values": collateral_values,
            "haircuts": haircuts,
            "already_pledged": already_pledged,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/collateral_availability_analysis", json_body=body
        )

    def combined_stress_scenario(
        self,
        *,
        retail_deposits: float,
        wholesale_funding: float,
        hqla_by_level: list[float] | list[list[float]],
        market_haircuts: list[float] | list[list[float]],
        retail_runoff: float = 0.15,
        wholesale_runoff: float = 1.0,
        inflows: float = 0.0,
        retail_deposits_by_category: list[float] | list[list[float]] | None = None,
        retail_runoff_rates: list[float] | list[list[float]] | None = None,
    ) -> dict[str, Any]:
        """Combined idiosyncratic + market-wide stress scenario.

        By default (the two retail-category arguments omitted) this is NOT the
        BCBS 238 reference combined scenario: BCBS 238's own combined
        idiosyncratic + market-wide scenario (§II paras 19-20) runs off the
        LCR's own regulator-set retail run-off categories (stable/less-stable
        deposit stability buckets, each with its own national-discretion
        minimum rate), whereas this function's default applies a single flat
        15% retail / 100% wholesale run-off convention instead -- a structural
        gap a single scalar ``retail_runoff`` rate cannot close, since BCBS
        238's categorisation requires segmenting retail deposits into multiple
        stability buckets with different rates, not one blended rate.

        Pass ``retail_deposits_by_category`` and ``retail_runoff_rates``
        together (equal-length arrays: each category's deposit balance and its
        own regulator-set run-off rate) to switch to a BCBS-238-shaped
        categorised retail outflow -- ``sum(retail_deposits_by_category *
        retail_runoff_rates)`` -- instead of the single-rate
        ``retail_deposits * retail_runoff`` convention. This function does not
        hardcode specific category rates itself (BCBS 238 leaves the exact
        stable/less-stable thresholds and rates to national supervisory
        discretion); the caller supplies their own jurisdiction's categorised
        balances and rates. ``retail_deposits_by_category`` must sum to
        ``retail_deposits`` -- enforced as a consistency check, not silently
        ignored.

        Models a firm-specific shock occurring inside a market-wide crisis:
        liability run-off is aggravated (default 15% retail, 100% wholesale)
        *and* HQLA value is reduced by stressed market haircuts, simultaneously.
        (Found during the Tier 3 #2 audit — a prior version of this docstring
        incorrectly claimed this was the Basel/EBA reference scenario.)

        Returns:
            The raw API response as a dict.
        """
        body = {
            "retail_deposits": retail_deposits,
            "wholesale_funding": wholesale_funding,
            "hqla_by_level": hqla_by_level,
            "market_haircuts": market_haircuts,
            "retail_runoff": retail_runoff,
            "wholesale_runoff": wholesale_runoff,
            "inflows": inflows,
            "retail_deposits_by_category": retail_deposits_by_category,
            "retail_runoff_rates": retail_runoff_rates,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/combined_stress_scenario", json_body=body
        )

    def contingency_funding_plan_trigger(
        self, *, metrics: dict[str, Any], thresholds: dict[str, Any]
    ) -> dict[str, Any]:
        """Evaluate Contingency Funding Plan (CFP) activation triggers.

        Compares current early-warning metrics against their activation thresholds.
        A metric breaches when its value falls *below* the threshold (lower = worse;
        e.g. LCR, survival days). Returns the list of breached triggers and the CFP
        activation decision.

        This is a logical breach test, not an arithmetic formula, so it is shown on
        the Try-it panel as an indicator function of the comparison rather than a
        computed expression.

        Returns:
            The raw API response as a dict.
        """
        body = {"metrics": metrics, "thresholds": thresholds}
        return self._client._request(
            "POST", "/api/v1/liquidity/contingency_funding_plan_trigger", json_body=body
        )

    def contingent_liquidity_risk(
        self,
        *,
        commitment_amounts: list[float] | list[list[float]],
        draw_probabilities: list[float] | list[list[float]],
        ccf: list[float] | list[list[float]] | None = None,
    ) -> dict[str, Any]:
        """Contingent liquidity risk from undrawn commitments and guarantees.

        When ``ccf`` is not supplied it defaults to 1.0 for every commitment,
        i.e. full drawdown of each commitment is assumed in the expected-outflow
        calculation unless a lower conversion factor is explicitly passed.

        Estimates the expected contingent outflow as ``commitment * draw_probability
        * credit-conversion-factor`` — the liquidity that off-balance-sheet
        commitments (undrawn lines, guarantees) could absorb in stress.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "commitment_amounts": commitment_amounts,
            "draw_probabilities": draw_probabilities,
            "ccf": ccf,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/contingent_liquidity_risk", json_body=body
        )

    def cross_currency_liquidity_bridge(
        self,
        *,
        shortfall_ccy: str,
        shortfall_amount: float,
        surplus_ccy: str,
        surplus_amount: float,
        fx_rate: float,
        swap_haircut: float = 0.0,
    ) -> dict[str, Any]:
        """Cross-currency liquidity bridge via FX swap.

        Sizes the FX swap needed to fund a shortfall in one currency using surplus
        in another. ``fx_rate`` converts one unit of the surplus currency into the
        shortfall currency; a ``swap_haircut`` reduces the usable surplus to reflect
        swap-market stress.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "shortfall_ccy": shortfall_ccy,
            "shortfall_amount": shortfall_amount,
            "surplus_ccy": surplus_ccy,
            "surplus_amount": surplus_amount,
            "fx_rate": fx_rate,
            "swap_haircut": swap_haircut,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/cross_currency_liquidity_bridge", json_body=body
        )

    def deposit_stability_classification(
        self, *, deposit_features: list[float] | list[list[float]], stable_threshold: float = 0.5
    ) -> dict[str, Any]:
        """Classify deposits as stable vs less-stable from a stability score.

        Each deposit carries a stability score in [0, 1] (e.g. derived from
        insurance coverage, transactional relationship, tenor). Deposits at or above
        ``stable_threshold`` are classified stable (lower LCR run-off), the rest
        less-stable.

        Returns:
            The raw API response as a dict.
        """
        body = {"deposit_features": deposit_features, "stable_threshold": stable_threshold}
        return self._client._request(
            "POST", "/api/v1/liquidity/deposit_stability_classification", json_body=body
        )

    def early_warning_indicator_liquidity(
        self,
        *,
        indicators: dict[str, Any],
        thresholds: dict[str, Any],
        directions: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Liquidity early-warning indicator (EWI) dashboard.

        Evaluates each EWI against its threshold and a per-indicator direction
        (``"higher_breach"`` means a value above threshold is a warning, e.g. funding
        spread; ``"lower_breach"`` means below threshold is a warning, e.g. LCR). The
        aggregate signal escalates with the number of triggered indicators.

        This is a direction-dependent logical breach test per indicator, not a
        single arithmetic formula, and the aggregate signal buckets are exact:
        normal (0 triggers), watch (1-2) and alert (3 or more).

        Returns:
            The raw API response as a dict.
        """
        body = {"indicators": indicators, "thresholds": thresholds, "directions": directions}
        return self._client._request(
            "POST", "/api/v1/liquidity/early_warning_indicator_liquidity", json_body=body
        )

    def funding_cost_analysis(
        self,
        *,
        funding_amounts: list[float] | list[list[float]],
        funding_rates: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """Weighted-average funding cost.

        Computes the amount-weighted average cost of the funding base and the total
        annual funding cost in currency terms.

        Returns:
            The raw API response as a dict.
        """
        body = {"funding_amounts": funding_amounts, "funding_rates": funding_rates}
        return self._client._request(
            "POST", "/api/v1/liquidity/funding_cost_analysis", json_body=body
        )

    def funding_tenor_analysis(
        self,
        *,
        funding_amounts: list[float] | list[list[float]],
        tenors_days: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """Weighted-average funding tenor and short-term reliance.

        Computes the amount-weighted average tenor of the funding base and the
        proportion of funding maturing within 90 days — a core ILAAP structural
        metric (longer WAL == more stable funding).

        Returns:
            The raw API response as a dict.
        """
        body = {"funding_amounts": funding_amounts, "tenors_days": tenors_days}
        return self._client._request(
            "POST", "/api/v1/liquidity/funding_tenor_analysis", json_body=body
        )

    def fx_liquidity_risk_by_currency(
        self, *, inflows_by_ccy: dict[str, Any], outflows_by_ccy: dict[str, Any]
    ) -> dict[str, Any]:
        """FX liquidity risk — net position per significant currency.

        Computes the net liquidity gap in each currency (inflows - outflows). A
        significant negative position signals reliance on FX swap markets to fund
        the shortfall — a key vulnerability if swap markets seize.

        Returns:
            The raw API response as a dict.
        """
        body = {"inflows_by_ccy": inflows_by_ccy, "outflows_by_ccy": outflows_by_ccy}
        return self._client._request(
            "POST", "/api/v1/liquidity/fx_liquidity_risk_by_currency", json_body=body
        )

    def hqla_level_1_asset_classifier(
        self,
        *,
        asset_values: list[float] | list[list[float]],
        haircuts: list[float] | list[list[float]] | None = None,
    ) -> dict[str, Any]:
        """Classify and value Level 1 HQLA.

        When ``haircuts`` is not supplied it defaults to all zeros, i.e. no
        haircut is applied and every asset is valued at full market value.

        Level 1 assets (cash, central-bank reserves, 0%-risk-weight sovereign debt)
        receive a 0% haircut by default and have no composition cap (BCBS 238 §50).

        Returns:
            The raw API response as a dict.
        """
        body = {"asset_values": asset_values, "haircuts": haircuts}
        return self._client._request(
            "POST", "/api/v1/liquidity/hqla_level_1_asset_classifier", json_body=body
        )

    def hqla_level_2a_asset_classifier(
        self, *, asset_values: list[float] | list[list[float]], haircut: float = 0.15
    ) -> dict[str, Any]:
        """Classify and value Level 2A HQLA.

        Unlike Level 1's zero-by-default haircut array, ``haircut`` here is a
        single scalar applied uniformly to every asset in ``asset_values``, and
        the function enforces a minimum of 15%.

        Level 2A assets (20%-risk-weight sovereigns, certain covered bonds, high-
        grade corporates) carry a minimum 15% haircut (BCBS 238 §52).

        Returns:
            The raw API response as a dict.
        """
        body = {"asset_values": asset_values, "haircut": haircut}
        return self._client._request(
            "POST", "/api/v1/liquidity/hqla_level_2a_asset_classifier", json_body=body
        )

    def hqla_level_2b_asset_classifier(
        self, *, asset_values: list[float] | list[list[float]], haircut: float = 0.25
    ) -> dict[str, Any]:
        """Classify and value Level 2B HQLA.

        As with Level 2A, ``haircut`` is a single scalar applied uniformly to
        every asset in ``asset_values`` rather than a per-asset array; the
        function enforces a minimum of 25% (pass 0.50 for the lower-grade
        corporate/equity sub-bucket).

        Level 2B assets (RMBS 25% haircut, lower-grade corporates and qualifying
        equities 50% haircut) carry a minimum 25% haircut (BCBS 238 §54).

        Returns:
            The raw API response as a dict.
        """
        body = {"asset_values": asset_values, "haircut": haircut}
        return self._client._request(
            "POST", "/api/v1/liquidity/hqla_level_2b_asset_classifier", json_body=body
        )

    def idiosyncratic_stress_scenario(
        self,
        *,
        retail_deposits: float,
        wholesale_funding: float,
        hqla: float,
        retail_runoff: float = 0.1,
        wholesale_runoff: float = 1.0,
    ) -> dict[str, Any]:
        """Idiosyncratic (name-specific) stress scenario.

        Models a firm-specific crisis (e.g. rating downgrade): partial retail
        deposit flight and complete loss of wholesale funding rollover. Wholesale
        run-off defaults to 100% — the hallmark of a name-specific shock.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "retail_deposits": retail_deposits,
            "wholesale_funding": wholesale_funding,
            "hqla": hqla,
            "retail_runoff": retail_runoff,
            "wholesale_runoff": wholesale_runoff,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/idiosyncratic_stress_scenario", json_body=body
        )

    def ilaap_internal_liquidity_metric(
        self,
        *,
        counterbalancing_capacity: float,
        stressed_net_outflow: float,
        survival_days: float,
        minimum_survival_days: float = 90.0,
    ) -> dict[str, Any]:
        """ILAAP internal liquidity adequacy metric.

        Combines the institution's own counterbalancing-capacity coverage ratio
        (CBC / stressed outflow) with the survival-horizon adequacy versus the
        internal minimum (commonly 90 days). Both must hold for internal adequacy.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "counterbalancing_capacity": counterbalancing_capacity,
            "stressed_net_outflow": stressed_net_outflow,
            "survival_days": survival_days,
            "minimum_survival_days": minimum_survival_days,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/ilaap_internal_liquidity_metric", json_body=body
        )

    def ilaap_stress_testing_framework(self, *, scenarios: dict[str, Any]) -> dict[str, Any]:
        """ILAAP stress-testing framework aggregator.

        Aggregates the outcomes of multiple named liquidity stress scenarios into an
        ILAAP-style summary: the binding (worst) scenario, the count of scenarios
        breached, and overall adequacy. Each scenario value must expose a
        ``surplus_deficit`` figure (as produced by the scenario functions above).

        SD_k in the rendered formula denotes the ``surplus_deficit`` field each
        named scenario dict must already carry — this function only aggregates
        pre-computed values and performs no cash-flow arithmetic itself.

        Returns:
            The raw API response as a dict.
        """
        body = {"scenarios": scenarios}
        return self._client._request(
            "POST", "/api/v1/liquidity/ilaap_stress_testing_framework", json_body=body
        )

    def intraday_liquidity_monitor(
        self,
        *,
        timestamps: list[float] | list[list[float]],
        net_flows: list[float] | list[list[float]],
        opening_balance: float,
    ) -> dict[str, Any]:
        """Intraday liquidity monitor (BCBS 248).

        Of the two figures reported, only ``net_debit_peak`` (the largest negative
        cumulative position) is the genuine BCBS 248 "largest net debit position"
        monitoring tool — ``max_usage`` is this codebase's own additional metric,
        not one of BCBS 248's own monitoring tools.

        Tracks the intraday liquidity position from time-stamped net payment flows
        and reports the peak usage (largest negative intraday position relative to
        the opening balance) and the largest net debit position.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "timestamps": timestamps,
            "net_flows": net_flows,
            "opening_balance": opening_balance,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/intraday_liquidity_monitor", json_body=body
        )

    def intraday_liquidity_stress_test(
        self,
        *,
        net_flows: list[float] | list[list[float]],
        opening_balance: float,
        delay_factor: float = 0.5,
        inflow_delay_shock: float = 0.0,
    ) -> dict[str, Any]:
        """Intraday liquidity stress test (BCBS 248 stress scenarios).

        This is this codebase's own internal stress design — delaying a fraction
        of positive intraday inflows — set in the context of BCBS 248's intraday-
        liquidity monitoring framework; it is not BCBS 248's own prescribed stress
        design.

        Stresses the intraday profile by delaying a fraction of *inflows* (positive
        flows): a ``delay_factor`` of expected inflows is removed from the intraday
        path, sharpening the peak liquidity requirement. Reports the stressed peak
        usage and whether the opening buffer plus any additional shock survives.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "net_flows": net_flows,
            "opening_balance": opening_balance,
            "delay_factor": delay_factor,
            "inflow_delay_shock": inflow_delay_shock,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/intraday_liquidity_stress_test", json_body=body
        )

    def intragroup_liquidity_flow(self, *, entity_positions: dict[str, Any]) -> dict[str, Any]:
        """Intragroup liquidity flow netting.

        Nets bilateral liquidity positions across group entities to derive each
        entity's net provider/receiver status and the total internal liquidity
        transferred. Positive = net provider of liquidity to the group.

        Returns:
            The raw API response as a dict.
        """
        body = {"entity_positions": entity_positions}
        return self._client._request(
            "POST", "/api/v1/liquidity/intragroup_liquidity_flow", json_body=body
        )

    def liquidity_buffer_sizing(
        self,
        *,
        stressed_net_outflows: list[float] | list[list[float]],
        confidence_buffer: float = 0.0,
    ) -> dict[str, Any]:
        """Size the liquidity buffer to the peak cumulative stressed outflow.

        The required buffer equals the maximum cumulative net outflow over the
        stress horizon (the deepest point of the cash-flow trough), optionally
        uplifted by a management ``confidence_buffer`` margin.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "stressed_net_outflows": stressed_net_outflows,
            "confidence_buffer": confidence_buffer,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/liquidity_buffer_sizing", json_body=body
        )

    def liquidity_coverage_ratio_lcr(
        self, *, hqla: float, gross_outflows: float, gross_inflows: float, inflow_cap: float = 0.75
    ) -> dict[str, Any]:
        """Basel III Liquidity Coverage Ratio.

        ``LCR = HQLA / net 30-day outflows`` where net outflows are gross outflows
        minus *capped* inflows. Recognised inflows are floored at ``inflow_cap`` of
        gross outflows (default 75%), guaranteeing net outflows never fall below
        25% of gross — the BCBS 238 §69 cap.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "hqla": hqla,
            "gross_outflows": gross_outflows,
            "gross_inflows": gross_inflows,
            "inflow_cap": inflow_cap,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/liquidity_coverage_ratio_lcr", json_body=body
        )

    def liquidity_gap_analysis(
        self,
        *,
        asset_maturities: list[float] | list[list[float]],
        liability_maturities: list[float] | list[list[float]],
        buckets: list[str] | None = None,
    ) -> dict[str, Any]:
        """Maturity-bucket liquidity gap (assets vs liabilities).

        Computes the structural maturity mismatch: ``gap_i = assets_i -
        liabilities_i`` per bucket, plus the cumulative gap. A positive cumulative
        gap means more assets than liabilities mature by that point (a funding
        surplus); a negative gap signals a refinancing need.

        Like the two cash-flow-ladder functions above, an optional opening balance
        is added to every cumulative-gap entry — the starting cash / HQLA position
        carried into the first bucket. It defaults to 0.0, so existing callers see
        no change in behaviour.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "asset_maturities": asset_maturities,
            "liability_maturities": liability_maturities,
            "buckets": buckets,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/liquidity_gap_analysis", json_body=body
        )

    def liquidity_risk_appetite_threshold(
        self,
        *,
        metric_value: float,
        green_threshold: float,
        amber_threshold: float,
        higher_is_better: bool = True,
    ) -> dict[str, Any]:
        """Map a liquidity metric to a RAG (red/amber/green) risk-appetite zone.

        For ``higher_is_better`` metrics (LCR, NSFR, survival days) green is at or
        above ``green_threshold`` and red below ``amber_threshold``. For
        lower-is-better metrics (e.g. funding concentration) the comparison inverts.

        This is a piecewise categorical rule rather than a continuous formula, and
        the Try-it panel's rendered formula shows only the higher-is-better
        direction; the comparison flips (green <= amber <= metric) when
        ``higher_is_better`` is False.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "metric_value": metric_value,
            "green_threshold": green_threshold,
            "amber_threshold": amber_threshold,
            "higher_is_better": higher_is_better,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/liquidity_risk_appetite_threshold", json_body=body
        )

    def liquidity_scorecard_aggregation(
        self, *, scores: list[float] | list[list[float]], weights: list[float] | list[list[float]]
    ) -> dict[str, Any]:
        """Weighted liquidity scorecard aggregation.

        Combines individual liquidity metric scores (each typically 0-100) into a
        single weighted composite score and maps it to a RAG rating.

        Returns:
            The raw API response as a dict.
        """
        body = {"scores": scores, "weights": weights}
        return self._client._request(
            "POST", "/api/v1/liquidity/liquidity_scorecard_aggregation", json_body=body
        )

    def liquidity_stress_scenario(
        self,
        *,
        balances: list[float] | list[list[float]],
        runoff_rates: list[float] | list[list[float]],
        hqla: float,
        inflows: float = 0.0,
    ) -> dict[str, Any]:
        """Generic single liquidity stress scenario.

        Applies category-specific run-off rates to funding balances to derive
        stressed outflows, nets inflows, and tests whether HQLA covers the net
        stressed outflow.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "balances": balances,
            "runoff_rates": runoff_rates,
            "hqla": hqla,
            "inflows": inflows,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/liquidity_stress_scenario", json_body=body
        )

    def liquidity_transfer_pricing(
        self,
        *,
        notional: float,
        tenor_years: float,
        base_rate: float,
        liquidity_spread: float,
        contingent_spread: float = 0.0,
    ) -> dict[str, Any]:
        """Liquidity Transfer Pricing (LTP) charge for a funding position.

        The FTP charge passes the cost of liquidity to business lines: the all-in
        transfer rate is ``base_rate + term liquidity premium + contingent liquidity
        premium``. The annual charge is that rate applied to notional; the lifetime
        charge multiplies by tenor.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "notional": notional,
            "tenor_years": tenor_years,
            "base_rate": base_rate,
            "liquidity_spread": liquidity_spread,
            "contingent_spread": contingent_spread,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/liquidity_transfer_pricing", json_body=body
        )

    def liquidity_var_liqvar(
        self,
        *,
        base_outflow: float,
        outflow_vol: float,
        confidence_level: float = 0.99,
        n_simulations: int = 100000,
        seed: int | None = 42,
    ) -> dict[str, Any]:
        """Liquidity VaR (LiqVaR) by Monte Carlo simulation of stressed net outflows.

        Simulates the distribution of stressed net cash outflows as
        ``base_outflow * (1 + vol * Z)`` and reads the loss quantile at the
        confidence level. LiqVaR is the outflow level not exceeded with the given
        confidence — the liquidity analogue of market VaR.

        Per CLAUDE.md §3.1 RULE 3 the N(0,1) shocks are pre-drawn in pure Python and
        passed to the JIT kernel; an analytic normal quantile is also returned for
        validation.

        ``liqvar`` is a simulated order statistic of this floored-at-zero
        normal-shock model, cross-validated only against its own analytic
        counterpart ``liqvar_analytic`` rather than a regulatory reference, using
        index ``floor(confidence_level * n_simulations)`` capped at
        ``n_simulations - 1``.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "base_outflow": base_outflow,
            "outflow_vol": outflow_vol,
            "confidence_level": confidence_level,
            "n_simulations": n_simulations,
            "seed": seed,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/liquidity_var_liqvar", json_body=body
        )

    def market_wide_stress_scenario(
        self,
        *,
        hqla_by_level: list[float] | list[list[float]],
        market_haircuts: list[float] | list[list[float]],
        outflow: float,
    ) -> dict[str, Any]:
        """Market-wide stress scenario.

        Models a system-wide crisis where HQLA monetisation value falls due to
        widened market haircuts (flight to quality, fire-sale discounts). Outflows
        are met from the haircut-reduced HQLA value.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "hqla_by_level": hqla_by_level,
            "market_haircuts": market_haircuts,
            "outflow": outflow,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/market_wide_stress_scenario", json_body=body
        )

    def net_stable_funding_ratio_nsfr(
        self, *, available_stable_funding: float, required_stable_funding: float
    ) -> dict[str, Any]:
        """Basel III Net Stable Funding Ratio.

        ``NSFR = ASF / RSF`` and must be >= 100% (BCBS 295). Measures the proportion
        of long-term assets funded by stable funding sources over a one-year horizon.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "available_stable_funding": available_stable_funding,
            "required_stable_funding": required_stable_funding,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/net_stable_funding_ratio_nsfr", json_body=body
        )

    def repo_market_stress_haircut(
        self,
        *,
        base_haircuts: list[float] | list[list[float]],
        stress_multipliers: list[float] | list[list[float]],
        collateral_values: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """Repo market stress — incremental margin call from widened haircuts.

        Under stress, repo haircuts widen by a multiplier. The incremental margin
        requirement is the extra collateral (or cash) the institution must post to
        maintain the same secured borrowing.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "base_haircuts": base_haircuts,
            "stress_multipliers": stress_multipliers,
            "collateral_values": collateral_values,
        }
        return self._client._request(
            "POST", "/api/v1/liquidity/repo_market_stress_haircut", json_body=body
        )

    def required_stable_funding_rsf_calc(
        self,
        *,
        asset_amounts: list[float] | list[list[float]],
        rsf_factors: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """Required Stable Funding for the NSFR denominator.

        RSF is the weighted sum of assets by their RSF factor. More liquid / shorter
        assets attract lower factors (Level 1 HQLA = 5%, Level 2A = 15%, loans = 50-
        85%, illiquid assets = 100%).

        Returns:
            The raw API response as a dict.
        """
        body = {"asset_amounts": asset_amounts, "rsf_factors": rsf_factors}
        return self._client._request(
            "POST", "/api/v1/liquidity/required_stable_funding_rsf_calc", json_body=body
        )

    def retail_deposit_runoff_rate(
        self,
        *,
        deposit_balances: list[float] | list[list[float]],
        runoff_rates: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """Aggregate retail deposit run-off (Basel LCR categories).

        Computes the blended run-off rate across retail deposit categories (e.g.
        stable 5%, less-stable 10%, non-operational higher) and the total expected
        30-day run-off amount.

        Returns:
            The raw API response as a dict.
        """
        body = {"deposit_balances": deposit_balances, "runoff_rates": runoff_rates}
        return self._client._request(
            "POST", "/api/v1/liquidity/retail_deposit_runoff_rate", json_body=body
        )

    def secured_funding_rollover_risk(
        self,
        *,
        maturing_amounts: list[float] | list[list[float]],
        rollover_rates: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """Secured funding (repo) rollover risk.

        Estimates the funding gap from secured transactions that fail to roll: the
        non-rolled portion of each maturing tranche must be replaced or repaid.

        Returns:
            The raw API response as a dict.
        """
        body = {"maturing_amounts": maturing_amounts, "rollover_rates": rollover_rates}
        return self._client._request(
            "POST", "/api/v1/liquidity/secured_funding_rollover_risk", json_body=body
        )

    def survival_horizon_calculator(
        self, *, hqla: float, daily_net_outflows: list[float] | list[list[float]]
    ) -> dict[str, Any]:
        """Survival horizon — days until cumulative net outflow exhausts HQLA.

        Walks forward through the daily net-outflow path subtracting from the HQLA
        counterbalancing capacity. The survival horizon is the last day on which the
        remaining buffer is still non-negative.

        ``survival_days`` is the 0-indexed day on which cumulative outflow first
        drives the buffer negative, so it equals the count of full days survived
        before breach (0 if the very first day breaches).

        Returns:
            The raw API response as a dict.
        """
        body = {"hqla": hqla, "daily_net_outflows": daily_net_outflows}
        return self._client._request(
            "POST", "/api/v1/liquidity/survival_horizon_calculator", json_body=body
        )

    def wholesale_funding_concentration(
        self, *, counterparty_amounts: list[float] | list[list[float]]
    ) -> dict[str, Any]:
        """Wholesale funding concentration via the Herfindahl-Hirschman Index.

        Computes the HHI of funding shares across counterparties (sum of squared
        shares, in [1/n, 1]) plus the largest single-counterparty share. Higher HHI
        means more concentrated, less diversified funding.

        Returns:
            The raw API response as a dict.
        """
        body = {"counterparty_amounts": counterparty_amounts}
        return self._client._request(
            "POST", "/api/v1/liquidity/wholesale_funding_concentration", json_body=body
        )
