"""Generated by codegen/generate.py -- DO NOT EDIT BY HAND.

Regenerate with `python3 codegen/generate.py` from pyvar-client/ after any
change to the API's request schemas. See that script's own module
docstring for what "generated" means here and why.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from pyvar_client._client import Client


class RegulatoryNamespace:
    """Generated methods for this domain -- see pyvar_client._generated's
    own module docstring."""

    def __init__(self, client: "Client") -> None:
        self._client = client

    def aifmd_risk_metrics(
        self,
        *,
        gross_exposure: float,
        commitment_exposure: float,
        net_asset_value: float,
        var_pct: float | None = None,
    ) -> dict[str, Any]:
        """AIFMD Annex IV risk metrics — leverage and (optional) VaR.

        Computes leverage under the gross method and the commitment method (each as
        a multiple of NAV) per Delegated Regulation 231/2013 Art. 7-8. A fund is
        "substantially leveraged" when commitment leverage exceeds 3x NAV.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "gross_exposure": gross_exposure,
            "commitment_exposure": commitment_exposure,
            "net_asset_value": net_asset_value,
            "var_pct": var_pct,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/aifmd_risk_metrics", json_body=body
        )

    def basel_iii_cet1_ratio(
        self, *, cet1_capital: float, risk_weighted_assets: float
    ) -> dict[str, Any]:
        """Basel III Common Equity Tier 1 (CET1) ratio.

        ``CET1 ratio = CET1 capital / RWA``; minimum 4.5% (Basel III §50).

        Returns:
            The raw API response as a dict.
        """
        body = {"cet1_capital": cet1_capital, "risk_weighted_assets": risk_weighted_assets}
        return self._client._request(
            "POST", "/api/v1/regulatory/basel_iii_cet1_ratio", json_body=body
        )

    def basel_iii_leverage_ratio(
        self, *, tier1_capital: float, total_exposure: float
    ) -> dict[str, Any]:
        """Basel III leverage ratio.

        ``Leverage ratio = Tier 1 capital / total exposure measure``; minimum 3.0%.
        The exposure measure is non-risk-weighted (on + off balance sheet).

        Returns:
            The raw API response as a dict.
        """
        body = {"tier1_capital": tier1_capital, "total_exposure": total_exposure}
        return self._client._request(
            "POST", "/api/v1/regulatory/basel_iii_leverage_ratio", json_body=body
        )

    def basel_iii_tier1_ratio(
        self, *, tier1_capital: float, risk_weighted_assets: float
    ) -> dict[str, Any]:
        """Basel III Tier 1 capital ratio.

        ``Tier 1 ratio = Tier 1 capital / RWA``; minimum 6.0% (Basel III §50).

        Returns:
            The raw API response as a dict.
        """
        body = {"tier1_capital": tier1_capital, "risk_weighted_assets": risk_weighted_assets}
        return self._client._request(
            "POST", "/api/v1/regulatory/basel_iii_tier1_ratio", json_body=body
        )

    def basel_iii_total_capital_ratio(
        self, *, total_capital: float, risk_weighted_assets: float
    ) -> dict[str, Any]:
        """Basel III Total capital ratio.

        ``Total ratio = (Tier 1 + Tier 2) / RWA``; minimum 8.0% (Basel III §50).

        Returns:
            The raw API response as a dict.
        """
        body = {"total_capital": total_capital, "risk_weighted_assets": risk_weighted_assets}
        return self._client._request(
            "POST", "/api/v1/regulatory/basel_iii_total_capital_ratio", json_body=body
        )

    def basel_iv_output_floor(
        self, *, internal_model_rwa: float, standardised_rwa: float, floor_factor: float = 0.725
    ) -> dict[str, Any]:
        """Basel IV output floor.

        Floored RWA = ``max(internal_model_rwa, floor_factor * standardised_rwa)``.
        The floor factor is 72.5% (Basel III finalisation) — do not relax.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "internal_model_rwa": internal_model_rwa,
            "standardised_rwa": standardised_rwa,
            "floor_factor": floor_factor,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/basel_iv_output_floor", json_body=body
        )

    def capital_conservation_buffer(
        self, *, cet1_ratio: float, risk_weighted_assets: float, buffer_ratio: float = 0.025
    ) -> dict[str, Any]:
        """Capital Conservation Buffer (CCoB) and distribution constraint.

        The 2.5% CET1 buffer above the 4.5% minimum. Breaching the buffer triggers
        Maximum Distributable Amount (MDA) restrictions on dividends/bonuses.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "cet1_ratio": cet1_ratio,
            "risk_weighted_assets": risk_weighted_assets,
            "buffer_ratio": buffer_ratio,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/capital_conservation_buffer", json_body=body
        )

    def combined_buffer_requirement(
        self,
        *,
        capital_conservation_buffer_ratio: float = 0.025,
        countercyclical_buffer_ratio: float = 0.0,
        systemic_buffer_ratio: float = 0.0,
        risk_weighted_assets: float = 0.0,
    ) -> dict[str, Any]:
        """Combined Buffer Requirement (CBR).

        ``CBR = CCoB + CCyB + max(G-SII, O-SII, SyRB)`` per CRD IV. Sums the buffer
        ratios and (optionally) the capital amount on the supplied RWA.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "capital_conservation_buffer_ratio": capital_conservation_buffer_ratio,
            "countercyclical_buffer_ratio": countercyclical_buffer_ratio,
            "systemic_buffer_ratio": systemic_buffer_ratio,
            "risk_weighted_assets": risk_weighted_assets,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/combined_buffer_requirement", json_body=body
        )

    def countercyclical_capital_buffer(
        self,
        *,
        exposure_amounts: list[float] | list[list[float]],
        country_ccyb_rates: list[float] | list[list[float]],
        risk_weighted_assets: float,
    ) -> dict[str, Any]:
        """Institution-specific Countercyclical Capital Buffer (CCyB).

        The CCyB rate is the exposure-weighted average of the national CCyB rates
        applied to the bank's private-sector credit exposures (CRD IV Art. 140).

        Returns:
            The raw API response as a dict.
        """
        body = {
            "exposure_amounts": exposure_amounts,
            "country_ccyb_rates": country_ccyb_rates,
            "risk_weighted_assets": risk_weighted_assets,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/countercyclical_capital_buffer", json_body=body
        )

    def crr2_large_exposure_limit(
        self, *, exposure_value: float, tier1_capital: float, is_institution: bool = False
    ) -> dict[str, Any]:
        """CRR2 large exposure limit (Art. 395).

        A single client / group exposure must not exceed 25% of Tier 1 capital
        (or EUR 150m for institutions, whichever is higher — simplified to the 25%
        ratio test here). Reports the exposure ratio and any breach amount.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "exposure_value": exposure_value,
            "tier1_capital": tier1_capital,
            "is_institution": is_institution,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/crr2_large_exposure_limit", json_body=body
        )

    def emir_clearing_obligation_check(
        self,
        *,
        notionals: dict[str, Any],
        counterparty_category: str,
        clearing_thresholds: dict[str, Any],
    ) -> dict[str, Any]:
        """EMIR clearing obligation check (Art. 4 / Art. 4a / Art. 10 / clearing thresholds).

        [REGULATORY] EMIR REFIT (Regulation (EU) 2019/834) Art. 4a(1): a Financial
        Counterparty (FC) that breaches its clearing threshold in ANY ONE OTC
        derivative asset class becomes subject to the clearing obligation for ALL
        asset classes it has positions in, not just the one that breached. Art.
        10(1) evaluates a Non-Financial Counterparty above threshold (NFC+)
        per-asset-class instead -- only the classes where ITS OWN threshold is
        breached become subject to clearing.

        A prior version of this function applied FC's per-class-only logic to
        BOTH categories (took a single ``asset_class``/``notional`` pair,
        identical branching for FC and NFC+ beyond the NFC- exemption). It
        understated an FC's clearing scope whenever the breaching class differed
        from the queried class -- masked in the original test, which happened to
        query the same class that breached. Found during the Tier 3 #2 audit.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "notionals": notionals,
            "counterparty_category": counterparty_category,
            "clearing_thresholds": clearing_thresholds,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/emir_clearing_obligation_check", json_body=body
        )

    def emir_margin_requirement(
        self,
        *,
        portfolio_value: float,
        initial_margin_rate: float,
        variation_margin: float,
        minimum_transfer_amount: float = 0.0,
    ) -> dict[str, Any]:
        """EMIR (Art. 11) uncleared-derivatives margin requirement.

        Computes the Initial Margin (IM) from the rate and the net margin call after
        applying the Minimum Transfer Amount (MTA) to the variation margin.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "portfolio_value": portfolio_value,
            "initial_margin_rate": initial_margin_rate,
            "variation_margin": variation_margin,
            "minimum_transfer_amount": minimum_transfer_amount,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/emir_margin_requirement", json_body=body
        )

    def emir_trade_repository_report(self, *, trade: dict[str, Any]) -> dict[str, Any]:
        """EMIR trade repository report builder/validator.

        Validates the core EMIR reporting fields (counterparty LEIs, UTI, notional,
        asset class) and echoes a normalised report.

        Returns:
            The raw API response as a dict.
        """
        body = {"trade": trade}
        return self._client._request(
            "POST", "/api/v1/regulatory/emir_trade_repository_report", json_body=body
        )

    def frtb_ima_market_risk_capital(
        self,
        *,
        expected_shortfall: float,
        stressed_es_ratio: float,
        multiplier: float,
        non_modellable_ses: float = 0.0,
        default_risk_charge: float = 0.0,
    ) -> dict[str, Any]:
        """FRTB Internal Models Approach total market-risk capital.

        The IMA charge combines the multiplier-scaled, stressed-scaled Expected
        Shortfall (the "IMCC" proxy) with the non-modellable risk factor capital
        (SES) and the Default Risk Charge (BCBS d457 §189). The multiplier is
        floored at 1.5.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "expected_shortfall": expected_shortfall,
            "stressed_es_ratio": stressed_es_ratio,
            "multiplier": multiplier,
            "non_modellable_ses": non_modellable_ses,
            "default_risk_charge": default_risk_charge,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/frtb_ima_market_risk_capital", json_body=body
        )

    def frtb_pl_attribution_test(
        self,
        *,
        risk_theoretical_pnl: list[float] | list[list[float]],
        hypothetical_pnl: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """FRTB P&L Attribution Test (PAT) — Spearman correlation + variance ratio.

        Jointly evaluates the Spearman rank correlation between risk-theoretical P&L
        (RTPL) and hypothetical P&L (HPL) and the volatility ratio
        ``std(RTPL)/std(HPL)``, assigning the Basel traffic-light zone. The
        thresholds are mandated by BCBS d457 and CLAUDE.md §4.4:
        green ``|corr|>=0.80 AND 0.8<=ratio<=1.2``;
        amber ``|corr|>=0.70 AND 0.6<=ratio<=1.5``; otherwise red (IMA loss).

        Returns:
            The raw API response as a dict.
        """
        body = {"risk_theoretical_pnl": risk_theoretical_pnl, "hypothetical_pnl": hypothetical_pnl}
        return self._client._request(
            "POST", "/api/v1/regulatory/frtb_pl_attribution_test", json_body=body
        )

    def frtb_sa_market_risk_capital(
        self, *, sensitivities_charge: float, default_risk_charge: float, residual_risk_addon: float
    ) -> dict[str, Any]:
        """FRTB Standardised Approach total market-risk capital.

        The SA capital is the simple sum of the Sensitivities-Based Method charge
        (already aggregated across delta/vega/curvature and the three correlation
        scenarios), the Default Risk Charge (DRC) and the Residual Risk Add-On
        (RRAO) (BCBS d457 §2).

        Returns:
            The raw API response as a dict.
        """
        body = {
            "sensitivities_charge": sensitivities_charge,
            "default_risk_charge": default_risk_charge,
            "residual_risk_addon": residual_risk_addon,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/frtb_sa_market_risk_capital", json_body=body
        )

    def frtb_trading_desk_aggregation(
        self,
        *,
        desk_sa_charges: list[float] | list[list[float]],
        desk_ima_charges: list[float] | list[list[float]],
        desk_ima_eligible: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """FRTB trading-desk capital aggregation.

        Aggregates per-desk capital: IMA-eligible desks contribute their IMA charge,
        non-eligible (PAT-red / backtest-failed) desks fall back to the SA charge.
        The total firm-wide market-risk capital is the sum across desks (BCBS d457
        treats the firm charge as the sum of approved-desk IMA plus SA for the rest).

        Returns:
            The raw API response as a dict.
        """
        body = {
            "desk_sa_charges": desk_sa_charges,
            "desk_ima_charges": desk_ima_charges,
            "desk_ima_eligible": desk_ima_eligible,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/frtb_trading_desk_aggregation", json_body=body
        )

    def icaap_capital_assessment(
        self,
        *,
        pillar1_capital: float,
        risk_capital_components: list[float] | list[list[float]],
        available_capital: float,
    ) -> dict[str, Any]:
        """ICAAP internal capital adequacy assessment.

        Aggregates Pillar 1 capital with internally-assessed risk components
        (credit concentration, IRRBB, etc.) and compares to available capital.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "pillar1_capital": pillar1_capital,
            "risk_capital_components": risk_capital_components,
            "available_capital": available_capital,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/icaap_capital_assessment", json_body=body
        )

    def mifid_ii_algorithm_documentation(self, *, documentation: dict[str, Any]) -> dict[str, Any]:
        """MiFID II RTS 6 algorithmic-trading documentation completeness check.

        Verifies that the mandatory governance and control documentation items for
        an algorithmic trading strategy are present.

        Returns:
            The raw API response as a dict.
        """
        body = {"documentation": documentation}
        return self._client._request(
            "POST", "/api/v1/regulatory/mifid_ii_algorithm_documentation", json_body=body
        )

    def mifid_ii_best_execution_metric(
        self,
        *,
        executed_prices: list[float] | list[list[float]],
        benchmark_prices: list[float] | list[list[float]],
        quantities: list[float] | list[list[float]],
        side: int = 1,
    ) -> dict[str, Any]:
        """MiFID II best-execution TCA metric -- internal, NOT an RTS 27/28 figure.

        Computes the quantity-weighted price improvement (or slippage) of executions
        versus a reference (e.g. EBBO) price, in basis points. Positive means price
        improvement for the client.

        This does not correspond to any specific RTS 27/28 field: RTS 27
        (Commission Delegated Regulation (EU) 2017/575) requires simple-average
        and volume-weighted transaction prices/spreads/best-bid-offer (Annex
        Tables 1-9), and RTS 28 (DR (EU) 2017/576) requires execution-venue
        rankings -- neither defines a quantity-weighted price-improvement-in-bps
        metric like this one. RTS 27 was also repealed by the 2024 MiFIR review.
        A prior version of this docstring cited "RTS 27/28" directly; corrected
        during the Tier 3 #2 audit. This remains a reasonable internal TCA
        metric, just not a regulatory-prescribed one.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "executed_prices": executed_prices,
            "benchmark_prices": benchmark_prices,
            "quantities": quantities,
            "side": side,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/mifid_ii_best_execution_metric", json_body=body
        )

    def mifid_ii_post_trade_transparency(
        self, *, trade_size: float, delayed_publication_threshold: float, is_liquid: bool = True
    ) -> dict[str, Any]:
        """MiFID II post-trade transparency / deferred-publication assessment.

        Trades above the size threshold (or in illiquid instruments) may benefit
        from deferred publication; otherwise publication is near real-time.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "trade_size": trade_size,
            "delayed_publication_threshold": delayed_publication_threshold,
            "is_liquid": is_liquid,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/mifid_ii_post_trade_transparency", json_body=body
        )

    def mifid_ii_pre_trade_transparency(
        self,
        *,
        instrument_type: str,
        order_size: float,
        large_in_scale_threshold: float,
        is_liquid: bool = True,
    ) -> dict[str, Any]:
        """MiFID II pre-trade transparency / LIS waiver assessment.

        Determines whether an order qualifies for the Large-in-Scale (LIS) waiver
        from pre-trade transparency (illiquid instruments and orders above the LIS
        threshold may be waived).

        Returns:
            The raw API response as a dict.
        """
        body = {
            "instrument_type": instrument_type,
            "order_size": order_size,
            "large_in_scale_threshold": large_in_scale_threshold,
            "is_liquid": is_liquid,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/mifid_ii_pre_trade_transparency", json_body=body
        )

    def mifid_ii_transaction_report_validator(self, *, report: dict[str, Any]) -> dict[str, Any]:
        """MiFID II / RTS 22 transaction report field validator.

        Checks the presence and basic validity of the mandatory transaction-report
        fields (LEI length, ISIN length, positive price/quantity).

        Returns:
            The raw API response as a dict.
        """
        body = {"report": report}
        return self._client._request(
            "POST", "/api/v1/regulatory/mifid_ii_transaction_report_validator", json_body=body
        )

    def pillar_2a_capital(
        self, *, risk_addons: list[float] | list[list[float]], risk_weighted_assets: float
    ) -> dict[str, Any]:
        """Pillar 2A capital — sum of individual risk add-ons.

        Pillar 2A covers risks not (fully) captured in Pillar 1: e.g. credit
        concentration, IRRBB, pension, operational. Sums the component charges.

        Returns:
            The raw API response as a dict.
        """
        body = {"risk_addons": risk_addons, "risk_weighted_assets": risk_weighted_assets}
        return self._client._request("POST", "/api/v1/regulatory/pillar_2a_capital", json_body=body)

    def pillar_2b_stress_buffer(
        self, *, stressed_capital_depletion: float, risk_weighted_assets: float
    ) -> dict[str, Any]:
        """Pillar 2B stress buffer (PRA buffer / capital guidance).

        The forward-looking buffer to absorb the peak capital depletion projected
        under the supervisory stress scenario.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "stressed_capital_depletion": stressed_capital_depletion,
            "risk_weighted_assets": risk_weighted_assets,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/pillar_2b_stress_buffer", json_body=body
        )

    def sftr_securities_finance_report(self, *, transaction: dict[str, Any]) -> dict[str, Any]:
        """SFTR securities-financing transaction report builder/validator.

        Validates the core SFTR fields for an SFT (repo, securities lending, buy-
        sell back, margin lending): counterparties, UTI, collateral and the SFT
        type.

        Returns:
            The raw API response as a dict.
        """
        body = {"transaction": transaction}
        return self._client._request(
            "POST", "/api/v1/regulatory/sftr_securities_finance_report", json_body=body
        )

    def solvency_ii_scr_credit_risk(
        self,
        *,
        exposures: list[float] | list[list[float]],
        loss_given_default: list[float] | list[list[float]],
        default_probabilities: list[float] | list[list[float]],
    ) -> dict[str, Any]:
        """Solvency II SCR counterparty default (credit) risk — Type 1 exposures.

        [REGULATORY] Delegated Regulation (EU) 2015/35 Art. 200(1)-(3) fixes the
        capital charge as a TIERED multiplier on the standard deviation (sigma) of
        the loss distribution, not a flat 3x: SCR = 3*sigma while
        sigma <= 7% of total LGD; SCR = 5*sigma while 7% < sigma/TLGD <= 20%; SCR =
        total LGD (fully capped) once sigma/TLGD exceeds 20%. An earlier version of
        this function exposed a caller-configurable ``risk_factor`` defaulting to a
        flat 3.0 — that understated capital by ~79% on a representative 2-exposure
        case (807 vs. the correct ~1449, entirely from missing the 5x/TLGD tiers).
        The multiplier is fixed by the Delegated Regulation, so it is intentionally
        not a parameter here (same reasoning as CLAUDE.md §4.3/§4.4's Basel
        thresholds: never parameterise regulator-set constants).

        [LIMITATION] The variance (sigma^2) computed here is the intra-counterparty
        term only — an independent-Bernoulli approximation summing each
        counterparty's own default-loss variance. Art. 201's full formula also adds
        an inter-counterparty correlation term (V_inter) between exposures carrying
        different default probabilities, which this implementation does NOT
        compute — that term is generally positive, so the true Art. 201 variance
        (and therefore the true SCR) is at least as large as what this function
        returns. Do not rely on this for statutory Solvency II reporting without an
        actuarial review of that gap.

        Returns:
            The raw API response as a dict.
        """
        body = {
            "exposures": exposures,
            "loss_given_default": loss_given_default,
            "default_probabilities": default_probabilities,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/solvency_ii_scr_credit_risk", json_body=body
        )

    def solvency_ii_scr_market_risk(
        self,
        *,
        sub_module_charges: list[float] | list[list[float]],
        correlation_matrix: list[float] | list[list[float]],
        sub_module_names: list[str] | None = None,
    ) -> dict[str, Any]:
        """Solvency II SCR Market risk — standard-formula modular aggregation.

        Aggregates the market sub-module capital charges (interest rate, equity,
        property, spread, currency, concentration) using the prescribed correlation
        matrix and the square-root formula ``SCR = sqrt(s' Corr s)`` (Delegated
        Regulation 2015/35 Art. 164).

        Returns:
            The raw API response as a dict.
        """
        body = {
            "sub_module_charges": sub_module_charges,
            "correlation_matrix": correlation_matrix,
            "sub_module_names": sub_module_names,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/solvency_ii_scr_market_risk", json_body=body
        )

    def srep_capital_add_on(
        self,
        *,
        pillar1_requirement: float,
        pillar2a_addon_ratio: float,
        risk_weighted_assets: float,
    ) -> dict[str, Any]:
        """SREP (Supervisory Review and Evaluation Process) capital add-on.

        Translates the supervisory Pillar 2A add-on ratio into a capital amount and
        the Total SREP Capital Requirement (TSCR).

        Returns:
            The raw API response as a dict.
        """
        body = {
            "pillar1_requirement": pillar1_requirement,
            "pillar2a_addon_ratio": pillar2a_addon_ratio,
            "risk_weighted_assets": risk_weighted_assets,
        }
        return self._client._request(
            "POST", "/api/v1/regulatory/srep_capital_add_on", json_body=body
        )

    def ucits_kiid_risk_indicator(
        self, *, returns: list[float] | list[list[float]], periods_per_year: int = 52
    ) -> dict[str, Any]:
        """UCITS KIID Synthetic Risk and Reward Indicator (SRRI), 1-7.

        Maps the annualised volatility of (weekly by default) returns to the SRRI
        bucket per CESR 10-673: class 1 (< 0.5%) up to class 7 (>= 25%).

        Returns:
            The raw API response as a dict.
        """
        body = {"returns": returns, "periods_per_year": periods_per_year}
        return self._client._request(
            "POST", "/api/v1/regulatory/ucits_kiid_risk_indicator", json_body=body
        )
