"""tests/test_alm_api.py — integration tests for the alm domain.

Auto-generated by scripts/gen_p3.py. Covers, across the whole domain:
  - route registration (count matches the engine surface),
  - authentication (every route rejects a missing bearer token),
  - input robustness (empty body never 500s — always 200 or 422),
  - curated happy paths that exercise the engine and assert HTTP 200.
"""

from __future__ import annotations

import pytest
from httpx import ASGITransport, AsyncClient

from api.middleware.auth import create_access_token
from ingestion.fixtures import generate_gbm_returns
from main import create_app

DOMAIN = "alm"
EXPECTED_ROUTES = 33

R1 = generate_gbm_returns(n_obs=252, seed=1).tolist()
R2 = generate_gbm_returns(n_obs=252, seed=2).tolist()
MEAN = [0.08, 0.10, 0.12]
COV = [[0.04, 0.01, 0.0], [0.01, 0.05, 0.01], [0.0, 0.01, 0.06]]


@pytest.fixture(scope="module")
def app():
    return create_app()


@pytest.fixture
def headers():
    return {"Authorization": f"Bearer {create_access_token('tester', 'enterprise')}"}


def _domain_routes(app) -> list[str]:
    prefix = f"/api/v1/{DOMAIN}/"
    return sorted(
        {
            getattr(r, "path", "")
            for r in app.routes
            if getattr(r, "path", "").startswith(prefix) and "POST" in getattr(r, "methods", set())
        }
    )


def _client(app) -> AsyncClient:
    return AsyncClient(transport=ASGITransport(app=app), base_url="http://test")


def test_routes_registered(app):
    assert len(_domain_routes(app)) == EXPECTED_ROUTES


@pytest.mark.asyncio
async def test_all_routes_require_auth(app):
    async with _client(app) as client:
        for path in _domain_routes(app):
            resp = await client.post(path, json={})
            assert resp.status_code in (401, 403), path


@pytest.mark.asyncio
async def test_empty_body_never_500(app, headers):
    async with _client(app) as client:
        for path in _domain_routes(app):
            resp = await client.post(path, json={}, headers=headers)
            assert resp.status_code in (200, 422), f"{path} -> {resp.status_code}"


HAPPY_PATHS = [
    (
        "duration_gap_analysis",
        {
            "asset_duration": 5.0,
            "liability_duration": 3.0,
            "total_assets": 1000.0,
            "total_liabilities": 900.0,
        },
    ),
]


@pytest.mark.parametrize("endpoint,body", HAPPY_PATHS)
@pytest.mark.asyncio
async def test_happy_path(app, headers, endpoint, body):
    path = f"/api/v1/{DOMAIN}/{endpoint}"
    async with _client(app) as client:
        resp = await client.post(path, json=body, headers=headers)
    assert resp.status_code == 200, f"{path} -> {resp.text[:200]}"
    data = resp.json()
    assert isinstance(data, dict) and data
