"""
migrations/env.py — Alembic migration environment

Reasoning:
- Aurora SV2 uses asyncpg in the application but Alembic requires a
  synchronous connection for migrations. We use psycopg2 here ONLY
  for migration runs. The application never uses psycopg2.
- target_metadata = Base.metadata ensures Alembic can autogenerate
  migration scripts by comparing the current DB schema to the ORM models.
- include_schemas=True detects schema-level changes (e.g. new schemas).
- compare_type=True detects column type changes (e.g. String → Text).
  Without this, Alembic ignores type changes in autogenerated scripts.
- The POSTGRES_DSN env var uses the asyncpg URL format (postgresql+asyncpg://).
  We strip the +asyncpg driver suffix for psycopg2 compatibility.
"""

from __future__ import annotations

import re
from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config, pool

# Import all ORM models so Alembic can see their metadata
# ADD NEW MODELS HERE when new tables are created
from storage.models import Base

# Alembic Config object
config = context.config

# Set up Python logging from alembic.ini
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# Metadata for autogenerate support
target_metadata = Base.metadata


def get_sync_url() -> str:
    """
    Convert asyncpg DSN to psycopg2 DSN for Alembic.
    postgresql+asyncpg://user:pass@host/db → postgresql://user:pass@host/db
    """
    import os

    url = os.environ.get("POSTGRES_DSN", config.get_main_option("sqlalchemy.url", ""))
    # Strip async driver suffix
    url = re.sub(r"\+asyncpg", "", url)
    return url


def run_migrations_offline() -> None:
    """
    Run migrations in 'offline' mode — generates SQL without a live DB connection.
    Useful for reviewing changes before applying, or for DBA approval workflows.
    Run with: alembic upgrade head --sql > migration.sql
    """
    url = get_sync_url()
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        include_schemas=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """
    Run migrations in 'online' mode against a live DB connection.
    Standard path for CI/CD pipeline pre-deploy step.
    """
    configuration = config.get_section(config.config_ini_section, {})
    configuration["sqlalchemy.url"] = get_sync_url()

    connectable = engine_from_config(
        configuration,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # no connection pooling in migration runs
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,  # detect column type changes
            compare_server_default=True,  # detect default value changes
            include_schemas=True,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
