"""schemas/liquidity.py — auto-generated Pydantic v2 contracts for the liquidity domain.

Generated by scripts/gen_p3.py from engine signatures. Request models are
precisely typed and enforce regulatory validators (CLAUDE.md s4). Response
models document engine return-dict keys; extra='allow' covers dynamically
built keys that static analysis cannot enumerate.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class LiquidityCoverageRatioLcrRequest(BaseModel):
    """Request parameters for liquidity_coverage_ratio_lcr()."""

    hqla: float
    gross_outflows: float
    gross_inflows: float
    inflow_cap: float = 0.75


class LiquidityCoverageRatioLcrResponse(BaseModel):
    """Result of liquidity_coverage_ratio_lcr(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    capped_inflows: Any = Field(default=None)
    compliant: Any = Field(default=None)
    hqla: Any = Field(default=None)
    lcr: Any = Field(default=None)
    net_outflows: Any = Field(default=None)


class AvailableStableFundingAsfCalcRequest(BaseModel):
    """Request parameters for available_stable_funding_asf_calc()."""

    funding_amounts: list[float] | list[list[float]]
    asf_factors: list[float] | list[list[float]]


class AvailableStableFundingAsfCalcResponse(BaseModel):
    """Result of available_stable_funding_asf_calc(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    asf: Any = Field(default=None)
    components: Any = Field(default=None)


class RequiredStableFundingRsfCalcRequest(BaseModel):
    """Request parameters for required_stable_funding_rsf_calc()."""

    asset_amounts: list[float] | list[list[float]]
    rsf_factors: list[float] | list[list[float]]


class RequiredStableFundingRsfCalcResponse(BaseModel):
    """Result of required_stable_funding_rsf_calc(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    components: Any = Field(default=None)
    rsf: Any = Field(default=None)


class NetStableFundingRatioNsfrRequest(BaseModel):
    """Request parameters for net_stable_funding_ratio_nsfr()."""

    available_stable_funding: float
    required_stable_funding: float


class NetStableFundingRatioNsfrResponse(BaseModel):
    """Result of net_stable_funding_ratio_nsfr(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    asf: Any = Field(default=None)
    compliant: Any = Field(default=None)
    nsfr: Any = Field(default=None)
    rsf: Any = Field(default=None)


class HqlaLevel1AssetClassifierRequest(BaseModel):
    """Request parameters for hqla_level_1_asset_classifier()."""

    asset_values: list[float] | list[list[float]]
    haircuts: list[float] | list[list[float]] | None = None


class HqlaLevel1AssetClassifierResponse(BaseModel):
    """Result of hqla_level_1_asset_classifier(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    adjusted_values: Any = Field(default=None)
    level: Any = Field(default=None)
    post_haircut_value: Any = Field(default=None)


class HqlaLevel2aAssetClassifierRequest(BaseModel):
    """Request parameters for hqla_level_2a_asset_classifier()."""

    asset_values: list[float] | list[list[float]]
    haircut: float = 0.15


class HqlaLevel2aAssetClassifierResponse(BaseModel):
    """Result of hqla_level_2a_asset_classifier(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    adjusted_values: Any = Field(default=None)
    haircut: Any = Field(default=None)
    level: Any = Field(default=None)
    post_haircut_value: Any = Field(default=None)


class HqlaLevel2bAssetClassifierRequest(BaseModel):
    """Request parameters for hqla_level_2b_asset_classifier()."""

    asset_values: list[float] | list[list[float]]
    haircut: float = 0.25


class HqlaLevel2bAssetClassifierResponse(BaseModel):
    """Result of hqla_level_2b_asset_classifier(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    adjusted_values: Any = Field(default=None)
    haircut: Any = Field(default=None)
    level: Any = Field(default=None)
    post_haircut_value: Any = Field(default=None)


class CashFlowLadder30DayRequest(BaseModel):
    """Request parameters for cash_flow_ladder_30_day()."""

    daily_inflows: list[float] | list[list[float]]
    daily_outflows: list[float] | list[list[float]]
    opening_balance: float = 0.0


class CashFlowLadder30DayResponse(BaseModel):
    """Result of cash_flow_ladder_30_day(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    cumulative_gap: Any = Field(default=None)
    horizon_days: Any = Field(default=None)
    min_cumulative: Any = Field(default=None)
    min_day: Any = Field(default=None)
    net_gap: Any = Field(default=None)


class CashFlowLadder1YearRequest(BaseModel):
    """Request parameters for cash_flow_ladder_1_year()."""

    bucket_inflows: list[float] | list[list[float]]
    bucket_outflows: list[float] | list[list[float]]
    opening_balance: float = 0.0
    buckets: list[str] | None = None


class CashFlowLadder1YearResponse(BaseModel):
    """Result of cash_flow_ladder_1_year(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    buckets: Any = Field(default=None)
    cumulative_gap: Any = Field(default=None)
    min_cumulative: Any = Field(default=None)
    net_gap: Any = Field(default=None)


class LiquidityGapAnalysisRequest(BaseModel):
    """Request parameters for liquidity_gap_analysis()."""

    asset_maturities: list[float] | list[list[float]]
    liability_maturities: list[float] | list[list[float]]
    buckets: list[str] | None = None


class LiquidityGapAnalysisResponse(BaseModel):
    """Result of liquidity_gap_analysis(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    buckets: Any = Field(default=None)
    cumulative_gap: Any = Field(default=None)
    gap_ratio: Any = Field(default=None)
    periodic_gap: Any = Field(default=None)


class FundingTenorAnalysisRequest(BaseModel):
    """Request parameters for funding_tenor_analysis()."""

    funding_amounts: list[float] | list[list[float]]
    tenors_days: list[float] | list[list[float]]


class FundingTenorAnalysisResponse(BaseModel):
    """Result of funding_tenor_analysis(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    short_term_ratio: Any = Field(default=None)
    total_funding: Any = Field(default=None)
    weighted_avg_tenor_days: Any = Field(default=None)


class LiquidityStressScenarioRequest(BaseModel):
    """Request parameters for liquidity_stress_scenario()."""

    balances: list[float] | list[list[float]]
    runoff_rates: list[float] | list[list[float]]
    hqla: float
    inflows: float = 0.0


class LiquidityStressScenarioResponse(BaseModel):
    """Result of liquidity_stress_scenario(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    net_outflow: Any = Field(default=None)
    stressed_outflow: Any = Field(default=None)
    surplus_deficit: Any = Field(default=None)
    survives: Any = Field(default=None)


class IdiosyncraticStressScenarioRequest(BaseModel):
    """Request parameters for idiosyncratic_stress_scenario()."""

    retail_deposits: float
    wholesale_funding: float
    hqla: float
    retail_runoff: float = 0.1
    wholesale_runoff: float = 1.0


class IdiosyncraticStressScenarioResponse(BaseModel):
    """Result of idiosyncratic_stress_scenario(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    scenario: Any = Field(default=None)
    stressed_outflow: Any = Field(default=None)
    surplus_deficit: Any = Field(default=None)
    survives: Any = Field(default=None)


class MarketWideStressScenarioRequest(BaseModel):
    """Request parameters for market_wide_stress_scenario()."""

    hqla_by_level: list[float] | list[list[float]]
    market_haircuts: list[float] | list[list[float]]
    outflow: float


class MarketWideStressScenarioResponse(BaseModel):
    """Result of market_wide_stress_scenario(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    scenario: Any = Field(default=None)
    stressed_hqla: Any = Field(default=None)
    surplus_deficit: Any = Field(default=None)
    survives: Any = Field(default=None)


class CombinedStressScenarioRequest(BaseModel):
    """Request parameters for combined_stress_scenario()."""

    retail_deposits: float
    wholesale_funding: float
    hqla_by_level: list[float] | list[list[float]]
    market_haircuts: list[float] | list[list[float]]
    retail_runoff: float = 0.15
    wholesale_runoff: float = 1.0
    inflows: float = 0.0
    retail_deposits_by_category: list[float] | list[list[float]] | None = None
    retail_runoff_rates: list[float] | list[list[float]] | None = None


class CombinedStressScenarioResponse(BaseModel):
    """Result of combined_stress_scenario(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    net_outflow: Any = Field(default=None)
    scenario: Any = Field(default=None)
    stressed_hqla: Any = Field(default=None)
    stressed_outflow: Any = Field(default=None)
    surplus_deficit: Any = Field(default=None)
    survives: Any = Field(default=None)


class SurvivalHorizonCalculatorRequest(BaseModel):
    """Request parameters for survival_horizon_calculator()."""

    hqla: float
    daily_net_outflows: list[float] | list[list[float]]


class SurvivalHorizonCalculatorResponse(BaseModel):
    """Result of survival_horizon_calculator(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    hqla: Any = Field(default=None)
    survival_days: Any = Field(default=None)
    terminal_buffer: Any = Field(default=None)


class IntradayLiquidityMonitorRequest(BaseModel):
    """Request parameters for intraday_liquidity_monitor()."""

    timestamps: list[float] | list[list[float]]
    net_flows: list[float] | list[list[float]]
    opening_balance: float


class IntradayLiquidityMonitorResponse(BaseModel):
    """Result of intraday_liquidity_monitor(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    closing_balance: Any = Field(default=None)
    max_usage: Any = Field(default=None)
    min_balance: Any = Field(default=None)
    net_debit_peak: Any = Field(default=None)


class IntradayLiquidityStressTestRequest(BaseModel):
    """Request parameters for intraday_liquidity_stress_test()."""

    net_flows: list[float] | list[list[float]]
    opening_balance: float
    delay_factor: float = 0.5
    inflow_delay_shock: float = 0.0


class IntradayLiquidityStressTestResponse(BaseModel):
    """Result of intraday_liquidity_stress_test(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    stressed_max_usage: Any = Field(default=None)
    stressed_min_balance: Any = Field(default=None)
    survives: Any = Field(default=None)


class IlaapStressTestingFrameworkRequest(BaseModel):
    """Request parameters for ilaap_stress_testing_framework()."""

    scenarios: dict[str, Any]


class IlaapStressTestingFrameworkResponse(BaseModel):
    """Result of ilaap_stress_testing_framework(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    adequate: Any = Field(default=None)
    binding_scenario: Any = Field(default=None)
    num_breached: Any = Field(default=None)
    worst_surplus_deficit: Any = Field(default=None)


class LiquidityVarLiqvarRequest(BaseModel):
    """Request parameters for liquidity_var_liqvar()."""

    base_outflow: float
    outflow_vol: float
    confidence_level: float = 0.99
    n_simulations: int = 100000
    seed: int | None = 42

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class LiquidityVarLiqvarResponse(BaseModel):
    """Result of liquidity_var_liqvar(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    expected_outflow: Any = Field(default=None)
    liqvar: Any = Field(default=None)
    liqvar_analytic: Any = Field(default=None)
    n_simulations: Any = Field(default=None)


class LiquidityBufferSizingRequest(BaseModel):
    """Request parameters for liquidity_buffer_sizing()."""

    stressed_net_outflows: list[float] | list[list[float]]
    confidence_buffer: float = 0.0


class LiquidityBufferSizingResponse(BaseModel):
    """Result of liquidity_buffer_sizing(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    peak_cumulative_outflow: Any = Field(default=None)
    peak_period: Any = Field(default=None)
    required_buffer: Any = Field(default=None)


class ContingencyFundingPlanTriggerRequest(BaseModel):
    """Request parameters for contingency_funding_plan_trigger()."""

    metrics: dict[str, Any]
    thresholds: dict[str, Any]


class ContingencyFundingPlanTriggerResponse(BaseModel):
    """Result of contingency_funding_plan_trigger(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    breached: Any = Field(default=None)
    cfp_activated: Any = Field(default=None)
    num_breached: Any = Field(default=None)


class WholesaleFundingConcentrationRequest(BaseModel):
    """Request parameters for wholesale_funding_concentration()."""

    counterparty_amounts: list[float] | list[list[float]]


class WholesaleFundingConcentrationResponse(BaseModel):
    """Result of wholesale_funding_concentration(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    effective_counterparties: Any = Field(default=None)
    hhi: Any = Field(default=None)
    top1_share: Any = Field(default=None)
    top5_share: Any = Field(default=None)


class RetailDepositRunoffRateRequest(BaseModel):
    """Request parameters for retail_deposit_runoff_rate()."""

    deposit_balances: list[float] | list[list[float]]
    runoff_rates: list[float] | list[list[float]]


class RetailDepositRunoffRateResponse(BaseModel):
    """Result of retail_deposit_runoff_rate(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    blended_rate: Any = Field(default=None)
    runoff_amounts: Any = Field(default=None)
    total_runoff: Any = Field(default=None)


class SecuredFundingRolloverRiskRequest(BaseModel):
    """Request parameters for secured_funding_rollover_risk()."""

    maturing_amounts: list[float] | list[list[float]]
    rollover_rates: list[float] | list[list[float]]


class SecuredFundingRolloverRiskResponse(BaseModel):
    """Result of secured_funding_rollover_risk(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    effective_rollover_rate: Any = Field(default=None)
    rolled_amount: Any = Field(default=None)
    rollover_gap: Any = Field(default=None)


class AssetEncumbranceRatioRequest(BaseModel):
    """Request parameters for asset_encumbrance_ratio()."""

    encumbered_assets: float
    total_assets: float


class AssetEncumbranceRatioResponse(BaseModel):
    """Result of asset_encumbrance_ratio(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    encumbrance_ratio: Any = Field(default=None)
    unencumbered_assets: Any = Field(default=None)
    unencumbered_ratio: Any = Field(default=None)


class CollateralAvailabilityAnalysisRequest(BaseModel):
    """Request parameters for collateral_availability_analysis()."""

    collateral_values: list[float] | list[list[float]]
    haircuts: list[float] | list[list[float]]
    already_pledged: list[float] | list[list[float]] | None = None


class CollateralAvailabilityAnalysisResponse(BaseModel):
    """Result of collateral_availability_analysis(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    available_collateral: Any = Field(default=None)
    post_haircut_values: Any = Field(default=None)


class RepoMarketStressHaircutRequest(BaseModel):
    """Request parameters for repo_market_stress_haircut()."""

    base_haircuts: list[float] | list[list[float]]
    stress_multipliers: list[float] | list[list[float]]
    collateral_values: list[float] | list[list[float]]


class RepoMarketStressHaircutResponse(BaseModel):
    """Result of repo_market_stress_haircut(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    additional_margin: Any = Field(default=None)
    margin_calls: Any = Field(default=None)
    stressed_haircuts: Any = Field(default=None)


class FxLiquidityRiskByCurrencyRequest(BaseModel):
    """Request parameters for fx_liquidity_risk_by_currency()."""

    inflows_by_ccy: dict[str, Any]
    outflows_by_ccy: dict[str, Any]


class FxLiquidityRiskByCurrencyResponse(BaseModel):
    """Result of fx_liquidity_risk_by_currency(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    largest_short_amount: Any = Field(default=None)
    largest_short_ccy: Any = Field(default=None)
    net_by_ccy: Any = Field(default=None)


class IntragroupLiquidityFlowRequest(BaseModel):
    """Request parameters for intragroup_liquidity_flow()."""

    entity_positions: dict[str, Any]


class IntragroupLiquidityFlowResponse(BaseModel):
    """Result of intragroup_liquidity_flow(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    balanced: Any = Field(default=None)
    net_providers: Any = Field(default=None)
    net_receivers: Any = Field(default=None)
    total_provided: Any = Field(default=None)


class FundingCostAnalysisRequest(BaseModel):
    """Request parameters for funding_cost_analysis()."""

    funding_amounts: list[float] | list[list[float]]
    funding_rates: list[float] | list[list[float]]


class FundingCostAnalysisResponse(BaseModel):
    """Result of funding_cost_analysis(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    total_annual_cost: Any = Field(default=None)
    total_funding: Any = Field(default=None)
    weighted_avg_cost: Any = Field(default=None)


class LiquidityTransferPricingRequest(BaseModel):
    """Request parameters for liquidity_transfer_pricing()."""

    notional: float
    tenor_years: float
    base_rate: float
    liquidity_spread: float
    contingent_spread: float = 0.0


class LiquidityTransferPricingResponse(BaseModel):
    """Result of liquidity_transfer_pricing(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    all_in_rate: Any = Field(default=None)
    annual_charge: Any = Field(default=None)
    lifetime_charge: Any = Field(default=None)


class IlaapInternalLiquidityMetricRequest(BaseModel):
    """Request parameters for ilaap_internal_liquidity_metric()."""

    counterbalancing_capacity: float
    stressed_net_outflow: float
    survival_days: float
    minimum_survival_days: float = 90.0


class IlaapInternalLiquidityMetricResponse(BaseModel):
    """Result of ilaap_internal_liquidity_metric(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    adequate: Any = Field(default=None)
    coverage_ratio: Any = Field(default=None)
    meets_survival: Any = Field(default=None)
    survival_days: Any = Field(default=None)


class LiquidityRiskAppetiteThresholdRequest(BaseModel):
    """Request parameters for liquidity_risk_appetite_threshold()."""

    metric_value: float
    green_threshold: float
    amber_threshold: float
    higher_is_better: bool = True


class LiquidityRiskAppetiteThresholdResponse(BaseModel):
    """Result of liquidity_risk_appetite_threshold(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    breach: Any = Field(default=None)
    zone: Any = Field(default=None)


class EarlyWarningIndicatorLiquidityRequest(BaseModel):
    """Request parameters for early_warning_indicator_liquidity()."""

    indicators: dict[str, Any]
    thresholds: dict[str, Any]
    directions: dict[str, Any] | None = None


class EarlyWarningIndicatorLiquidityResponse(BaseModel):
    """Result of early_warning_indicator_liquidity(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    num_triggered: Any = Field(default=None)
    signal: Any = Field(default=None)
    triggered: Any = Field(default=None)


class CentralBankFacilityEligibilityRequest(BaseModel):
    """Request parameters for central_bank_facility_eligibility()."""

    asset_ratings: list[float] | list[list[float]]
    min_rating: int
    asset_values: list[float] | list[list[float]]
    cb_haircuts: list[float] | list[list[float]]


class CentralBankFacilityEligibilityResponse(BaseModel):
    """Result of central_bank_facility_eligibility(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    borrowing_capacity: Any = Field(default=None)
    eligible_count: Any = Field(default=None)
    eligible_mask: Any = Field(default=None)


class ContingentLiquidityRiskRequest(BaseModel):
    """Request parameters for contingent_liquidity_risk()."""

    commitment_amounts: list[float] | list[list[float]]
    draw_probabilities: list[float] | list[list[float]]
    ccf: list[float] | list[list[float]] | None = None


class ContingentLiquidityRiskResponse(BaseModel):
    """Result of contingent_liquidity_risk(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    expected_contingent_outflow: Any = Field(default=None)
    max_contingent_outflow: Any = Field(default=None)


class LiquidityScorecardAggregationRequest(BaseModel):
    """Request parameters for liquidity_scorecard_aggregation()."""

    scores: list[float] | list[list[float]]
    weights: list[float] | list[list[float]]


class LiquidityScorecardAggregationResponse(BaseModel):
    """Result of liquidity_scorecard_aggregation(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    composite_score: Any = Field(default=None)
    rating: Any = Field(default=None)


class DepositStabilityClassificationRequest(BaseModel):
    """Request parameters for deposit_stability_classification()."""

    deposit_features: list[float] | list[list[float]]
    stable_threshold: float = 0.5


class DepositStabilityClassificationResponse(BaseModel):
    """Result of deposit_stability_classification(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    num_less_stable: Any = Field(default=None)
    num_stable: Any = Field(default=None)
    stable_fraction: Any = Field(default=None)


class CrossCurrencyLiquidityBridgeRequest(BaseModel):
    """Request parameters for cross_currency_liquidity_bridge()."""

    shortfall_ccy: str
    shortfall_amount: float
    surplus_ccy: str
    surplus_amount: float
    fx_rate: float
    swap_haircut: float = 0.0


class CrossCurrencyLiquidityBridgeResponse(BaseModel):
    """Result of cross_currency_liquidity_bridge(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    coverable_amount: Any = Field(default=None)
    fully_bridged: Any = Field(default=None)
    residual_shortfall: Any = Field(default=None)
    shortfall_ccy: Any = Field(default=None)
    surplus_ccy: Any = Field(default=None)
