"""schemas/market_risk.py — auto-generated Pydantic v2 contracts for the market-risk domain.

Generated by scripts/gen_p3.py from engine signatures. Request models are
precisely typed and enforce regulatory validators (CLAUDE.md s4). Response
models document engine return-dict keys; extra='allow' covers dynamically
built keys that static analysis cannot enumerate.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class HistoricalSimulationVarRequest(BaseModel):
    """Request parameters for historical_simulation_var()."""

    returns: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.99

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class HistoricalSimulationVarResponse(BaseModel):
    """Result of historical_simulation_var(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    cvar_abs: Any = Field(default=None)
    cvar_pct: Any = Field(default=None)
    n_obs: Any = Field(default=None)
    var_abs: Any = Field(default=None)
    var_pct: Any = Field(default=None)


class FilteredHistoricalSimulationVarRequest(BaseModel):
    """Request parameters for filtered_historical_simulation_var()."""

    returns: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.99
    lambda_decay: float = 0.94

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class FilteredHistoricalSimulationVarResponse(BaseModel):
    """Result of filtered_historical_simulation_var(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    cvar_abs: Any = Field(default=None)
    cvar_pct: Any = Field(default=None)
    sigma_forecast: Any = Field(default=None)
    var_abs: Any = Field(default=None)
    var_pct: Any = Field(default=None)


class ParametricDeltaNormalVarRequest(BaseModel):
    """Request parameters for parametric_delta_normal_var()."""

    weights: list[float] | list[list[float]]
    cov_matrix: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.99
    horizon_days: int = 1

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class ParametricDeltaNormalVarResponse(BaseModel):
    """Result of parametric_delta_normal_var(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    horizon_days: Any = Field(default=None)
    sigma_p: Any = Field(default=None)
    var_abs: Any = Field(default=None)
    var_pct: Any = Field(default=None)
    z_score: Any = Field(default=None)


class CornishFisherVarRequest(BaseModel):
    """Request parameters for cornish_fisher_var()."""

    returns: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.99
    skewness: float | None = None
    excess_kurtosis: float | None = None

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class CornishFisherVarResponse(BaseModel):
    """Result of cornish_fisher_var(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    excess_kurtosis: Any = Field(default=None)
    skewness: Any = Field(default=None)
    var_abs: Any = Field(default=None)
    var_pct: Any = Field(default=None)
    z_cf: Any = Field(default=None)


class MarginalVarRequest(BaseModel):
    """Request parameters for marginal_var()."""

    weights: list[float] | list[list[float]]
    cov_matrix: list[float] | list[list[float]]
    confidence_level: float = 0.99

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class MarginalVarResponse(BaseModel):
    """Result of marginal_var(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    marginal: Any = Field(default=None)
    sigma_p: Any = Field(default=None)
    var_pct: Any = Field(default=None)


class ComponentVarRequest(BaseModel):
    """Request parameters for component_var()."""

    weights: list[float] | list[list[float]]
    cov_matrix: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.99

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class ComponentVarResponse(BaseModel):
    """Result of component_var(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    component: Any = Field(default=None)
    component_abs: Any = Field(default=None)
    confidence_level: Any = Field(default=None)
    var_abs: Any = Field(default=None)
    var_pct: Any = Field(default=None)


class IncrementalVarRequest(BaseModel):
    """Request parameters for incremental_var()."""

    weights: list[float] | list[list[float]]
    cov_matrix: list[float] | list[list[float]]
    position_index: int
    portfolio_value: float
    confidence_level: float = 0.99

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class IncrementalVarResponse(BaseModel):
    """Result of incremental_var(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    incremental_abs: Any = Field(default=None)
    incremental_pct: Any = Field(default=None)
    position_index: Any = Field(default=None)
    var_full_pct: Any = Field(default=None)
    var_without_pct: Any = Field(default=None)


class VarByRiskFactorRequest(BaseModel):
    """Request parameters for var_by_risk_factor()."""

    factor_exposures: list[float] | list[list[float]]
    factor_cov: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.99
    factor_names: list[str] | None = None

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class VarByRiskFactorResponse(BaseModel):
    """Result of var_by_risk_factor(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    contributions: Any = Field(default=None)
    var_abs: Any = Field(default=None)
    var_pct: Any = Field(default=None)


class VarFanChartRequest(BaseModel):
    """Request parameters for var_fan_chart()."""

    returns: list[float] | list[list[float]]
    portfolio_value: float
    confidence_levels: list[float] = [0.9, 0.95, 0.99]
    horizon_days: int = 10

    @field_validator("confidence_levels")
    @classmethod
    def _confidence_levels_range(cls, v: list[float]) -> list[float]:
        for cl in v or []:
            if not (0.90 <= cl <= 0.9999):
                raise ValueError(f"confidence level {cl} outside regulatory range [0.90, 0.9999]")
        return v


class VarFanChartResponse(BaseModel):
    """Result of var_fan_chart(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    bands: Any = Field(default=None)
    bands_abs: Any = Field(default=None)
    horizons: Any = Field(default=None)


class ConditionalVarEsRequest(BaseModel):
    """Request parameters for conditional_var_es()."""

    returns: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.975

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class ConditionalVarEsResponse(BaseModel):
    """Result of conditional_var_es(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    es_abs: Any = Field(default=None)
    es_pct: Any = Field(default=None)
    var_abs: Any = Field(default=None)
    var_pct: Any = Field(default=None)


class HistoricalExpectedShortfallRequest(BaseModel):
    """Request parameters for historical_expected_shortfall()."""

    returns: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.975

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class HistoricalExpectedShortfallResponse(BaseModel):
    """Result of historical_expected_shortfall(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    es_abs: Any = Field(default=None)
    es_pct: Any = Field(default=None)
    n_tail: Any = Field(default=None)
    var_pct: Any = Field(default=None)


class MonteCarloExpectedShortfallRequest(BaseModel):
    """Request parameters for monte_carlo_expected_shortfall()."""

    returns: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.975
    n_simulations: int = 100000
    horizon_days: int = 1
    seed: int | None = 42

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class MonteCarloExpectedShortfallResponse(BaseModel):
    """Result of monte_carlo_expected_shortfall(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    es_abs: Any = Field(default=None)
    es_pct: Any = Field(default=None)
    n_simulations: Any = Field(default=None)
    var_abs: Any = Field(default=None)
    var_pct: Any = Field(default=None)


class CvarDecompositionEulerRequest(BaseModel):
    """Request parameters for cvar_decomposition_euler()."""

    weights: list[float] | list[list[float]]
    cov_matrix: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.975

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class CvarDecompositionEulerResponse(BaseModel):
    """Result of cvar_decomposition_euler(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    component: Any = Field(default=None)
    component_abs: Any = Field(default=None)
    confidence_level: Any = Field(default=None)
    es_abs: Any = Field(default=None)
    es_pct: Any = Field(default=None)


class StressedExpectedShortfallRequest(BaseModel):
    """Request parameters for stressed_expected_shortfall()."""

    returns: list[float] | list[list[float]]
    stress_start: int
    stress_end: int
    portfolio_value: float
    confidence_level: float = 0.975

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class StressedExpectedShortfallResponse(BaseModel):
    """Result of stressed_expected_shortfall(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    stressed_es_abs: Any = Field(default=None)
    stressed_es_pct: Any = Field(default=None)
    stressed_var_pct: Any = Field(default=None)
    window_size: Any = Field(default=None)


class LiquidityAdjustedEsRequest(BaseModel):
    """Request parameters for liquidity_adjusted_es()."""

    es_base: float
    partial_es: list[float]
    liquidity_horizons: list[float]
    base_horizon: float = 10.0


class LiquidityAdjustedEsResponse(BaseModel):
    """Result of liquidity_adjusted_es(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    es_base: Any = Field(default=None)
    liquidity_adjusted_es: Any = Field(default=None)
    scaling_factor: Any = Field(default=None)


class EsAtMultipleConfidenceLevelsRequest(BaseModel):
    """Request parameters for es_at_multiple_confidence_levels()."""

    returns: list[float] | list[list[float]]
    portfolio_value: float
    confidence_levels: list[float] = [0.95, 0.975, 0.99]

    @field_validator("confidence_levels")
    @classmethod
    def _confidence_levels_range(cls, v: list[float]) -> list[float]:
        for cl in v or []:
            if not (0.90 <= cl <= 0.9999):
                raise ValueError(f"confidence level {cl} outside regulatory range [0.90, 0.9999]")
        return v


class EsAtMultipleConfidenceLevelsResponse(BaseModel):
    """Result of es_at_multiple_confidence_levels(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    es: Any = Field(default=None)
    es_abs: Any = Field(default=None)


class ExpectedShortfallContributionRequest(BaseModel):
    """Request parameters for expected_shortfall_contribution()."""

    asset_returns: list[float] | list[list[float]]
    weights: list[float] | list[list[float]]
    portfolio_value: float
    confidence_level: float = 0.975

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class ExpectedShortfallContributionResponse(BaseModel):
    """Result of expected_shortfall_contribution(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    contribution: Any = Field(default=None)
    contribution_abs: Any = Field(default=None)
    es_pct: Any = Field(default=None)
    n_tail: Any = Field(default=None)


class HistoricalScenarioReplayRequest(BaseModel):
    """Request parameters for historical_scenario_replay()."""

    exposures: list[float] | list[list[float]]
    historical_factor_returns: list[float] | list[list[float]]


class HistoricalScenarioReplayResponse(BaseModel):
    """Result of historical_scenario_replay(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    best_gain: Any = Field(default=None)
    mean_pnl: Any = Field(default=None)
    pnl_path: Any = Field(default=None)
    worst_loss: Any = Field(default=None)
    worst_scenario_index: Any = Field(default=None)


class HypotheticalMultiFactorScenarioRequest(BaseModel):
    """Request parameters for hypothetical_multi_factor_scenario()."""

    exposures: list[float] | list[list[float]]
    shocks: list[float] | list[list[float]]


class HypotheticalMultiFactorScenarioResponse(BaseModel):
    """Result of hypothetical_multi_factor_scenario(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    factor_pnl: Any = Field(default=None)
    pnl: Any = Field(default=None)


class ReverseStressTestingRequest(BaseModel):
    """Request parameters for reverse_stress_testing()."""

    exposures: list[float] | list[list[float]]
    factor_cov: list[float] | list[list[float]]
    target_loss: float


class ReverseStressTestingResponse(BaseModel):
    """Result of reverse_stress_testing(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    achieved_loss: Any = Field(default=None)
    magnitude: Any = Field(default=None)
    shock: Any = Field(default=None)
    target_loss: Any = Field(default=None)


class SensitivityStressProfileRequest(BaseModel):
    """Request parameters for sensitivity_stress_profile()."""

    exposures: list[float] | list[list[float]]
    factor_index: int
    shock_grid: list[float] | list[list[float]]


class SensitivityStressProfileResponse(BaseModel):
    """Result of sensitivity_stress_profile(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    factor_index: Any = Field(default=None)
    pnl_profile: Any = Field(default=None)
    shock_grid: Any = Field(default=None)


class SectorStressScenarioRequest(BaseModel):
    """Request parameters for sector_stress_scenario()."""

    sector_exposures: list[float] | list[list[float]]
    sector_shocks: list[float] | list[list[float]]
    sector_names: list[str] | None = None


class SectorStressScenarioResponse(BaseModel):
    """Result of sector_stress_scenario(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    sector_pnl: Any = Field(default=None)
    total_pnl: Any = Field(default=None)


class MacroScenarioGeneratorRequest(BaseModel):
    """Request parameters for macro_scenario_generator()."""

    factor_cov: list[float] | list[list[float]]
    n_scenarios: int = 10000
    seed: int | None = 42


class MacroScenarioGeneratorResponse(BaseModel):
    """Result of macro_scenario_generator(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    n_scenarios: Any = Field(default=None)
    sample_cov: Any = Field(default=None)
    scenarios: Any = Field(default=None)


class ContagionStressScenarioRequest(BaseModel):
    """Request parameters for contagion_stress_scenario()."""

    initial_shock: list[float] | list[list[float]]
    contagion_matrix: list[float] | list[list[float]]
    rounds: int = 3


class ContagionStressScenarioResponse(BaseModel):
    """Result of contagion_stress_scenario(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    amplification_factor: Any = Field(default=None)
    amplified_shock: Any = Field(default=None)
    rounds: Any = Field(default=None)


class PortfolioDeltaAggregatedRequest(BaseModel):
    """Request parameters for portfolio_delta_aggregated()."""

    deltas: list[float] | list[list[float]]
    quantities: list[float] | list[list[float]]
    spot_prices: list[float] | list[list[float]] | None = None


class PortfolioDeltaAggregatedResponse(BaseModel):
    """Result of portfolio_delta_aggregated(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    result: Any = Field(default=None)


class GammaCrossGammaMatrixRequest(BaseModel):
    """Request parameters for gamma_cross_gamma_matrix()."""

    own_gammas: list[float] | list[list[float]]
    cross_gammas: list[float] | list[list[float]] | None = None


class GammaCrossGammaMatrixResponse(BaseModel):
    """Result of gamma_cross_gamma_matrix(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    gamma_matrix: Any = Field(default=None)
    is_symmetric: Any = Field(default=None)


class VegaSurfaceBucketedRequest(BaseModel):
    """Request parameters for vega_surface_bucketed()."""

    vegas: list[float] | list[list[float]]
    expiry_buckets: list[float] | list[list[float]]
    strike_buckets: list[float] | list[list[float]]
    n_expiry: int
    n_strike: int


class VegaSurfaceBucketedResponse(BaseModel):
    """Result of vega_surface_bucketed(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    surface: Any = Field(default=None)
    total_vega: Any = Field(default=None)


class Dv01Pv01BucketedRequest(BaseModel):
    """Request parameters for dv01_pv01_bucketed()."""

    cashflows: list[float] | list[list[float]]
    times: list[float] | list[list[float]]
    flat_yield: float
    bucket_indices: list[float] | list[list[float]]
    n_buckets: int


class Dv01Pv01BucketedResponse(BaseModel):
    """Result of dv01_pv01_bucketed(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    dv01_buckets: Any = Field(default=None)
    pv: Any = Field(default=None)
    total_dv01: Any = Field(default=None)
    total_pv01: Any = Field(default=None)


class Cs01CreditSpreadRequest(BaseModel):
    """Request parameters for cs01_credit_spread()."""

    cashflows: list[float] | list[list[float]]
    times: list[float] | list[list[float]]
    risk_free_rate: float
    credit_spread: float


class Cs01CreditSpreadResponse(BaseModel):
    """Result of cs01_credit_spread(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    cs01: Any = Field(default=None)
    pv: Any = Field(default=None)


class RhoInterestRateRequest(BaseModel):
    """Request parameters for rho_interest_rate()."""

    spot: float
    strike: float
    rate: float
    sigma: float
    tau: float
    option_type: str = "call"
    div_yield: float = 0.0


class RhoInterestRateResponse(BaseModel):
    """Result of rho_interest_rate(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    d2: Any = Field(default=None)
    rho: Any = Field(default=None)


class ThetaTimeDecayRequest(BaseModel):
    """Request parameters for theta_time_decay()."""

    spot: float
    strike: float
    rate: float
    sigma: float
    tau: float
    option_type: str = "call"
    div_yield: float = 0.0


class ThetaTimeDecayResponse(BaseModel):
    """Result of theta_time_decay(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    theta: Any = Field(default=None)
    theta_per_day: Any = Field(default=None)


class CharmDeltaDecayRequest(BaseModel):
    """Request parameters for charm_delta_decay()."""

    spot: float
    strike: float
    rate: float
    sigma: float
    tau: float
    option_type: str = "call"
    div_yield: float = 0.0


class CharmDeltaDecayResponse(BaseModel):
    """Result of charm_delta_decay(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    charm: Any = Field(default=None)


class VolgaVegaConvexityRequest(BaseModel):
    """Request parameters for volga_vega_convexity()."""

    spot: float
    strike: float
    rate: float
    sigma: float
    tau: float
    div_yield: float = 0.0


class VolgaVegaConvexityResponse(BaseModel):
    """Result of volga_vega_convexity(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    vega: Any = Field(default=None)
    volga: Any = Field(default=None)


class VannaDeltaVegaCrossRequest(BaseModel):
    """Request parameters for vanna_delta_vega_cross()."""

    spot: float
    strike: float
    rate: float
    sigma: float
    tau: float
    div_yield: float = 0.0


class VannaDeltaVegaCrossResponse(BaseModel):
    """Result of vanna_delta_vega_cross(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    vanna: Any = Field(default=None)


class GreeksBasedPnlExplainRequest(BaseModel):
    """Request parameters for greeks_based_pnl_explain()."""

    delta: float
    gamma: float
    vega: float
    theta: float
    rho: float
    spot_move: float
    vol_move: float
    time_step: float
    rate_move: float
    actual_pnl: float


class GreeksBasedPnlExplainResponse(BaseModel):
    """Result of greeks_based_pnl_explain(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    actual_pnl: Any = Field(default=None)
    components: Any = Field(default=None)
    predicted_pnl: Any = Field(default=None)
    unexplained: Any = Field(default=None)


class PnlAttributionTestFrtbPatRequest(BaseModel):
    """Request parameters for pnl_attribution_test_frtb_pat()."""

    risk_theoretical_pnl: list[float] | list[list[float]]
    hypothetical_pnl: list[float] | list[list[float]]


class PnlAttributionTestFrtbPatResponse(BaseModel):
    """Result of pnl_attribution_test_frtb_pat(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    ratio: Any = Field(default=None)
    spearman_corr: Any = Field(default=None)
    zone: Any = Field(default=None)


class ThetaCarryAttributionRequest(BaseModel):
    """Request parameters for theta_carry_attribution()."""

    theta: float
    time_step: float
    funding_cost: float = 0.0


class ThetaCarryAttributionResponse(BaseModel):
    """Result of theta_carry_attribution(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    carry_pnl: Any = Field(default=None)
    funding_cost: Any = Field(default=None)
    theta_pnl: Any = Field(default=None)


class GammaPnlAttributionRequest(BaseModel):
    """Request parameters for gamma_pnl_attribution()."""

    gamma: float
    spot_move: float


class GammaPnlAttributionResponse(BaseModel):
    """Result of gamma_pnl_attribution(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    gamma_pnl: Any = Field(default=None)


class VegaPnlAttributionRequest(BaseModel):
    """Request parameters for vega_pnl_attribution()."""

    vega: float
    vol_move: float


class VegaPnlAttributionResponse(BaseModel):
    """Result of vega_pnl_attribution(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    vega_pnl: Any = Field(default=None)


class FxPnlAttributionRequest(BaseModel):
    """Request parameters for fx_pnl_attribution()."""

    fx_deltas: list[float] | list[list[float]]
    fx_moves: list[float] | list[list[float]]
    currency_names: list[str] | None = None


class FxPnlAttributionResponse(BaseModel):
    """Result of fx_pnl_attribution(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    fx_pnl: Any = Field(default=None)
    total_fx_pnl: Any = Field(default=None)


class RatesPnlAttributionRequest(BaseModel):
    """Request parameters for rates_pnl_attribution()."""

    key_rate_sensitivities: list[float] | list[list[float]]
    yield_moves_bp: list[float] | list[list[float]]
    tenor_names: list[str] | None = None


class RatesPnlAttributionResponse(BaseModel):
    """Result of rates_pnl_attribution(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    rates_pnl: Any = Field(default=None)
    total_rates_pnl: Any = Field(default=None)


class CreditPnlAttributionRequest(BaseModel):
    """Request parameters for credit_pnl_attribution()."""

    cs01_sensitivities: list[float] | list[list[float]]
    spread_moves_bp: list[float] | list[list[float]]
    name_labels: list[str] | None = None


class CreditPnlAttributionResponse(BaseModel):
    """Result of credit_pnl_attribution(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    credit_pnl: Any = Field(default=None)
    total_credit_pnl: Any = Field(default=None)


class ResidualPnlUnexplainedRequest(BaseModel):
    """Request parameters for residual_pnl_unexplained()."""

    actual_pnl: float
    explained_components: list[float] | list[list[float]]


class ResidualPnlUnexplainedResponse(BaseModel):
    """Result of residual_pnl_unexplained(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    explained_pnl: Any = Field(default=None)
    explained_ratio: Any = Field(default=None)
    residual_pnl: Any = Field(default=None)


class TrafficLightBacktestingRequest(BaseModel):
    """Request parameters for traffic_light_backtesting()."""

    actual_returns: list[float] | list[list[float]]
    var_estimates: list[float] | list[list[float]]


class TrafficLightBacktestingResponse(BaseModel):
    """Result of traffic_light_backtesting(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    basel_zone: Any = Field(default=None)
    expected_window: Any = Field(default=None)
    n_breaches: Any = Field(default=None)
    n_observations: Any = Field(default=None)


class KupiecPofTestRequest(BaseModel):
    """Request parameters for kupiec_pof_test()."""

    n_breaches: int
    n_observations: int
    confidence_level: float = 0.99

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class KupiecPofTestResponse(BaseModel):
    """Result of kupiec_pof_test(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    critical_value: Any = Field(default=None)
    lr_pof: Any = Field(default=None)
    p_value: Any = Field(default=None)
    reject: Any = Field(default=None)


class ChristoffersenIndependenceTestRequest(BaseModel):
    """Request parameters for christoffersen_independence_test()."""

    breaches: list[float] | list[list[float]]


class ChristoffersenIndependenceTestResponse(BaseModel):
    """Result of christoffersen_independence_test(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    critical_value: Any = Field(default=None)
    lr_ind: Any = Field(default=None)
    p_value: Any = Field(default=None)
    reject: Any = Field(default=None)


class CombinedBacktestingRequest(BaseModel):
    """Request parameters for combined_backtesting()."""

    breaches: list[float] | list[list[float]]
    confidence_level: float = 0.99

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class CombinedBacktestingResponse(BaseModel):
    """Result of combined_backtesting(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    critical_value: Any = Field(default=None)
    lr_cc: Any = Field(default=None)
    lr_ind: Any = Field(default=None)
    lr_pof: Any = Field(default=None)
    reject: Any = Field(default=None)


class BaselCapitalAddonMultiplierRequest(BaseModel):
    """Request parameters for basel_capital_addon_multiplier()."""

    n_breaches: int


class BaselCapitalAddonMultiplierResponse(BaseModel):
    """Result of basel_capital_addon_multiplier(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    multiplier: Any = Field(default=None)
    n_breaches: Any = Field(default=None)
    zone: Any = Field(default=None)


class RollingVarBacktestRequest(BaseModel):
    """Request parameters for rolling_var_backtest()."""

    returns: list[float] | list[list[float]]
    window: int = 250
    confidence_level: float = 0.99

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class RollingVarBacktestResponse(BaseModel):
    """Result of rolling_var_backtest(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    basel_zone: Any = Field(default=None)
    breach_rate_pct: Any = Field(default=None)
    n_breaches: Any = Field(default=None)
    n_observations: Any = Field(default=None)
    window: Any = Field(default=None)


class VarBreachClusterAnalysisRequest(BaseModel):
    """Request parameters for var_breach_cluster_analysis()."""

    breaches: list[float] | list[list[float]]


class VarBreachClusterAnalysisResponse(BaseModel):
    """Result of var_breach_cluster_analysis(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    max_cluster_length: Any = Field(default=None)
    mean_cluster_length: Any = Field(default=None)
    n_breaches: Any = Field(default=None)
    n_clusters: Any = Field(default=None)


class VolatilitySurfaceImpliedVolRequest(BaseModel):
    """Request parameters for volatility_surface_implied_vol()."""

    market_prices: list[float] | list[list[float]]
    strikes: list[float] | list[list[float]]
    expiries: list[float] | list[list[float]]
    spot: float
    rate: float
    option_type: str = "call"


class VolatilitySurfaceImpliedVolResponse(BaseModel):
    """Result of volatility_surface_implied_vol(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    implied_vols: Any = Field(default=None)
    points: Any = Field(default=None)


class Garch11VolatilityForecastRequest(BaseModel):
    """Request parameters for garch_11_volatility_forecast()."""

    returns: list[float] | list[list[float]]
    alpha: float = 0.1
    beta: float = 0.85
    omega: float | None = None
    horizon: int = 10


class Garch11VolatilityForecastResponse(BaseModel):
    """Result of garch_11_volatility_forecast(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    current_vol: Any = Field(default=None)
    forecast_vol_path: Any = Field(default=None)
    long_run_vol: Any = Field(default=None)
    persistence: Any = Field(default=None)


class EgarchVolatilityModelRequest(BaseModel):
    """Request parameters for egarch_volatility_model()."""

    returns: list[float] | list[list[float]]
    omega: float = -0.1
    alpha: float = 0.1
    gamma: float = -0.05
    beta: float = 0.95


class EgarchVolatilityModelResponse(BaseModel):
    """Result of egarch_volatility_model(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    current_vol: Any = Field(default=None)
    forecast_vol: Any = Field(default=None)


class GjrGarchAsymmetricModelRequest(BaseModel):
    """Request parameters for gjr_garch_asymmetric_model()."""

    returns: list[float] | list[list[float]]
    alpha: float = 0.03
    gamma: float = 0.08
    beta: float = 0.88
    omega: float | None = None


class GjrGarchAsymmetricModelResponse(BaseModel):
    """Result of gjr_garch_asymmetric_model(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    current_vol: Any = Field(default=None)
    forecast_vol: Any = Field(default=None)
    long_run_vol: Any = Field(default=None)
    persistence: Any = Field(default=None)


class RealisedVolatilityRequest(BaseModel):
    """Request parameters for realised_volatility()."""

    returns: list[float] | list[list[float]]
    annualisation_factor: int = 252


class RealisedVolatilityResponse(BaseModel):
    """Result of realised_volatility(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    annualised_vol: Any = Field(default=None)
    realised_variance: Any = Field(default=None)
    realised_vol: Any = Field(default=None)


class CorrelationMatrixHistoricalRequest(BaseModel):
    """Request parameters for correlation_matrix_historical()."""

    returns_matrix: list[float] | list[list[float]]


class CorrelationMatrixHistoricalResponse(BaseModel):
    """Result of correlation_matrix_historical(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    correlation: Any = Field(default=None)
    is_symmetric: Any = Field(default=None)
    n_assets: Any = Field(default=None)


class DccGarchDynamicCorrelationRequest(BaseModel):
    """Request parameters for dcc_garch_dynamic_correlation()."""

    returns_matrix: list[float] | list[list[float]]
    a: float = 0.02
    b: float = 0.95


class DccGarchDynamicCorrelationResponse(BaseModel):
    """Result of dcc_garch_dynamic_correlation(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    a: Any = Field(default=None)
    b: Any = Field(default=None)
    dynamic_correlation: Any = Field(default=None)


class RiskFactorPcaDecompositionRequest(BaseModel):
    """Request parameters for risk_factor_pca_decomposition()."""

    returns_matrix: list[float] | list[list[float]]
    n_components: int | None = None


class RiskFactorPcaDecompositionResponse(BaseModel):
    """Result of risk_factor_pca_decomposition(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    cumulative_variance_ratio: Any = Field(default=None)
    eigenvalues: Any = Field(default=None)
    explained_variance_ratio: Any = Field(default=None)
    loadings: Any = Field(default=None)


class FrtbSaSensitivityBasedMethodRequest(BaseModel):
    """Request parameters for frtb_sa_sensitivity_based_method()."""

    bucket_weighted_sensitivities: list[list[float]]
    intra_bucket_corr: float
    inter_bucket_corr: float


class FrtbSaSensitivityBasedMethodResponse(BaseModel):
    """Result of frtb_sa_sensitivity_based_method(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    kb: Any = Field(default=None)
    risk_charge: Any = Field(default=None)
    sb: Any = Field(default=None)


class FrtbSaDefaultRiskChargeRequest(BaseModel):
    """Request parameters for frtb_sa_default_risk_charge()."""

    jtd_long: list[float] | list[list[float]]
    jtd_short: list[float] | list[list[float]]
    risk_weights: list[float] | list[list[float]]


class FrtbSaDefaultRiskChargeResponse(BaseModel):
    """Result of frtb_sa_default_risk_charge(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    drc: Any = Field(default=None)
    gross_long: Any = Field(default=None)
    gross_short: Any = Field(default=None)
    wts_ratio: Any = Field(default=None)


class FrtbSaResidualRiskAddonRequest(BaseModel):
    """Request parameters for frtb_sa_residual_risk_addon()."""

    notionals: list[float] | list[list[float]]
    rrao_weights: list[float] | list[list[float]]


class FrtbSaResidualRiskAddonResponse(BaseModel):
    """Result of frtb_sa_residual_risk_addon(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    addon: Any = Field(default=None)
    rrao: Any = Field(default=None)


class FrtbImaExpectedShortfallRequest(BaseModel):
    """Request parameters for frtb_ima_expected_shortfall()."""

    returns: list[float] | list[list[float]]
    confidence_level: float = 0.975

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class FrtbImaExpectedShortfallResponse(BaseModel):
    """Result of frtb_ima_expected_shortfall(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    es: Any = Field(default=None)
    var: Any = Field(default=None)


class FrtbImaStressedPeriodFinderRequest(BaseModel):
    """Request parameters for frtb_ima_stressed_period_finder()."""

    returns: list[float] | list[list[float]]
    window: int = 250
    confidence_level: float = 0.975

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class FrtbImaStressedPeriodFinderResponse(BaseModel):
    """Result of frtb_ima_stressed_period_finder(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    n_windows: Any = Field(default=None)
    stressed_es: Any = Field(default=None)
    stressed_window_start: Any = Field(default=None)


class FrtbImaNonModellableRiskFactorsRequest(BaseModel):
    """Request parameters for frtb_ima_non_modellable_risk_factors()."""

    individual_ses: list[float] | list[list[float]]
    rho: float = 0.0


class FrtbImaNonModellableRiskFactorsResponse(BaseModel):
    """Result of frtb_ima_non_modellable_risk_factors(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    n_factors: Any = Field(default=None)
    ses: Any = Field(default=None)


class FrtbImaAggregateCapitalChargeRequest(BaseModel):
    """Request parameters for frtb_ima_aggregate_capital_charge()."""

    imcc: float
    ses: float
    default_risk_charge: float = 0.0


class FrtbImaAggregateCapitalChargeResponse(BaseModel):
    """Result of frtb_ima_aggregate_capital_charge(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    aggregate_capital_charge: Any = Field(default=None)
    drc: Any = Field(default=None)
    imcc: Any = Field(default=None)
    ses: Any = Field(default=None)


class ExtremeValueTheoryVarRequest(BaseModel):
    """Request parameters for extreme_value_theory_var()."""

    returns: list[float] | list[list[float]]
    threshold_quantile: float = 0.95
    confidence_level: float = 0.99

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class ExtremeValueTheoryVarResponse(BaseModel):
    """Result of extreme_value_theory_var(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    beta: Any = Field(default=None)
    evt_var: Any = Field(default=None)
    n_exceedances: Any = Field(default=None)
    threshold: Any = Field(default=None)
    xi: Any = Field(default=None)


class SpectralRiskMeasureRequest(BaseModel):
    """Request parameters for spectral_risk_measure()."""

    returns: list[float] | list[list[float]]
    risk_aversion: float = 25.0


class SpectralRiskMeasureResponse(BaseModel):
    """Result of spectral_risk_measure(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    mean_loss: Any = Field(default=None)
    risk_aversion: Any = Field(default=None)
    spectral_risk: Any = Field(default=None)


class ComputeCvarRequest(BaseModel):
    """Request parameters for compute_cvar()."""

    sorted_losses: list[float] | list[list[float]]
    confidence_level: float

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class ComputeCvarResponse(BaseModel):
    """Result of compute_cvar(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    result: Any = Field(default=None)


class ComputeLossPercentilesRequest(BaseModel):
    """Request parameters for compute_loss_percentiles()."""

    sorted_losses: list[float] | list[list[float]]
    percentiles: list[float] | None = None


class ComputeLossPercentilesResponse(BaseModel):
    """Result of compute_loss_percentiles(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    result: Any = Field(default=None)


class ComputeRollingVarRequest(BaseModel):
    """Request parameters for compute_rolling_var()."""

    returns: list[float] | list[list[float]]
    window: int = 250
    confidence_level: float = 0.99

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class ComputeRollingVarResponse(BaseModel):
    """Result of compute_rolling_var(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    result: Any = Field(default=None)


class ComputeBreachesRequest(BaseModel):
    """Request parameters for compute_breaches()."""

    actual_returns: list[float] | list[list[float]]
    var_estimates: list[float] | list[list[float]]


class ComputeBreachesResponse(BaseModel):
    """Result of compute_breaches(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    basel_zone: Any = Field(default=None)
    breach_rate_pct: Any = Field(default=None)
    n_breaches: Any = Field(default=None)
    n_observations: Any = Field(default=None)
