"""schemas/operational.py — auto-generated Pydantic v2 contracts for the operational domain.

Generated by scripts/gen_p3.py from engine signatures. Request models are
precisely typed and enforce regulatory validators (CLAUDE.md s4). Response
models document engine return-dict keys; extra='allow' covers dynamically
built keys that static analysis cannot enumerate.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field, field_validator


class FrequencyDistributionFittingRequest(BaseModel):
    """Request parameters for frequency_distribution_fitting()."""

    annual_event_counts: list[float] | list[list[float]]


class FrequencyDistributionFittingResponse(BaseModel):
    """Result of frequency_distribution_fitting(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    dispersion: Any = Field(default=None)
    distribution: Any = Field(default=None)
    f_lambda: Any = Field(default=None, alias="lambda")


class SeverityDistributionFittingRequest(BaseModel):
    """Request parameters for severity_distribution_fitting()."""

    loss_amounts: list[float] | list[list[float]]
    distribution: str = "lognormal"


class SeverityDistributionFittingResponse(BaseModel):
    """Result of severity_distribution_fitting(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    distribution: Any = Field(default=None)
    mean_severity: Any = Field(default=None)
    mu: Any = Field(default=None)
    sigma: Any = Field(default=None)


class CompoundLossDistributionRequest(BaseModel):
    """Request parameters for compound_loss_distribution()."""

    frequency_lambda: float
    severity_mu: float
    severity_sigma: float
    n_years: int = 50000
    seed: int | None = 42


class CompoundLossDistributionResponse(BaseModel):
    """Result of compound_loss_distribution(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    annual_losses: Any = Field(default=None)
    mean_annual_loss: Any = Field(default=None)
    n_years: Any = Field(default=None)
    std_annual_loss: Any = Field(default=None)


class MonteCarloOpriskCapitalRequest(BaseModel):
    """Request parameters for monte_carlo_oprisk_capital()."""

    frequency_lambda: float
    severity_mu: float
    severity_sigma: float
    confidence_level: float = 0.999
    n_years: int = 100000
    seed: int | None = 42

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class MonteCarloOpriskCapitalResponse(BaseModel):
    """Result of monte_carlo_oprisk_capital(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    capital: Any = Field(default=None)
    confidence_level: Any = Field(default=None)
    expected_loss: Any = Field(default=None)
    expected_shortfall: Any = Field(default=None)
    n_years: Any = Field(default=None)
    opvar: Any = Field(default=None)


class OperationalVarOpvarRequest(BaseModel):
    """Request parameters for operational_var_opvar()."""

    annual_losses: list[float] | list[list[float]]
    confidence_level: float = 0.999

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class OperationalVarOpvarResponse(BaseModel):
    """Result of operational_var_opvar(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    expected_loss: Any = Field(default=None)
    expected_shortfall: Any = Field(default=None)
    opvar: Any = Field(default=None)


class LossDistributionApproachLdaRequest(BaseModel):
    """Request parameters for loss_distribution_approach_lda()."""

    annual_event_counts: list[float] | list[list[float]]
    loss_amounts: list[float] | list[list[float]]
    confidence_level: float = 0.999
    n_years: int = 100000
    seed: int | None = 42

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class LossDistributionApproachLdaResponse(BaseModel):
    """Result of loss_distribution_approach_lda(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    capital: Any = Field(default=None)
    confidence_level: Any = Field(default=None)
    expected_loss: Any = Field(default=None)
    frequency: Any = Field(default=None)
    opvar: Any = Field(default=None)
    severity: Any = Field(default=None)


class AdvancedMeasurementApproachAmaRequest(BaseModel):
    """Request parameters for advanced_measurement_approach_ama()."""

    annual_event_counts: list[float] | list[list[float]]
    loss_amounts: list[float] | list[list[float]]
    expected_loss_covered: bool = True
    confidence_level: float = 0.999
    n_years: int = 100000
    seed: int | None = 42

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class AdvancedMeasurementApproachAmaResponse(BaseModel):
    """Result of advanced_measurement_approach_ama(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    ama_capital: Any = Field(default=None)
    confidence_level: Any = Field(default=None)
    el_covered: Any = Field(default=None)
    expected_loss: Any = Field(default=None)
    opvar: Any = Field(default=None)


class BaselStandardisedMeasurementSmaRequest(BaseModel):
    """Request parameters for basel_standardised_measurement_sma()."""

    business_indicator: float
    loss_component: float = 0.0
    use_ilm: bool = True


class BaselStandardisedMeasurementSmaResponse(BaseModel):
    """Result of basel_standardised_measurement_sma(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    bic: Any = Field(default=None)
    ilm: Any = Field(default=None)
    sma_capital: Any = Field(default=None)


class OpriskCapitalAllocationRequest(BaseModel):
    """Request parameters for oprisk_capital_allocation()."""

    total_capital: float
    business_line_risks: list[float] | list[list[float]]


class OpriskCapitalAllocationResponse(BaseModel):
    """Result of oprisk_capital_allocation(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    allocations: Any = Field(default=None)
    shares: Any = Field(default=None)


class DiversificationBenefitOpriskRequest(BaseModel):
    """Request parameters for diversification_benefit_oprisk()."""

    standalone_capitals: list[float] | list[list[float]]
    correlation: float = 0.0


class DiversificationBenefitOpriskResponse(BaseModel):
    """Result of diversification_benefit_oprisk(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    diversification_benefit: Any = Field(default=None)
    diversified_capital: Any = Field(default=None)
    sum_standalone: Any = Field(default=None)


class OpriskEconomicCapitalRequest(BaseModel):
    """Request parameters for oprisk_economic_capital()."""

    opvar: float
    expected_loss: float
    insurance_offset: float = 0.0
    diversification_benefit: float = 0.0


class OpriskEconomicCapitalResponse(BaseModel):
    """Result of oprisk_economic_capital(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    economic_capital: Any = Field(default=None)
    gross_capital: Any = Field(default=None)
    total_mitigation: Any = Field(default=None)


class InsuranceOffsetCalculationRequest(BaseModel):
    """Request parameters for insurance_offset_calculation()."""

    gross_loss: float
    policy_limit: float
    deductible: float
    haircut: float = 0.0


class InsuranceOffsetCalculationResponse(BaseModel):
    """Result of insurance_offset_calculation(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    net_loss: Any = Field(default=None)
    recoverable: Any = Field(default=None)
    recovery_rate: Any = Field(default=None)


class TailRiskScenarioOpriskRequest(BaseModel):
    """Request parameters for tail_risk_scenario_oprisk()."""

    annual_losses: list[float] | list[list[float]]
    tail_confidence: float = 0.999
    severity_multiplier: float = 1.0


class TailRiskScenarioOpriskResponse(BaseModel):
    """Result of tail_risk_scenario_oprisk(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    base_tail_es: Any = Field(default=None)
    capital_uplift: Any = Field(default=None)
    stressed_tail_es: Any = Field(default=None)


class OpriskStressTestingRequest(BaseModel):
    """Request parameters for oprisk_stress_testing()."""

    base_capital: float
    frequency_shock: float
    severity_shock: float


class OpriskStressTestingResponse(BaseModel):
    """Result of oprisk_stress_testing(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    capital_increase: Any = Field(default=None)
    stressed_capital: Any = Field(default=None)


class RcsaRiskIdentificationRequest(BaseModel):
    """Request parameters for rcsa_risk_identification()."""

    risk_register: list[dict[str, Any]]


class RcsaRiskIdentificationResponse(BaseModel):
    """Result of rcsa_risk_identification(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    by_category: Any = Field(default=None)
    num_risks: Any = Field(default=None)


class RcsaInherentRiskScoringRequest(BaseModel):
    """Request parameters for rcsa_inherent_risk_scoring()."""

    likelihood: int
    impact: int


class RcsaInherentRiskScoringResponse(BaseModel):
    """Result of rcsa_inherent_risk_scoring(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    inherent_score: Any = Field(default=None)
    rating: Any = Field(default=None)


class RcsaResidualRiskScoringRequest(BaseModel):
    """Request parameters for rcsa_residual_risk_scoring()."""

    inherent_score: float
    control_effectiveness: float


class RcsaResidualRiskScoringResponse(BaseModel):
    """Result of rcsa_residual_risk_scoring(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    rating: Any = Field(default=None)
    residual_score: Any = Field(default=None)


class RcsaControlEffectivenessRequest(BaseModel):
    """Request parameters for rcsa_control_effectiveness()."""

    design_score: float
    operating_score: float
    design_weight: float = 0.4


class RcsaControlEffectivenessResponse(BaseModel):
    """Result of rcsa_control_effectiveness(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    effectiveness: Any = Field(default=None)
    rating: Any = Field(default=None)


class ControlTestingEffectivenessRequest(BaseModel):
    """Request parameters for control_testing_effectiveness()."""

    tests_passed: int
    tests_total: int


class ControlTestingEffectivenessResponse(BaseModel):
    """Result of control_testing_effectiveness(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    conclusion: Any = Field(default=None)
    exception_rate: Any = Field(default=None)
    pass_rate: Any = Field(default=None)


class BusinessEnvironmentFactorBeiRequest(BaseModel):
    """Request parameters for business_environment_factor_bei()."""

    factor_scores: list[float] | list[list[float]]
    baseline: float = 3.0
    sensitivity: float = 0.05


class BusinessEnvironmentFactorBeiResponse(BaseModel):
    """Result of business_environment_factor_bei(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    avg_score: Any = Field(default=None)
    bei_multiplier: Any = Field(default=None)
    capital_impact: Any = Field(default=None)


class InternalControlFactorIcfRequest(BaseModel):
    """Request parameters for internal_control_factor_icf()."""

    control_scores: list[float] | list[list[float]]
    baseline: float = 0.8
    sensitivity: float = 0.25


class InternalControlFactorIcfResponse(BaseModel):
    """Result of internal_control_factor_icf(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    avg_effectiveness: Any = Field(default=None)
    capital_impact: Any = Field(default=None)
    icf_multiplier: Any = Field(default=None)


class LossEventClassificationBaselRequest(BaseModel):
    """Request parameters for loss_event_classification_basel()."""

    event_type: str


class LossEventClassificationBaselResponse(BaseModel):
    """Result of loss_event_classification_basel(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    category_index: Any = Field(default=None)
    event_type: Any = Field(default=None)
    valid: Any = Field(default=None)


class LossDataCollectionFrameworkRequest(BaseModel):
    """Request parameters for loss_data_collection_framework()."""

    loss_events: list[dict[str, Any]]
    reporting_threshold: float


class LossDataCollectionFrameworkResponse(BaseModel):
    """Result of loss_data_collection_framework(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    below_threshold_count: Any = Field(default=None)
    max_loss: Any = Field(default=None)
    reportable_count: Any = Field(default=None)
    total_loss: Any = Field(default=None)


class ExternalLossDataIntegrationRequest(BaseModel):
    """Request parameters for external_loss_data_integration()."""

    internal_losses: list[float] | list[list[float]]
    external_losses: list[float] | list[list[float]]
    scaling_factor: float


class ExternalLossDataIntegrationResponse(BaseModel):
    """Result of external_loss_data_integration(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    combined_count: Any = Field(default=None)
    combined_mean: Any = Field(default=None)
    external_weight: Any = Field(default=None)


class KeyRiskIndicatorKriLibraryRequest(BaseModel):
    """Request parameters for key_risk_indicator_kri_library()."""

    kri_definitions: list[dict[str, Any]]


class KeyRiskIndicatorKriLibraryResponse(BaseModel):
    """Result of key_risk_indicator_kri_library(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    num_kris: Any = Field(default=None)
    registry: Any = Field(default=None)


class KriThresholdBreachDetectionRequest(BaseModel):
    """Request parameters for kri_threshold_breach_detection()."""

    value: float
    amber_threshold: float
    red_threshold: float
    direction: str = "higher_breach"


class KriThresholdBreachDetectionResponse(BaseModel):
    """Result of kri_threshold_breach_detection(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    breached: Any = Field(default=None)
    status: Any = Field(default=None)


class KriTrendAnalysisRequest(BaseModel):
    """Request parameters for kri_trend_analysis()."""

    observations: list[float] | list[list[float]]
    higher_is_worse: bool = True


class KriTrendAnalysisResponse(BaseModel):
    """Result of kri_trend_analysis(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    latest: Any = Field(default=None)
    slope: Any = Field(default=None)
    trend: Any = Field(default=None)


class ScenarioFrequencyEstimationRequest(BaseModel):
    """Request parameters for scenario_frequency_estimation()."""

    expected_events_per_year: float
    occurrences: int | None = None
    observation_years: float | None = None


class ScenarioFrequencyEstimationResponse(BaseModel):
    """Result of scenario_frequency_estimation(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    f_lambda: Any = Field(default=None, alias="lambda")
    source: Any = Field(default=None)


class ScenarioSeverityEstimationRequest(BaseModel):
    """Request parameters for scenario_severity_estimation()."""

    typical_loss: float
    worst_case_loss: float
    worst_case_percentile: float = 0.99


class ScenarioSeverityEstimationResponse(BaseModel):
    """Result of scenario_severity_estimation(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    mean_severity: Any = Field(default=None)
    mu: Any = Field(default=None)
    sigma: Any = Field(default=None)


class ScenarioExpertElicitationModelRequest(BaseModel):
    """Request parameters for scenario_expert_elicitation_model()."""

    expert_estimates: list[float] | list[list[float]]
    expert_weights: list[float] | list[list[float]] | None = None


class ScenarioExpertElicitationModelResponse(BaseModel):
    """Result of scenario_expert_elicitation_model(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    coefficient_of_variation: Any = Field(default=None)
    consensus: Any = Field(default=None)
    dispersion: Any = Field(default=None)


class ScenarioAnalysisOpriskRequest(BaseModel):
    """Request parameters for scenario_analysis_oprisk()."""

    frequency_lambda: float
    severity_mu: float
    severity_sigma: float
    confidence_level: float = 0.999
    n_years: int = 50000
    seed: int | None = 42

    @field_validator("confidence_level")
    @classmethod
    def _confidence_range(cls, v: float) -> float:
        if v is not None and not (0.90 <= v <= 0.9999):
            raise ValueError(f"confidence_level {v} outside regulatory range [0.90, 0.9999]")
        return v


class ScenarioAnalysisOpriskResponse(BaseModel):
    """Result of scenario_analysis_oprisk(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    confidence_level: Any = Field(default=None)
    expected_loss: Any = Field(default=None)
    expected_shortfall: Any = Field(default=None)
    scenario_var: Any = Field(default=None)


class CyberRiskLossEstimationRequest(BaseModel):
    """Request parameters for cyber_risk_loss_estimation()."""

    records_exposed: float
    cost_per_record: float
    breach_probability: float
    business_interruption_cost: float = 0.0


class CyberRiskLossEstimationResponse(BaseModel):
    """Result of cyber_risk_loss_estimation(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    breach_probability: Any = Field(default=None)
    expected_loss: Any = Field(default=None)
    worst_case_loss: Any = Field(default=None)


class ConductRiskMetricRequest(BaseModel):
    """Request parameters for conduct_risk_metric()."""

    complaints: float
    customers: float
    redress_paid: float
    revenue: float


class ConductRiskMetricResponse(BaseModel):
    """Result of conduct_risk_metric(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    complaints_per_1000: Any = Field(default=None)
    conduct_index: Any = Field(default=None)
    rating: Any = Field(default=None)
    redress_ratio: Any = Field(default=None)


class ModelRiskAssessmentRequest(BaseModel):
    """Request parameters for model_risk_assessment()."""

    materiality: int
    complexity: int
    validation_score: float


class ModelRiskAssessmentResponse(BaseModel):
    """Result of model_risk_assessment(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    inherent_score: Any = Field(default=None)
    residual_score: Any = Field(default=None)
    tier: Any = Field(default=None)


class ItRiskScoringRequest(BaseModel):
    """Request parameters for it_risk_scoring()."""

    availability: float
    incident_count: float
    patch_compliance: float


class ItRiskScoringResponse(BaseModel):
    """Result of it_risk_scoring(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    it_risk_score: Any = Field(default=None)
    rating: Any = Field(default=None)


class ThirdPartyVendorRiskRequest(BaseModel):
    """Request parameters for third_party_vendor_risk()."""

    criticality: int
    financial_health: float
    concentration: float
    substitutability: float


class ThirdPartyVendorRiskResponse(BaseModel):
    """Result of third_party_vendor_risk(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    rating: Any = Field(default=None)
    vendor_risk_score: Any = Field(default=None)


class BusinessContinuityRiskScoreRequest(BaseModel):
    """Request parameters for business_continuity_risk_score()."""

    rto_hours: float
    rpo_hours: float
    max_tolerable_downtime: float
    bcp_maturity: float


class BusinessContinuityRiskScoreResponse(BaseModel):
    """Result of business_continuity_risk_score(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    bc_risk_score: Any = Field(default=None)
    mtd_breach: Any = Field(default=None)
    rating: Any = Field(default=None)


class NearMissCaptureFrameworkRequest(BaseModel):
    """Request parameters for near_miss_capture_framework()."""

    events: list[dict[str, Any]]


class NearMissCaptureFrameworkResponse(BaseModel):
    """Result of near_miss_capture_framework(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    actual_loss_count: Any = Field(default=None)
    near_miss_count: Any = Field(default=None)
    total_potential_loss: Any = Field(default=None)


class RootCauseAnalysisTemplateRequest(BaseModel):
    """Request parameters for root_cause_analysis_template()."""

    causal_factors: dict[str, Any]


class RootCauseAnalysisTemplateResponse(BaseModel):
    """Result of root_cause_analysis_template(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    attribution: Any = Field(default=None)
    num_factors: Any = Field(default=None)
    primary_cause: Any = Field(default=None)


class RiskAppetiteStatementOpriskRequest(BaseModel):
    """Request parameters for risk_appetite_statement_oprisk()."""

    current_metric: float
    appetite_limit: float
    tolerance_limit: float
    higher_is_worse: bool = True


class RiskAppetiteStatementOpriskResponse(BaseModel):
    """Result of risk_appetite_statement_oprisk(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    status: Any = Field(default=None)
    utilisation: Any = Field(default=None)


class EscalationThresholdCalculationRequest(BaseModel):
    """Request parameters for escalation_threshold_calculation()."""

    loss_amount: float
    thresholds: dict[str, Any]


class EscalationThresholdCalculationResponse(BaseModel):
    """Result of escalation_threshold_calculation(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    escalation_level: Any = Field(default=None)
    threshold: Any = Field(default=None)


class OpriskHeatMapGeneratorRequest(BaseModel):
    """Request parameters for oprisk_heat_map_generator()."""

    likelihoods: list[float] | list[list[float]]
    impacts: list[float] | list[list[float]]


class OpriskHeatMapGeneratorResponse(BaseModel):
    """Result of oprisk_heat_map_generator(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    matrix: Any = Field(default=None)
    ratings: Any = Field(default=None)
    scores: Any = Field(default=None)


class RegulatoryComplianceScoreRequest(BaseModel):
    """Request parameters for regulatory_compliance_score()."""

    requirements_met: list[float] | list[list[float]]
    weights: list[float] | list[list[float]] | None = None


class RegulatoryComplianceScoreResponse(BaseModel):
    """Result of regulatory_compliance_score(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    compliance_score: Any = Field(default=None)
    num_requirements: Any = Field(default=None)
    rating: Any = Field(default=None)


class AuditFindingRiskScorerRequest(BaseModel):
    """Request parameters for audit_finding_risk_scorer()."""

    severity: int
    likelihood: int
    overdue_days: float


class AuditFindingRiskScorerResponse(BaseModel):
    """Result of audit_finding_risk_scorer(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    adjusted_score: Any = Field(default=None)
    base_score: Any = Field(default=None)
    rating: Any = Field(default=None)
