"""schemas/regulatory.py — auto-generated Pydantic v2 contracts for the regulatory domain.

Generated by scripts/gen_p3.py from engine signatures. Request models are
precisely typed and enforce regulatory validators (CLAUDE.md s4). Response
models document engine return-dict keys; extra='allow' covers dynamically
built keys that static analysis cannot enumerate.
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class BaselIiiCet1RatioRequest(BaseModel):
    """Request parameters for basel_iii_cet1_ratio()."""

    cet1_capital: float
    risk_weighted_assets: float


class BaselIiiCet1RatioResponse(BaseModel):
    """Result of basel_iii_cet1_ratio(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    cet1_ratio: Any = Field(default=None)
    compliant: Any = Field(default=None)
    minimum: Any = Field(default=None)
    surplus: Any = Field(default=None)


class BaselIiiTier1RatioRequest(BaseModel):
    """Request parameters for basel_iii_tier1_ratio()."""

    tier1_capital: float
    risk_weighted_assets: float


class BaselIiiTier1RatioResponse(BaseModel):
    """Result of basel_iii_tier1_ratio(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    compliant: Any = Field(default=None)
    minimum: Any = Field(default=None)
    surplus: Any = Field(default=None)
    tier1_ratio: Any = Field(default=None)


class BaselIiiTotalCapitalRatioRequest(BaseModel):
    """Request parameters for basel_iii_total_capital_ratio()."""

    total_capital: float
    risk_weighted_assets: float


class BaselIiiTotalCapitalRatioResponse(BaseModel):
    """Result of basel_iii_total_capital_ratio(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    compliant: Any = Field(default=None)
    minimum: Any = Field(default=None)
    surplus: Any = Field(default=None)
    total_capital_ratio: Any = Field(default=None)


class BaselIiiLeverageRatioRequest(BaseModel):
    """Request parameters for basel_iii_leverage_ratio()."""

    tier1_capital: float
    total_exposure: float


class BaselIiiLeverageRatioResponse(BaseModel):
    """Result of basel_iii_leverage_ratio(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    compliant: Any = Field(default=None)
    leverage_ratio: Any = Field(default=None)
    minimum: Any = Field(default=None)
    surplus: Any = Field(default=None)


class BaselIvOutputFloorRequest(BaseModel):
    """Request parameters for basel_iv_output_floor()."""

    internal_model_rwa: float
    standardised_rwa: float
    floor_factor: float = 0.725


class BaselIvOutputFloorResponse(BaseModel):
    """Result of basel_iv_output_floor(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    binding: Any = Field(default=None)
    floor_factor: Any = Field(default=None)
    floor_rwa: Any = Field(default=None)
    floored_rwa: Any = Field(default=None)
    rwa_uplift: Any = Field(default=None)


class IcaapCapitalAssessmentRequest(BaseModel):
    """Request parameters for icaap_capital_assessment()."""

    pillar1_capital: float
    risk_capital_components: list[float] | list[list[float]]
    available_capital: float


class IcaapCapitalAssessmentResponse(BaseModel):
    """Result of icaap_capital_assessment(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    adequate: Any = Field(default=None)
    available_capital: Any = Field(default=None)
    capital_surplus: Any = Field(default=None)
    pillar2_capital: Any = Field(default=None)
    total_capital_requirement: Any = Field(default=None)


class SrepCapitalAddOnRequest(BaseModel):
    """Request parameters for srep_capital_add_on()."""

    pillar1_requirement: float
    pillar2a_addon_ratio: float
    risk_weighted_assets: float


class SrepCapitalAddOnResponse(BaseModel):
    """Result of srep_capital_add_on(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    pillar2a_capital: Any = Field(default=None)
    total_srep_requirement: Any = Field(default=None)
    tscr_ratio: Any = Field(default=None)


class Pillar2aCapitalRequest(BaseModel):
    """Request parameters for pillar_2a_capital()."""

    risk_addons: list[float] | list[list[float]]
    risk_weighted_assets: float


class Pillar2aCapitalResponse(BaseModel):
    """Result of pillar_2a_capital(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    n_components: Any = Field(default=None)
    pillar2a_capital: Any = Field(default=None)
    pillar2a_ratio: Any = Field(default=None)


class Pillar2bStressBufferRequest(BaseModel):
    """Request parameters for pillar_2b_stress_buffer()."""

    stressed_capital_depletion: float
    risk_weighted_assets: float


class Pillar2bStressBufferResponse(BaseModel):
    """Result of pillar_2b_stress_buffer(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    buffer_ratio: Any = Field(default=None)
    pillar2b_buffer: Any = Field(default=None)


class CombinedBufferRequirementRequest(BaseModel):
    """Request parameters for combined_buffer_requirement()."""

    capital_conservation_buffer_ratio: float = 0.025
    countercyclical_buffer_ratio: float = 0.0
    systemic_buffer_ratio: float = 0.0
    risk_weighted_assets: float = 0.0


class CombinedBufferRequirementResponse(BaseModel):
    """Result of combined_buffer_requirement(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    combined_buffer_ratio: Any = Field(default=None)


class CapitalConservationBufferRequest(BaseModel):
    """Request parameters for capital_conservation_buffer()."""

    cet1_ratio: float
    risk_weighted_assets: float
    buffer_ratio: float = 0.025


class CapitalConservationBufferResponse(BaseModel):
    """Result of capital_conservation_buffer(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    buffer_capital: Any = Field(default=None)
    buffer_met: Any = Field(default=None)
    mda_restricted: Any = Field(default=None)
    required_cet1_ratio: Any = Field(default=None)


class CountercyclicalCapitalBufferRequest(BaseModel):
    """Request parameters for countercyclical_capital_buffer()."""

    exposure_amounts: list[float] | list[list[float]]
    country_ccyb_rates: list[float] | list[list[float]]
    risk_weighted_assets: float


class CountercyclicalCapitalBufferResponse(BaseModel):
    """Result of countercyclical_capital_buffer(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    ccyb_capital: Any = Field(default=None)
    ccyb_rate: Any = Field(default=None)


class Crr2LargeExposureLimitRequest(BaseModel):
    """Request parameters for crr2_large_exposure_limit()."""

    exposure_value: float
    tier1_capital: float
    is_institution: bool = False


class Crr2LargeExposureLimitResponse(BaseModel):
    """Result of crr2_large_exposure_limit(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    excess: Any = Field(default=None)
    exposure_ratio: Any = Field(default=None)
    is_institution: Any = Field(default=None)
    limit: Any = Field(default=None)
    within_limit: Any = Field(default=None)


class FrtbSaMarketRiskCapitalRequest(BaseModel):
    """Request parameters for frtb_sa_market_risk_capital()."""

    sensitivities_charge: float
    default_risk_charge: float
    residual_risk_addon: float


class FrtbSaMarketRiskCapitalResponse(BaseModel):
    """Result of frtb_sa_market_risk_capital(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    default_risk_charge: Any = Field(default=None)
    residual_risk_addon: Any = Field(default=None)
    sa_capital: Any = Field(default=None)
    sensitivities_charge: Any = Field(default=None)


class FrtbImaMarketRiskCapitalRequest(BaseModel):
    """Request parameters for frtb_ima_market_risk_capital()."""

    expected_shortfall: float
    stressed_es_ratio: float
    multiplier: float
    non_modellable_ses: float = 0.0
    default_risk_charge: float = 0.0


class FrtbImaMarketRiskCapitalResponse(BaseModel):
    """Result of frtb_ima_market_risk_capital(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    default_risk_charge: Any = Field(default=None)
    es_charge: Any = Field(default=None)
    es_confidence: Any = Field(default=None)
    ima_capital: Any = Field(default=None)
    multiplier: Any = Field(default=None)
    non_modellable_ses: Any = Field(default=None)


class FrtbPlAttributionTestRequest(BaseModel):
    """Request parameters for frtb_pl_attribution_test()."""

    risk_theoretical_pnl: list[float] | list[list[float]]
    hypothetical_pnl: list[float] | list[list[float]]


class FrtbPlAttributionTestResponse(BaseModel):
    """Result of frtb_pl_attribution_test(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    ima_eligible: Any = Field(default=None)
    ratio: Any = Field(default=None)
    spearman_corr: Any = Field(default=None)
    zone: Any = Field(default=None)


class FrtbTradingDeskAggregationRequest(BaseModel):
    """Request parameters for frtb_trading_desk_aggregation()."""

    desk_sa_charges: list[float] | list[list[float]]
    desk_ima_charges: list[float] | list[list[float]]
    desk_ima_eligible: list[float] | list[list[float]]


class FrtbTradingDeskAggregationResponse(BaseModel):
    """Result of frtb_trading_desk_aggregation(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    ima_capital: Any = Field(default=None)
    n_ima_desks: Any = Field(default=None)
    n_sa_desks: Any = Field(default=None)
    sa_capital: Any = Field(default=None)
    total_capital: Any = Field(default=None)


class MifidIiTransactionReportValidatorRequest(BaseModel):
    """Request parameters for mifid_ii_transaction_report_validator()."""

    report: dict[str, Any]


class MifidIiTransactionReportValidatorResponse(BaseModel):
    """Result of mifid_ii_transaction_report_validator(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    errors: Any = Field(default=None)
    report: Any = Field(default=None)
    valid: Any = Field(default=None)


class MifidIiPreTradeTransparencyRequest(BaseModel):
    """Request parameters for mifid_ii_pre_trade_transparency()."""

    instrument_type: str
    order_size: float
    large_in_scale_threshold: float
    is_liquid: bool = True


class MifidIiPreTradeTransparencyResponse(BaseModel):
    """Result of mifid_ii_pre_trade_transparency(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    instrument_type: Any = Field(default=None)
    transparency_required: Any = Field(default=None)
    waiver: Any = Field(default=None)


class MifidIiPostTradeTransparencyRequest(BaseModel):
    """Request parameters for mifid_ii_post_trade_transparency()."""

    trade_size: float
    delayed_publication_threshold: float
    is_liquid: bool = True


class MifidIiPostTradeTransparencyResponse(BaseModel):
    """Result of mifid_ii_post_trade_transparency(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    deferral_eligible: Any = Field(default=None)
    publication: Any = Field(default=None)


class MifidIiBestExecutionMetricRequest(BaseModel):
    """Request parameters for mifid_ii_best_execution_metric()."""

    executed_prices: list[float] | list[list[float]]
    benchmark_prices: list[float] | list[list[float]]
    quantities: list[float] | list[list[float]]
    side: int = 1


class MifidIiBestExecutionMetricResponse(BaseModel):
    """Result of mifid_ii_best_execution_metric(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    fill_rate: Any = Field(default=None)
    n_fills: Any = Field(default=None)
    price_improvement_bps: Any = Field(default=None)
    total_quantity: Any = Field(default=None)


class MifidIiAlgorithmDocumentationRequest(BaseModel):
    """Request parameters for mifid_ii_algorithm_documentation()."""

    documentation: dict[str, Any]


class MifidIiAlgorithmDocumentationResponse(BaseModel):
    """Result of mifid_ii_algorithm_documentation(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    errors: Any = Field(default=None)
    report: Any = Field(default=None)
    valid: Any = Field(default=None)


class EmirTradeRepositoryReportRequest(BaseModel):
    """Request parameters for emir_trade_repository_report()."""

    trade: dict[str, Any]


class EmirTradeRepositoryReportResponse(BaseModel):
    """Result of emir_trade_repository_report(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    errors: Any = Field(default=None)
    report: Any = Field(default=None)
    valid: Any = Field(default=None)


class EmirClearingObligationCheckRequest(BaseModel):
    """Request parameters for emir_clearing_obligation_check().

    ``notionals`` covers ALL asset classes the counterparty has positions in,
    not just one -- required for the FC any-class-breach rule (EMIR REFIT
    Art. 4a(1)): a single class's notional alone cannot answer whether an
    FC's clearing obligation extends to its other classes too.
    """

    notionals: dict[str, float]
    counterparty_category: str
    clearing_thresholds: dict[str, float]


class EmirClearingObligationCheckResponse(BaseModel):
    """Result of emir_clearing_obligation_check(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    any_class_breached: Any = Field(default=None)
    clearing_required: Any = Field(default=None)
    counterparty_category: Any = Field(default=None)


class EmirMarginRequirementRequest(BaseModel):
    """Request parameters for emir_margin_requirement()."""

    portfolio_value: float
    initial_margin_rate: float
    variation_margin: float
    minimum_transfer_amount: float = 0.0


class EmirMarginRequirementResponse(BaseModel):
    """Result of emir_margin_requirement(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    initial_margin: Any = Field(default=None)
    total_margin: Any = Field(default=None)
    variation_margin_call: Any = Field(default=None)


class SftrSecuritiesFinanceReportRequest(BaseModel):
    """Request parameters for sftr_securities_finance_report()."""

    transaction: dict[str, Any]


class SftrSecuritiesFinanceReportResponse(BaseModel):
    """Result of sftr_securities_finance_report(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    errors: Any = Field(default=None)
    report: Any = Field(default=None)
    valid: Any = Field(default=None)


class AifmdRiskMetricsRequest(BaseModel):
    """Request parameters for aifmd_risk_metrics()."""

    gross_exposure: float
    commitment_exposure: float
    net_asset_value: float
    var_pct: float | None = None


class AifmdRiskMetricsResponse(BaseModel):
    """Result of aifmd_risk_metrics(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    commitment_leverage: Any = Field(default=None)
    gross_leverage: Any = Field(default=None)
    substantially_leveraged: Any = Field(default=None)


class UcitsKiidRiskIndicatorRequest(BaseModel):
    """Request parameters for ucits_kiid_risk_indicator()."""

    returns: list[float] | list[list[float]]
    periods_per_year: int = 52


class UcitsKiidRiskIndicatorResponse(BaseModel):
    """Result of ucits_kiid_risk_indicator(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    annualised_volatility: Any = Field(default=None)
    srri: Any = Field(default=None)


class SolvencyIiScrMarketRiskRequest(BaseModel):
    """Request parameters for solvency_ii_scr_market_risk()."""

    sub_module_charges: list[float] | list[list[float]]
    correlation_matrix: list[float] | list[list[float]]
    sub_module_names: list[str] | None = None


class SolvencyIiScrMarketRiskResponse(BaseModel):
    """Result of solvency_ii_scr_market_risk(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    diversification_benefit: Any = Field(default=None)
    scr_market: Any = Field(default=None)
    sum_of_charges: Any = Field(default=None)


class SolvencyIiScrCreditRiskRequest(BaseModel):
    """Request parameters for solvency_ii_scr_credit_risk().

    No ``risk_factor`` field: DR (EU) 2015/35 Art. 200(1)-(3) fixes the
    capital multiplier as a tiered function of sigma/total_lgd (3x/5x/capped
    at total LGD) — it is not a caller-configurable value. See the engine
    docstring for the regulatory fix this removal is part of.
    """

    exposures: list[float] | list[list[float]]
    loss_given_default: list[float] | list[list[float]]
    default_probabilities: list[float] | list[list[float]]


class SolvencyIiScrCreditRiskResponse(BaseModel):
    """Result of solvency_ii_scr_credit_risk(). Mirrors the engine return dict."""

    model_config = ConfigDict(extra="allow", protected_namespaces=())

    expected_loss: Any = Field(default=None)
    scr_credit: Any = Field(default=None)
    total_lgd: Any = Field(default=None)
