"""api/routes/alm.py — auto-generated FastAPI routes for the alm domain.

Generated by scripts/gen_p3.py. Each route validates its request, converts
list payloads to NumPy arrays, calls the engine wrapper (the single source
of truth), and returns the result dict via OrjsonResponse. No business logic
lives here.
"""

from __future__ import annotations

import logging
from typing import Any

import numpy as np
from fastapi import APIRouter, Depends, HTTPException, status

from api.middleware.auth import TokenPayload, get_current_user
from api.responses import OrjsonResponse
from engine.alm_behavioural import behavioural_modelling_nmds as _e_behavioural_modelling_nmds
from engine.alm_behavioural import core_deposit_duration as _e_core_deposit_duration
from engine.alm_behavioural import loan_prepayment_rate_cpr as _e_loan_prepayment_rate_cpr
from engine.alm_behavioural import (
    non_maturity_deposit_stability as _e_non_maturity_deposit_stability,
)
from engine.alm_behavioural import prepayment_model_mortgages as _e_prepayment_model_mortgages
from engine.alm_duration import convexity_gap as _e_convexity_gap
from engine.alm_duration import duration_gap_analysis as _e_duration_gap_analysis
from engine.alm_duration import effective_duration_alm as _e_effective_duration_alm
from engine.alm_duration import (
    macaulay_duration_balance_sheet as _e_macaulay_duration_balance_sheet,
)
from engine.alm_duration import (
    modified_duration_balance_sheet as _e_modified_duration_balance_sheet,
)
from engine.alm_duration import nii_sensitivity_rate_shock as _e_nii_sensitivity_rate_shock
from engine.alm_duration import nii_simulation_baseline as _e_nii_simulation_baseline
from engine.alm_ftp import alm_stress_test as _e_alm_stress_test
from engine.alm_ftp import balance_sheet_projection_model as _e_balance_sheet_projection_model
from engine.alm_ftp import ftp_curve_construction as _e_ftp_curve_construction
from engine.alm_ftp import funds_transfer_pricing_ftp as _e_funds_transfer_pricing_ftp
from engine.alm_ftp import structural_hedge_optimisation as _e_structural_hedge_optimisation
from engine.alm_irrbb import asset_liability_mismatch_index as _e_asset_liability_mismatch_index
from engine.alm_irrbb import basis_risk_irrbb as _e_basis_risk_irrbb
from engine.alm_irrbb import dynamic_gap_analysis as _e_dynamic_gap_analysis
from engine.alm_irrbb import interest_rate_risk_capital_irrbb as _e_interest_rate_risk_capital_irrbb
from engine.alm_irrbb import irrbb_internal_model as _e_irrbb_internal_model
from engine.alm_irrbb import irrbb_six_standard_rate_shocks as _e_irrbb_six_standard_rate_shocks
from engine.alm_irrbb import irrbb_standardised_framework as _e_irrbb_standardised_framework
from engine.alm_irrbb import option_risk_irrbb as _e_option_risk_irrbb
from engine.alm_irrbb import pipeline_risk_measurement as _e_pipeline_risk_measurement
from engine.alm_irrbb import repricing_gap_analysis as _e_repricing_gap_analysis
from engine.alm_irrbb import repricing_maturity_profile as _e_repricing_maturity_profile
from engine.alm_irrbb import static_gap_analysis as _e_static_gap_analysis
from engine.alm_nii_eve import economic_value_of_equity_eve as _e_economic_value_of_equity_eve
from engine.alm_nii_eve import eve_sensitivity_analysis as _e_eve_sensitivity_analysis
from engine.alm_nii_eve import liquidity_adjusted_nii as _e_liquidity_adjusted_nii
from engine.alm_nii_eve import nii_simulation_stress as _e_nii_simulation_stress
from schemas.alm import (
    AlmStressTestRequest,
    AlmStressTestResponse,
    AssetLiabilityMismatchIndexRequest,
    AssetLiabilityMismatchIndexResponse,
    BalanceSheetProjectionModelRequest,
    BalanceSheetProjectionModelResponse,
    BasisRiskIrrbbRequest,
    BasisRiskIrrbbResponse,
    BehaviouralModellingNmdsRequest,
    BehaviouralModellingNmdsResponse,
    ConvexityGapRequest,
    ConvexityGapResponse,
    CoreDepositDurationRequest,
    CoreDepositDurationResponse,
    DurationGapAnalysisRequest,
    DurationGapAnalysisResponse,
    DynamicGapAnalysisRequest,
    DynamicGapAnalysisResponse,
    EconomicValueOfEquityEveRequest,
    EconomicValueOfEquityEveResponse,
    EffectiveDurationAlmRequest,
    EffectiveDurationAlmResponse,
    EveSensitivityAnalysisRequest,
    EveSensitivityAnalysisResponse,
    FtpCurveConstructionRequest,
    FtpCurveConstructionResponse,
    FundsTransferPricingFtpRequest,
    FundsTransferPricingFtpResponse,
    InterestRateRiskCapitalIrrbbRequest,
    InterestRateRiskCapitalIrrbbResponse,
    IrrbbInternalModelRequest,
    IrrbbInternalModelResponse,
    IrrbbSixStandardRateShocksRequest,
    IrrbbSixStandardRateShocksResponse,
    IrrbbStandardisedFrameworkRequest,
    IrrbbStandardisedFrameworkResponse,
    LiquidityAdjustedNiiRequest,
    LiquidityAdjustedNiiResponse,
    LoanPrepaymentRateCprRequest,
    LoanPrepaymentRateCprResponse,
    MacaulayDurationBalanceSheetRequest,
    MacaulayDurationBalanceSheetResponse,
    ModifiedDurationBalanceSheetRequest,
    ModifiedDurationBalanceSheetResponse,
    NiiSensitivityRateShockRequest,
    NiiSensitivityRateShockResponse,
    NiiSimulationBaselineRequest,
    NiiSimulationBaselineResponse,
    NiiSimulationStressRequest,
    NiiSimulationStressResponse,
    NonMaturityDepositStabilityRequest,
    NonMaturityDepositStabilityResponse,
    OptionRiskIrrbbRequest,
    OptionRiskIrrbbResponse,
    PipelineRiskMeasurementRequest,
    PipelineRiskMeasurementResponse,
    PrepaymentModelMortgagesRequest,
    PrepaymentModelMortgagesResponse,
    RepricingGapAnalysisRequest,
    RepricingGapAnalysisResponse,
    RepricingMaturityProfileRequest,
    RepricingMaturityProfileResponse,
    StaticGapAnalysisRequest,
    StaticGapAnalysisResponse,
    StructuralHedgeOptimisationRequest,
    StructuralHedgeOptimisationResponse,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/alm", tags=["alm"])

# Engine input errors → HTTP 422. Explicit tuple (no bare except) covers
# bad numeric domains, singular matrices, and shape/key mismatches.
_INPUT_ERRORS = (
    ValueError,
    TypeError,
    KeyError,
    IndexError,
    ArithmeticError,
    AssertionError,
    np.linalg.LinAlgError,
)


@router.post(
    "/macaulay_duration_balance_sheet",
    response_model=MacaulayDurationBalanceSheetResponse,
    summary="Macaulay Duration Balance Sheet",
)
async def macaulay_duration_balance_sheet(
    body: MacaulayDurationBalanceSheetRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["cashflows"] = np.asarray(kwargs["cashflows"], dtype=np.float64)
    kwargs["times"] = np.asarray(kwargs["times"], dtype=np.float64)
    try:
        result: Any = _e_macaulay_duration_balance_sheet(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/modified_duration_balance_sheet",
    response_model=ModifiedDurationBalanceSheetResponse,
    summary="Modified Duration Balance Sheet",
)
async def modified_duration_balance_sheet(
    body: ModifiedDurationBalanceSheetRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["cashflows"] = np.asarray(kwargs["cashflows"], dtype=np.float64)
    kwargs["times"] = np.asarray(kwargs["times"], dtype=np.float64)
    try:
        result: Any = _e_modified_duration_balance_sheet(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/effective_duration_alm",
    response_model=EffectiveDurationAlmResponse,
    summary="Effective Duration Alm",
)
async def effective_duration_alm(
    body: EffectiveDurationAlmRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_effective_duration_alm(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/duration_gap_analysis",
    response_model=DurationGapAnalysisResponse,
    summary="Duration Gap Analysis",
)
async def duration_gap_analysis(
    body: DurationGapAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_duration_gap_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/convexity_gap",
    response_model=ConvexityGapResponse,
    summary="Convexity Gap",
)
async def convexity_gap(
    body: ConvexityGapRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_convexity_gap(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/nii_sensitivity_rate_shock",
    response_model=NiiSensitivityRateShockResponse,
    summary="Nii Sensitivity Rate Shock",
)
async def nii_sensitivity_rate_shock(
    body: NiiSensitivityRateShockRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_nii_sensitivity_rate_shock(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/nii_simulation_baseline",
    response_model=NiiSimulationBaselineResponse,
    summary="Nii Simulation Baseline",
)
async def nii_simulation_baseline(
    body: NiiSimulationBaselineRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_balances"] = np.asarray(kwargs["asset_balances"], dtype=np.float64)
    kwargs["asset_rates"] = np.asarray(kwargs["asset_rates"], dtype=np.float64)
    kwargs["liability_balances"] = np.asarray(kwargs["liability_balances"], dtype=np.float64)
    kwargs["liability_rates"] = np.asarray(kwargs["liability_rates"], dtype=np.float64)
    try:
        result: Any = _e_nii_simulation_baseline(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/nii_simulation_stress",
    response_model=NiiSimulationStressResponse,
    summary="Nii Simulation Stress",
)
async def nii_simulation_stress(
    body: NiiSimulationStressRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_balances"] = np.asarray(kwargs["asset_balances"], dtype=np.float64)
    kwargs["asset_rates"] = np.asarray(kwargs["asset_rates"], dtype=np.float64)
    kwargs["liability_balances"] = np.asarray(kwargs["liability_balances"], dtype=np.float64)
    kwargs["liability_rates"] = np.asarray(kwargs["liability_rates"], dtype=np.float64)
    try:
        result: Any = _e_nii_simulation_stress(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/economic_value_of_equity_eve",
    response_model=EconomicValueOfEquityEveResponse,
    summary="Economic Value Of Equity Eve",
)
async def economic_value_of_equity_eve(
    body: EconomicValueOfEquityEveRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_cashflows"] = np.asarray(kwargs["asset_cashflows"], dtype=np.float64)
    kwargs["asset_times"] = np.asarray(kwargs["asset_times"], dtype=np.float64)
    kwargs["liability_cashflows"] = np.asarray(kwargs["liability_cashflows"], dtype=np.float64)
    kwargs["liability_times"] = np.asarray(kwargs["liability_times"], dtype=np.float64)
    kwargs["asset_rates"] = np.asarray(kwargs["asset_rates"], dtype=np.float64)
    kwargs["liability_rates"] = np.asarray(kwargs["liability_rates"], dtype=np.float64)
    try:
        result: Any = _e_economic_value_of_equity_eve(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/eve_sensitivity_analysis",
    response_model=EveSensitivityAnalysisResponse,
    summary="Eve Sensitivity Analysis",
)
async def eve_sensitivity_analysis(
    body: EveSensitivityAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["net_cashflows"] = np.asarray(kwargs["net_cashflows"], dtype=np.float64)
    kwargs["times"] = np.asarray(kwargs["times"], dtype=np.float64)
    kwargs["base_rates"] = np.asarray(kwargs["base_rates"], dtype=np.float64)
    try:
        result: Any = _e_eve_sensitivity_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/liquidity_adjusted_nii",
    response_model=LiquidityAdjustedNiiResponse,
    summary="Liquidity Adjusted Nii",
)
async def liquidity_adjusted_nii(
    body: LiquidityAdjustedNiiRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_liquidity_adjusted_nii(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/irrbb_six_standard_rate_shocks",
    response_model=IrrbbSixStandardRateShocksResponse,
    summary="Irrbb Six Standard Rate Shocks",
)
async def irrbb_six_standard_rate_shocks(
    body: IrrbbSixStandardRateShocksRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["tenors"] = np.asarray(kwargs["tenors"], dtype=np.float64)
    try:
        result: Any = _e_irrbb_six_standard_rate_shocks(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/irrbb_standardised_framework",
    response_model=IrrbbStandardisedFrameworkResponse,
    summary="Irrbb Standardised Framework",
)
async def irrbb_standardised_framework(
    body: IrrbbStandardisedFrameworkRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["net_cashflows"] = np.asarray(kwargs["net_cashflows"], dtype=np.float64)
    kwargs["times"] = np.asarray(kwargs["times"], dtype=np.float64)
    kwargs["base_rates"] = np.asarray(kwargs["base_rates"], dtype=np.float64)
    try:
        result: Any = _e_irrbb_standardised_framework(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/irrbb_internal_model",
    response_model=IrrbbInternalModelResponse,
    summary="Irrbb Internal Model",
)
async def irrbb_internal_model(
    body: IrrbbInternalModelRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["net_cashflows"] = np.asarray(kwargs["net_cashflows"], dtype=np.float64)
    kwargs["times"] = np.asarray(kwargs["times"], dtype=np.float64)
    kwargs["base_rates"] = np.asarray(kwargs["base_rates"], dtype=np.float64)
    kwargs["rate_scenarios"] = np.asarray(kwargs["rate_scenarios"], dtype=np.float64)
    try:
        result: Any = _e_irrbb_internal_model(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/repricing_gap_analysis",
    response_model=RepricingGapAnalysisResponse,
    summary="Repricing Gap Analysis",
)
async def repricing_gap_analysis(
    body: RepricingGapAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["bucket_assets"] = np.asarray(kwargs["bucket_assets"], dtype=np.float64)
    kwargs["bucket_liabilities"] = np.asarray(kwargs["bucket_liabilities"], dtype=np.float64)
    try:
        result: Any = _e_repricing_gap_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/repricing_maturity_profile",
    response_model=RepricingMaturityProfileResponse,
    summary="Repricing Maturity Profile",
)
async def repricing_maturity_profile(
    body: RepricingMaturityProfileRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["balances"] = np.asarray(kwargs["balances"], dtype=np.float64)
    kwargs["repricing_times"] = np.asarray(kwargs["repricing_times"], dtype=np.float64)
    kwargs["bucket_edges"] = np.asarray(kwargs["bucket_edges"], dtype=np.float64)
    try:
        result: Any = _e_repricing_maturity_profile(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/static_gap_analysis",
    response_model=StaticGapAnalysisResponse,
    summary="Static Gap Analysis",
)
async def static_gap_analysis(
    body: StaticGapAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["bucket_assets"] = np.asarray(kwargs["bucket_assets"], dtype=np.float64)
    kwargs["bucket_liabilities"] = np.asarray(kwargs["bucket_liabilities"], dtype=np.float64)
    try:
        result: Any = _e_static_gap_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/dynamic_gap_analysis",
    response_model=DynamicGapAnalysisResponse,
    summary="Dynamic Gap Analysis",
)
async def dynamic_gap_analysis(
    body: DynamicGapAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["bucket_assets"] = np.asarray(kwargs["bucket_assets"], dtype=np.float64)
    kwargs["bucket_liabilities"] = np.asarray(kwargs["bucket_liabilities"], dtype=np.float64)
    kwargs["asset_growth"] = np.asarray(kwargs["asset_growth"], dtype=np.float64)
    kwargs["liability_growth"] = np.asarray(kwargs["liability_growth"], dtype=np.float64)
    try:
        result: Any = _e_dynamic_gap_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/basis_risk_irrbb",
    response_model=BasisRiskIrrbbResponse,
    summary="Basis Risk Irrbb",
)
async def basis_risk_irrbb(
    body: BasisRiskIrrbbRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_balances"] = np.asarray(kwargs["asset_balances"], dtype=np.float64)
    kwargs["asset_index_shifts"] = np.asarray(kwargs["asset_index_shifts"], dtype=np.float64)
    kwargs["liability_balances"] = np.asarray(kwargs["liability_balances"], dtype=np.float64)
    kwargs["liability_index_shifts"] = np.asarray(
        kwargs["liability_index_shifts"], dtype=np.float64
    )
    try:
        result: Any = _e_basis_risk_irrbb(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/option_risk_irrbb",
    response_model=OptionRiskIrrbbResponse,
    summary="Option Risk Irrbb",
)
async def option_risk_irrbb(
    body: OptionRiskIrrbbRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_option_risk_irrbb(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/pipeline_risk_measurement",
    response_model=PipelineRiskMeasurementResponse,
    summary="Pipeline Risk Measurement",
)
async def pipeline_risk_measurement(
    body: PipelineRiskMeasurementRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_pipeline_risk_measurement(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/interest_rate_risk_capital_irrbb",
    response_model=InterestRateRiskCapitalIrrbbResponse,
    summary="Interest Rate Risk Capital Irrbb",
)
async def interest_rate_risk_capital_irrbb(
    body: InterestRateRiskCapitalIrrbbRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_interest_rate_risk_capital_irrbb(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/asset_liability_mismatch_index",
    response_model=AssetLiabilityMismatchIndexResponse,
    summary="Asset Liability Mismatch Index",
)
async def asset_liability_mismatch_index(
    body: AssetLiabilityMismatchIndexRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_durations"] = np.asarray(kwargs["asset_durations"], dtype=np.float64)
    kwargs["asset_amounts"] = np.asarray(kwargs["asset_amounts"], dtype=np.float64)
    kwargs["liability_durations"] = np.asarray(kwargs["liability_durations"], dtype=np.float64)
    kwargs["liability_amounts"] = np.asarray(kwargs["liability_amounts"], dtype=np.float64)
    try:
        result: Any = _e_asset_liability_mismatch_index(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/loan_prepayment_rate_cpr",
    response_model=LoanPrepaymentRateCprResponse,
    summary="Loan Prepayment Rate Cpr",
)
async def loan_prepayment_rate_cpr(
    body: LoanPrepaymentRateCprRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_loan_prepayment_rate_cpr(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/prepayment_model_mortgages",
    response_model=PrepaymentModelMortgagesResponse,
    summary="Prepayment Model Mortgages",
)
async def prepayment_model_mortgages(
    body: PrepaymentModelMortgagesRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_prepayment_model_mortgages(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/behavioural_modelling_nmds",
    response_model=BehaviouralModellingNmdsResponse,
    summary="Behavioural Modelling Nmds",
)
async def behavioural_modelling_nmds(
    body: BehaviouralModellingNmdsRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_behavioural_modelling_nmds(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/non_maturity_deposit_stability",
    response_model=NonMaturityDepositStabilityResponse,
    summary="Non Maturity Deposit Stability",
)
async def non_maturity_deposit_stability(
    body: NonMaturityDepositStabilityRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["balance_history"] = np.asarray(kwargs["balance_history"], dtype=np.float64)
    try:
        result: Any = _e_non_maturity_deposit_stability(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/core_deposit_duration",
    response_model=CoreDepositDurationResponse,
    summary="Core Deposit Duration",
)
async def core_deposit_duration(
    body: CoreDepositDurationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_core_deposit_duration(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/funds_transfer_pricing_ftp",
    response_model=FundsTransferPricingFtpResponse,
    summary="Funds Transfer Pricing Ftp",
)
async def funds_transfer_pricing_ftp(
    body: FundsTransferPricingFtpRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_funds_transfer_pricing_ftp(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/ftp_curve_construction",
    response_model=FtpCurveConstructionResponse,
    summary="Ftp Curve Construction",
)
async def ftp_curve_construction(
    body: FtpCurveConstructionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["tenors"] = np.asarray(kwargs["tenors"], dtype=np.float64)
    kwargs["base_curve"] = np.asarray(kwargs["base_curve"], dtype=np.float64)
    kwargs["liquidity_spreads"] = np.asarray(kwargs["liquidity_spreads"], dtype=np.float64)
    try:
        result: Any = _e_ftp_curve_construction(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/structural_hedge_optimisation",
    response_model=StructuralHedgeOptimisationResponse,
    summary="Structural Hedge Optimisation",
)
async def structural_hedge_optimisation(
    body: StructuralHedgeOptimisationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["instrument_durations"] = np.asarray(kwargs["instrument_durations"], dtype=np.float64)
    kwargs["instrument_max_notional"] = np.asarray(
        kwargs["instrument_max_notional"], dtype=np.float64
    )
    try:
        result: Any = _e_structural_hedge_optimisation(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/alm_stress_test",
    response_model=AlmStressTestResponse,
    summary="Alm Stress Test",
)
async def alm_stress_test(
    body: AlmStressTestRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["net_cashflows"] = np.asarray(kwargs["net_cashflows"], dtype=np.float64)
    kwargs["times"] = np.asarray(kwargs["times"], dtype=np.float64)
    kwargs["base_rates"] = np.asarray(kwargs["base_rates"], dtype=np.float64)
    try:
        result: Any = _e_alm_stress_test(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/balance_sheet_projection_model",
    response_model=BalanceSheetProjectionModelResponse,
    summary="Balance Sheet Projection Model",
)
async def balance_sheet_projection_model(
    body: BalanceSheetProjectionModelRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_balance_sheet_projection_model(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)
