"""api/routes/liquidity.py — auto-generated FastAPI routes for the liquidity domain.

Generated by scripts/gen_p3.py. Each route validates its request, converts
list payloads to NumPy arrays, calls the engine wrapper (the single source
of truth), and returns the result dict via OrjsonResponse. No business logic
lives here.
"""

from __future__ import annotations

import logging
from typing import Any

import numpy as np
from fastapi import APIRouter, Depends, HTTPException, status

from api.middleware.auth import TokenPayload, get_current_user
from api.responses import OrjsonResponse
from engine.liquidity_cashflow import cash_flow_ladder_1_year as _e_cash_flow_ladder_1_year
from engine.liquidity_cashflow import cash_flow_ladder_30_day as _e_cash_flow_ladder_30_day
from engine.liquidity_cashflow import funding_tenor_analysis as _e_funding_tenor_analysis
from engine.liquidity_cashflow import liquidity_gap_analysis as _e_liquidity_gap_analysis
from engine.liquidity_funding import asset_encumbrance_ratio as _e_asset_encumbrance_ratio
from engine.liquidity_funding import (
    collateral_availability_analysis as _e_collateral_availability_analysis,
)
from engine.liquidity_funding import (
    contingency_funding_plan_trigger as _e_contingency_funding_plan_trigger,
)
from engine.liquidity_funding import funding_cost_analysis as _e_funding_cost_analysis
from engine.liquidity_funding import (
    fx_liquidity_risk_by_currency as _e_fx_liquidity_risk_by_currency,
)
from engine.liquidity_funding import intragroup_liquidity_flow as _e_intragroup_liquidity_flow
from engine.liquidity_funding import liquidity_buffer_sizing as _e_liquidity_buffer_sizing
from engine.liquidity_funding import liquidity_transfer_pricing as _e_liquidity_transfer_pricing
from engine.liquidity_funding import repo_market_stress_haircut as _e_repo_market_stress_haircut
from engine.liquidity_funding import retail_deposit_runoff_rate as _e_retail_deposit_runoff_rate
from engine.liquidity_funding import (
    secured_funding_rollover_risk as _e_secured_funding_rollover_risk,
)
from engine.liquidity_funding import (
    wholesale_funding_concentration as _e_wholesale_funding_concentration,
)
from engine.liquidity_internal import (
    central_bank_facility_eligibility as _e_central_bank_facility_eligibility,
)
from engine.liquidity_internal import contingent_liquidity_risk as _e_contingent_liquidity_risk
from engine.liquidity_internal import (
    cross_currency_liquidity_bridge as _e_cross_currency_liquidity_bridge,
)
from engine.liquidity_internal import (
    deposit_stability_classification as _e_deposit_stability_classification,
)
from engine.liquidity_internal import (
    early_warning_indicator_liquidity as _e_early_warning_indicator_liquidity,
)
from engine.liquidity_internal import (
    ilaap_internal_liquidity_metric as _e_ilaap_internal_liquidity_metric,
)
from engine.liquidity_internal import (
    liquidity_risk_appetite_threshold as _e_liquidity_risk_appetite_threshold,
)
from engine.liquidity_internal import (
    liquidity_scorecard_aggregation as _e_liquidity_scorecard_aggregation,
)
from engine.liquidity_ratios import (
    available_stable_funding_asf_calc as _e_available_stable_funding_asf_calc,
)
from engine.liquidity_ratios import (
    hqla_level_1_asset_classifier as _e_hqla_level_1_asset_classifier,
)
from engine.liquidity_ratios import (
    hqla_level_2a_asset_classifier as _e_hqla_level_2a_asset_classifier,
)
from engine.liquidity_ratios import (
    hqla_level_2b_asset_classifier as _e_hqla_level_2b_asset_classifier,
)
from engine.liquidity_ratios import liquidity_coverage_ratio_lcr as _e_liquidity_coverage_ratio_lcr
from engine.liquidity_ratios import (
    net_stable_funding_ratio_nsfr as _e_net_stable_funding_ratio_nsfr,
)
from engine.liquidity_ratios import (
    required_stable_funding_rsf_calc as _e_required_stable_funding_rsf_calc,
)
from engine.liquidity_stress import combined_stress_scenario as _e_combined_stress_scenario
from engine.liquidity_stress import (
    idiosyncratic_stress_scenario as _e_idiosyncratic_stress_scenario,
)
from engine.liquidity_stress import (
    ilaap_stress_testing_framework as _e_ilaap_stress_testing_framework,
)
from engine.liquidity_stress import intraday_liquidity_monitor as _e_intraday_liquidity_monitor
from engine.liquidity_stress import (
    intraday_liquidity_stress_test as _e_intraday_liquidity_stress_test,
)
from engine.liquidity_stress import liquidity_stress_scenario as _e_liquidity_stress_scenario
from engine.liquidity_stress import liquidity_var_liqvar as _e_liquidity_var_liqvar
from engine.liquidity_stress import market_wide_stress_scenario as _e_market_wide_stress_scenario
from engine.liquidity_stress import survival_horizon_calculator as _e_survival_horizon_calculator
from schemas.liquidity import (
    AssetEncumbranceRatioRequest,
    AssetEncumbranceRatioResponse,
    AvailableStableFundingAsfCalcRequest,
    AvailableStableFundingAsfCalcResponse,
    CashFlowLadder1YearRequest,
    CashFlowLadder1YearResponse,
    CashFlowLadder30DayRequest,
    CashFlowLadder30DayResponse,
    CentralBankFacilityEligibilityRequest,
    CentralBankFacilityEligibilityResponse,
    CollateralAvailabilityAnalysisRequest,
    CollateralAvailabilityAnalysisResponse,
    CombinedStressScenarioRequest,
    CombinedStressScenarioResponse,
    ContingencyFundingPlanTriggerRequest,
    ContingencyFundingPlanTriggerResponse,
    ContingentLiquidityRiskRequest,
    ContingentLiquidityRiskResponse,
    CrossCurrencyLiquidityBridgeRequest,
    CrossCurrencyLiquidityBridgeResponse,
    DepositStabilityClassificationRequest,
    DepositStabilityClassificationResponse,
    EarlyWarningIndicatorLiquidityRequest,
    EarlyWarningIndicatorLiquidityResponse,
    FundingCostAnalysisRequest,
    FundingCostAnalysisResponse,
    FundingTenorAnalysisRequest,
    FundingTenorAnalysisResponse,
    FxLiquidityRiskByCurrencyRequest,
    FxLiquidityRiskByCurrencyResponse,
    HqlaLevel1AssetClassifierRequest,
    HqlaLevel1AssetClassifierResponse,
    HqlaLevel2aAssetClassifierRequest,
    HqlaLevel2aAssetClassifierResponse,
    HqlaLevel2bAssetClassifierRequest,
    HqlaLevel2bAssetClassifierResponse,
    IdiosyncraticStressScenarioRequest,
    IdiosyncraticStressScenarioResponse,
    IlaapInternalLiquidityMetricRequest,
    IlaapInternalLiquidityMetricResponse,
    IlaapStressTestingFrameworkRequest,
    IlaapStressTestingFrameworkResponse,
    IntradayLiquidityMonitorRequest,
    IntradayLiquidityMonitorResponse,
    IntradayLiquidityStressTestRequest,
    IntradayLiquidityStressTestResponse,
    IntragroupLiquidityFlowRequest,
    IntragroupLiquidityFlowResponse,
    LiquidityBufferSizingRequest,
    LiquidityBufferSizingResponse,
    LiquidityCoverageRatioLcrRequest,
    LiquidityCoverageRatioLcrResponse,
    LiquidityGapAnalysisRequest,
    LiquidityGapAnalysisResponse,
    LiquidityRiskAppetiteThresholdRequest,
    LiquidityRiskAppetiteThresholdResponse,
    LiquidityScorecardAggregationRequest,
    LiquidityScorecardAggregationResponse,
    LiquidityStressScenarioRequest,
    LiquidityStressScenarioResponse,
    LiquidityTransferPricingRequest,
    LiquidityTransferPricingResponse,
    LiquidityVarLiqvarRequest,
    LiquidityVarLiqvarResponse,
    MarketWideStressScenarioRequest,
    MarketWideStressScenarioResponse,
    NetStableFundingRatioNsfrRequest,
    NetStableFundingRatioNsfrResponse,
    RepoMarketStressHaircutRequest,
    RepoMarketStressHaircutResponse,
    RequiredStableFundingRsfCalcRequest,
    RequiredStableFundingRsfCalcResponse,
    RetailDepositRunoffRateRequest,
    RetailDepositRunoffRateResponse,
    SecuredFundingRolloverRiskRequest,
    SecuredFundingRolloverRiskResponse,
    SurvivalHorizonCalculatorRequest,
    SurvivalHorizonCalculatorResponse,
    WholesaleFundingConcentrationRequest,
    WholesaleFundingConcentrationResponse,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/liquidity", tags=["liquidity"])

# Engine input errors → HTTP 422. Explicit tuple (no bare except) covers
# bad numeric domains, singular matrices, and shape/key mismatches.
_INPUT_ERRORS = (
    ValueError,
    TypeError,
    KeyError,
    IndexError,
    ArithmeticError,
    AssertionError,
    np.linalg.LinAlgError,
)


@router.post(
    "/liquidity_coverage_ratio_lcr",
    response_model=LiquidityCoverageRatioLcrResponse,
    summary="Liquidity Coverage Ratio Lcr",
)
async def liquidity_coverage_ratio_lcr(
    body: LiquidityCoverageRatioLcrRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_liquidity_coverage_ratio_lcr(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/available_stable_funding_asf_calc",
    response_model=AvailableStableFundingAsfCalcResponse,
    summary="Available Stable Funding Asf Calc",
)
async def available_stable_funding_asf_calc(
    body: AvailableStableFundingAsfCalcRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["funding_amounts"] = np.asarray(kwargs["funding_amounts"], dtype=np.float64)
    kwargs["asf_factors"] = np.asarray(kwargs["asf_factors"], dtype=np.float64)
    try:
        result: Any = _e_available_stable_funding_asf_calc(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/required_stable_funding_rsf_calc",
    response_model=RequiredStableFundingRsfCalcResponse,
    summary="Required Stable Funding Rsf Calc",
)
async def required_stable_funding_rsf_calc(
    body: RequiredStableFundingRsfCalcRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_amounts"] = np.asarray(kwargs["asset_amounts"], dtype=np.float64)
    kwargs["rsf_factors"] = np.asarray(kwargs["rsf_factors"], dtype=np.float64)
    try:
        result: Any = _e_required_stable_funding_rsf_calc(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/net_stable_funding_ratio_nsfr",
    response_model=NetStableFundingRatioNsfrResponse,
    summary="Net Stable Funding Ratio Nsfr",
)
async def net_stable_funding_ratio_nsfr(
    body: NetStableFundingRatioNsfrRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_net_stable_funding_ratio_nsfr(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/hqla_level_1_asset_classifier",
    response_model=HqlaLevel1AssetClassifierResponse,
    summary="Hqla Level 1 Asset Classifier",
)
async def hqla_level_1_asset_classifier(
    body: HqlaLevel1AssetClassifierRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_values"] = np.asarray(kwargs["asset_values"], dtype=np.float64)
    if kwargs["haircuts"] is not None:
        kwargs["haircuts"] = np.asarray(kwargs["haircuts"], dtype=np.float64)
    try:
        result: Any = _e_hqla_level_1_asset_classifier(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/hqla_level_2a_asset_classifier",
    response_model=HqlaLevel2aAssetClassifierResponse,
    summary="Hqla Level 2A Asset Classifier",
)
async def hqla_level_2a_asset_classifier(
    body: HqlaLevel2aAssetClassifierRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_values"] = np.asarray(kwargs["asset_values"], dtype=np.float64)
    try:
        result: Any = _e_hqla_level_2a_asset_classifier(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/hqla_level_2b_asset_classifier",
    response_model=HqlaLevel2bAssetClassifierResponse,
    summary="Hqla Level 2B Asset Classifier",
)
async def hqla_level_2b_asset_classifier(
    body: HqlaLevel2bAssetClassifierRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_values"] = np.asarray(kwargs["asset_values"], dtype=np.float64)
    try:
        result: Any = _e_hqla_level_2b_asset_classifier(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/cash_flow_ladder_30_day",
    response_model=CashFlowLadder30DayResponse,
    summary="Cash Flow Ladder 30 Day",
)
async def cash_flow_ladder_30_day(
    body: CashFlowLadder30DayRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["daily_inflows"] = np.asarray(kwargs["daily_inflows"], dtype=np.float64)
    kwargs["daily_outflows"] = np.asarray(kwargs["daily_outflows"], dtype=np.float64)
    try:
        result: Any = _e_cash_flow_ladder_30_day(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/cash_flow_ladder_1_year",
    response_model=CashFlowLadder1YearResponse,
    summary="Cash Flow Ladder 1 Year",
)
async def cash_flow_ladder_1_year(
    body: CashFlowLadder1YearRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["bucket_inflows"] = np.asarray(kwargs["bucket_inflows"], dtype=np.float64)
    kwargs["bucket_outflows"] = np.asarray(kwargs["bucket_outflows"], dtype=np.float64)
    try:
        result: Any = _e_cash_flow_ladder_1_year(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/liquidity_gap_analysis",
    response_model=LiquidityGapAnalysisResponse,
    summary="Liquidity Gap Analysis",
)
async def liquidity_gap_analysis(
    body: LiquidityGapAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_maturities"] = np.asarray(kwargs["asset_maturities"], dtype=np.float64)
    kwargs["liability_maturities"] = np.asarray(kwargs["liability_maturities"], dtype=np.float64)
    try:
        result: Any = _e_liquidity_gap_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/funding_tenor_analysis",
    response_model=FundingTenorAnalysisResponse,
    summary="Funding Tenor Analysis",
)
async def funding_tenor_analysis(
    body: FundingTenorAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["funding_amounts"] = np.asarray(kwargs["funding_amounts"], dtype=np.float64)
    kwargs["tenors_days"] = np.asarray(kwargs["tenors_days"], dtype=np.float64)
    try:
        result: Any = _e_funding_tenor_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/liquidity_stress_scenario",
    response_model=LiquidityStressScenarioResponse,
    summary="Liquidity Stress Scenario",
)
async def liquidity_stress_scenario(
    body: LiquidityStressScenarioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["balances"] = np.asarray(kwargs["balances"], dtype=np.float64)
    kwargs["runoff_rates"] = np.asarray(kwargs["runoff_rates"], dtype=np.float64)
    try:
        result: Any = _e_liquidity_stress_scenario(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/idiosyncratic_stress_scenario",
    response_model=IdiosyncraticStressScenarioResponse,
    summary="Idiosyncratic Stress Scenario",
)
async def idiosyncratic_stress_scenario(
    body: IdiosyncraticStressScenarioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_idiosyncratic_stress_scenario(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/market_wide_stress_scenario",
    response_model=MarketWideStressScenarioResponse,
    summary="Market Wide Stress Scenario",
)
async def market_wide_stress_scenario(
    body: MarketWideStressScenarioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["hqla_by_level"] = np.asarray(kwargs["hqla_by_level"], dtype=np.float64)
    kwargs["market_haircuts"] = np.asarray(kwargs["market_haircuts"], dtype=np.float64)
    try:
        result: Any = _e_market_wide_stress_scenario(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/combined_stress_scenario",
    response_model=CombinedStressScenarioResponse,
    summary="Combined Stress Scenario",
)
async def combined_stress_scenario(
    body: CombinedStressScenarioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["hqla_by_level"] = np.asarray(kwargs["hqla_by_level"], dtype=np.float64)
    kwargs["market_haircuts"] = np.asarray(kwargs["market_haircuts"], dtype=np.float64)
    try:
        result: Any = _e_combined_stress_scenario(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/survival_horizon_calculator",
    response_model=SurvivalHorizonCalculatorResponse,
    summary="Survival Horizon Calculator",
)
async def survival_horizon_calculator(
    body: SurvivalHorizonCalculatorRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["daily_net_outflows"] = np.asarray(kwargs["daily_net_outflows"], dtype=np.float64)
    try:
        result: Any = _e_survival_horizon_calculator(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/intraday_liquidity_monitor",
    response_model=IntradayLiquidityMonitorResponse,
    summary="Intraday Liquidity Monitor",
)
async def intraday_liquidity_monitor(
    body: IntradayLiquidityMonitorRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["timestamps"] = np.asarray(kwargs["timestamps"], dtype=np.float64)
    kwargs["net_flows"] = np.asarray(kwargs["net_flows"], dtype=np.float64)
    try:
        result: Any = _e_intraday_liquidity_monitor(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/intraday_liquidity_stress_test",
    response_model=IntradayLiquidityStressTestResponse,
    summary="Intraday Liquidity Stress Test",
)
async def intraday_liquidity_stress_test(
    body: IntradayLiquidityStressTestRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["net_flows"] = np.asarray(kwargs["net_flows"], dtype=np.float64)
    try:
        result: Any = _e_intraday_liquidity_stress_test(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/ilaap_stress_testing_framework",
    response_model=IlaapStressTestingFrameworkResponse,
    summary="Ilaap Stress Testing Framework",
)
async def ilaap_stress_testing_framework(
    body: IlaapStressTestingFrameworkRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_ilaap_stress_testing_framework(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/liquidity_var_liqvar",
    response_model=LiquidityVarLiqvarResponse,
    summary="Liquidity Var Liqvar",
)
async def liquidity_var_liqvar(
    body: LiquidityVarLiqvarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    if body.n_simulations > user.max_simulations:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=(
                f"Your {user.tier!r} tier allows a maximum of "
                f"{user.max_simulations:,} simulations. "
                f"Requested: {body.n_simulations:,}."
            ),
        )
    kwargs = body.model_dump()
    try:
        result: Any = _e_liquidity_var_liqvar(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/liquidity_buffer_sizing",
    response_model=LiquidityBufferSizingResponse,
    summary="Liquidity Buffer Sizing",
)
async def liquidity_buffer_sizing(
    body: LiquidityBufferSizingRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["stressed_net_outflows"] = np.asarray(kwargs["stressed_net_outflows"], dtype=np.float64)
    try:
        result: Any = _e_liquidity_buffer_sizing(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/contingency_funding_plan_trigger",
    response_model=ContingencyFundingPlanTriggerResponse,
    summary="Contingency Funding Plan Trigger",
)
async def contingency_funding_plan_trigger(
    body: ContingencyFundingPlanTriggerRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_contingency_funding_plan_trigger(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/wholesale_funding_concentration",
    response_model=WholesaleFundingConcentrationResponse,
    summary="Wholesale Funding Concentration",
)
async def wholesale_funding_concentration(
    body: WholesaleFundingConcentrationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["counterparty_amounts"] = np.asarray(kwargs["counterparty_amounts"], dtype=np.float64)
    try:
        result: Any = _e_wholesale_funding_concentration(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/retail_deposit_runoff_rate",
    response_model=RetailDepositRunoffRateResponse,
    summary="Retail Deposit Runoff Rate",
)
async def retail_deposit_runoff_rate(
    body: RetailDepositRunoffRateRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["deposit_balances"] = np.asarray(kwargs["deposit_balances"], dtype=np.float64)
    kwargs["runoff_rates"] = np.asarray(kwargs["runoff_rates"], dtype=np.float64)
    try:
        result: Any = _e_retail_deposit_runoff_rate(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/secured_funding_rollover_risk",
    response_model=SecuredFundingRolloverRiskResponse,
    summary="Secured Funding Rollover Risk",
)
async def secured_funding_rollover_risk(
    body: SecuredFundingRolloverRiskRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["maturing_amounts"] = np.asarray(kwargs["maturing_amounts"], dtype=np.float64)
    kwargs["rollover_rates"] = np.asarray(kwargs["rollover_rates"], dtype=np.float64)
    try:
        result: Any = _e_secured_funding_rollover_risk(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/asset_encumbrance_ratio",
    response_model=AssetEncumbranceRatioResponse,
    summary="Asset Encumbrance Ratio",
)
async def asset_encumbrance_ratio(
    body: AssetEncumbranceRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_asset_encumbrance_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/collateral_availability_analysis",
    response_model=CollateralAvailabilityAnalysisResponse,
    summary="Collateral Availability Analysis",
)
async def collateral_availability_analysis(
    body: CollateralAvailabilityAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["collateral_values"] = np.asarray(kwargs["collateral_values"], dtype=np.float64)
    kwargs["haircuts"] = np.asarray(kwargs["haircuts"], dtype=np.float64)
    if kwargs["already_pledged"] is not None:
        kwargs["already_pledged"] = np.asarray(kwargs["already_pledged"], dtype=np.float64)
    try:
        result: Any = _e_collateral_availability_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/repo_market_stress_haircut",
    response_model=RepoMarketStressHaircutResponse,
    summary="Repo Market Stress Haircut",
)
async def repo_market_stress_haircut(
    body: RepoMarketStressHaircutRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["base_haircuts"] = np.asarray(kwargs["base_haircuts"], dtype=np.float64)
    kwargs["stress_multipliers"] = np.asarray(kwargs["stress_multipliers"], dtype=np.float64)
    kwargs["collateral_values"] = np.asarray(kwargs["collateral_values"], dtype=np.float64)
    try:
        result: Any = _e_repo_market_stress_haircut(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/fx_liquidity_risk_by_currency",
    response_model=FxLiquidityRiskByCurrencyResponse,
    summary="Fx Liquidity Risk By Currency",
)
async def fx_liquidity_risk_by_currency(
    body: FxLiquidityRiskByCurrencyRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_fx_liquidity_risk_by_currency(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/intragroup_liquidity_flow",
    response_model=IntragroupLiquidityFlowResponse,
    summary="Intragroup Liquidity Flow",
)
async def intragroup_liquidity_flow(
    body: IntragroupLiquidityFlowRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_intragroup_liquidity_flow(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/funding_cost_analysis",
    response_model=FundingCostAnalysisResponse,
    summary="Funding Cost Analysis",
)
async def funding_cost_analysis(
    body: FundingCostAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["funding_amounts"] = np.asarray(kwargs["funding_amounts"], dtype=np.float64)
    kwargs["funding_rates"] = np.asarray(kwargs["funding_rates"], dtype=np.float64)
    try:
        result: Any = _e_funding_cost_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/liquidity_transfer_pricing",
    response_model=LiquidityTransferPricingResponse,
    summary="Liquidity Transfer Pricing",
)
async def liquidity_transfer_pricing(
    body: LiquidityTransferPricingRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_liquidity_transfer_pricing(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/ilaap_internal_liquidity_metric",
    response_model=IlaapInternalLiquidityMetricResponse,
    summary="Ilaap Internal Liquidity Metric",
)
async def ilaap_internal_liquidity_metric(
    body: IlaapInternalLiquidityMetricRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_ilaap_internal_liquidity_metric(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/liquidity_risk_appetite_threshold",
    response_model=LiquidityRiskAppetiteThresholdResponse,
    summary="Liquidity Risk Appetite Threshold",
)
async def liquidity_risk_appetite_threshold(
    body: LiquidityRiskAppetiteThresholdRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_liquidity_risk_appetite_threshold(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/early_warning_indicator_liquidity",
    response_model=EarlyWarningIndicatorLiquidityResponse,
    summary="Early Warning Indicator Liquidity",
)
async def early_warning_indicator_liquidity(
    body: EarlyWarningIndicatorLiquidityRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_early_warning_indicator_liquidity(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/central_bank_facility_eligibility",
    response_model=CentralBankFacilityEligibilityResponse,
    summary="Central Bank Facility Eligibility",
)
async def central_bank_facility_eligibility(
    body: CentralBankFacilityEligibilityRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_ratings"] = np.asarray(kwargs["asset_ratings"], dtype=np.float64)
    kwargs["asset_values"] = np.asarray(kwargs["asset_values"], dtype=np.float64)
    kwargs["cb_haircuts"] = np.asarray(kwargs["cb_haircuts"], dtype=np.float64)
    try:
        result: Any = _e_central_bank_facility_eligibility(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/contingent_liquidity_risk",
    response_model=ContingentLiquidityRiskResponse,
    summary="Contingent Liquidity Risk",
)
async def contingent_liquidity_risk(
    body: ContingentLiquidityRiskRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["commitment_amounts"] = np.asarray(kwargs["commitment_amounts"], dtype=np.float64)
    kwargs["draw_probabilities"] = np.asarray(kwargs["draw_probabilities"], dtype=np.float64)
    if kwargs["ccf"] is not None:
        kwargs["ccf"] = np.asarray(kwargs["ccf"], dtype=np.float64)
    try:
        result: Any = _e_contingent_liquidity_risk(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/liquidity_scorecard_aggregation",
    response_model=LiquidityScorecardAggregationResponse,
    summary="Liquidity Scorecard Aggregation",
)
async def liquidity_scorecard_aggregation(
    body: LiquidityScorecardAggregationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["scores"] = np.asarray(kwargs["scores"], dtype=np.float64)
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    try:
        result: Any = _e_liquidity_scorecard_aggregation(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/deposit_stability_classification",
    response_model=DepositStabilityClassificationResponse,
    summary="Deposit Stability Classification",
)
async def deposit_stability_classification(
    body: DepositStabilityClassificationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["deposit_features"] = np.asarray(kwargs["deposit_features"], dtype=np.float64)
    try:
        result: Any = _e_deposit_stability_classification(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/cross_currency_liquidity_bridge",
    response_model=CrossCurrencyLiquidityBridgeResponse,
    summary="Cross Currency Liquidity Bridge",
)
async def cross_currency_liquidity_bridge(
    body: CrossCurrencyLiquidityBridgeRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_cross_currency_liquidity_bridge(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)
