"""api/routes/market_risk.py — auto-generated FastAPI routes for the market-risk domain.

Generated by scripts/gen_p3.py. Each route validates its request, converts
list payloads to NumPy arrays, calls the engine wrapper (the single source
of truth), and returns the result dict via OrjsonResponse. No business logic
lives here.
"""

from __future__ import annotations

import logging
from typing import Any

import numpy as np
from fastapi import APIRouter, Depends, HTTPException, status

from api.middleware.auth import TokenPayload, get_current_user
from api.responses import OrjsonResponse
from engine.backtesting import basel_capital_addon_multiplier as _e_basel_capital_addon_multiplier
from engine.backtesting import (
    christoffersen_independence_test as _e_christoffersen_independence_test,
)
from engine.backtesting import combined_backtesting as _e_combined_backtesting
from engine.backtesting import kupiec_pof_test as _e_kupiec_pof_test
from engine.backtesting import rolling_var_backtest as _e_rolling_var_backtest
from engine.backtesting import traffic_light_backtesting as _e_traffic_light_backtesting
from engine.backtesting import var_breach_cluster_analysis as _e_var_breach_cluster_analysis
from engine.expected_shortfall import conditional_var_es as _e_conditional_var_es
from engine.expected_shortfall import cvar_decomposition_euler as _e_cvar_decomposition_euler
from engine.expected_shortfall import (
    es_at_multiple_confidence_levels as _e_es_at_multiple_confidence_levels,
)
from engine.expected_shortfall import (
    expected_shortfall_contribution as _e_expected_shortfall_contribution,
)
from engine.expected_shortfall import (
    historical_expected_shortfall as _e_historical_expected_shortfall,
)
from engine.expected_shortfall import liquidity_adjusted_es as _e_liquidity_adjusted_es
from engine.expected_shortfall import (
    monte_carlo_expected_shortfall as _e_monte_carlo_expected_shortfall,
)
from engine.expected_shortfall import stressed_expected_shortfall as _e_stressed_expected_shortfall
from engine.frtb import extreme_value_theory_var as _e_extreme_value_theory_var
from engine.frtb import frtb_ima_aggregate_capital_charge as _e_frtb_ima_aggregate_capital_charge
from engine.frtb import frtb_ima_expected_shortfall as _e_frtb_ima_expected_shortfall
from engine.frtb import (
    frtb_ima_non_modellable_risk_factors as _e_frtb_ima_non_modellable_risk_factors,
)
from engine.frtb import frtb_ima_stressed_period_finder as _e_frtb_ima_stressed_period_finder
from engine.frtb import frtb_sa_default_risk_charge as _e_frtb_sa_default_risk_charge
from engine.frtb import frtb_sa_residual_risk_addon as _e_frtb_sa_residual_risk_addon
from engine.frtb import frtb_sa_sensitivity_based_method as _e_frtb_sa_sensitivity_based_method
from engine.frtb import spectral_risk_measure as _e_spectral_risk_measure
from engine.greeks import charm_delta_decay as _e_charm_delta_decay
from engine.greeks import cs01_credit_spread as _e_cs01_credit_spread
from engine.greeks import dv01_pv01_bucketed as _e_dv01_pv01_bucketed
from engine.greeks import gamma_cross_gamma_matrix as _e_gamma_cross_gamma_matrix
from engine.greeks import portfolio_delta_aggregated as _e_portfolio_delta_aggregated
from engine.greeks import rho_interest_rate as _e_rho_interest_rate
from engine.greeks import theta_time_decay as _e_theta_time_decay
from engine.greeks import vanna_delta_vega_cross as _e_vanna_delta_vega_cross
from engine.greeks import vega_surface_bucketed as _e_vega_surface_bucketed
from engine.greeks import volga_vega_convexity as _e_volga_vega_convexity
from engine.metrics import compute_breaches as _e_compute_breaches
from engine.metrics import compute_cvar as _e_compute_cvar
from engine.metrics import compute_loss_percentiles as _e_compute_loss_percentiles
from engine.metrics import compute_rolling_var as _e_compute_rolling_var
from engine.pnl_attribution import credit_pnl_attribution as _e_credit_pnl_attribution
from engine.pnl_attribution import fx_pnl_attribution as _e_fx_pnl_attribution
from engine.pnl_attribution import gamma_pnl_attribution as _e_gamma_pnl_attribution
from engine.pnl_attribution import greeks_based_pnl_explain as _e_greeks_based_pnl_explain
from engine.pnl_attribution import pnl_attribution_test_frtb_pat as _e_pnl_attribution_test_frtb_pat
from engine.pnl_attribution import rates_pnl_attribution as _e_rates_pnl_attribution
from engine.pnl_attribution import residual_pnl_unexplained as _e_residual_pnl_unexplained
from engine.pnl_attribution import theta_carry_attribution as _e_theta_carry_attribution
from engine.pnl_attribution import vega_pnl_attribution as _e_vega_pnl_attribution
from engine.stress import contagion_stress_scenario as _e_contagion_stress_scenario
from engine.stress import historical_scenario_replay as _e_historical_scenario_replay
from engine.stress import (
    hypothetical_multi_factor_scenario as _e_hypothetical_multi_factor_scenario,
)
from engine.stress import macro_scenario_generator as _e_macro_scenario_generator
from engine.stress import reverse_stress_testing as _e_reverse_stress_testing
from engine.stress import sector_stress_scenario as _e_sector_stress_scenario
from engine.stress import sensitivity_stress_profile as _e_sensitivity_stress_profile
from engine.var_models import component_var as _e_component_var
from engine.var_models import cornish_fisher_var as _e_cornish_fisher_var
from engine.var_models import (
    filtered_historical_simulation_var as _e_filtered_historical_simulation_var,
)
from engine.var_models import historical_simulation_var as _e_historical_simulation_var
from engine.var_models import incremental_var as _e_incremental_var
from engine.var_models import marginal_var as _e_marginal_var
from engine.var_models import parametric_delta_normal_var as _e_parametric_delta_normal_var
from engine.var_models import var_by_risk_factor as _e_var_by_risk_factor
from engine.var_models import var_fan_chart as _e_var_fan_chart
from engine.volatility import correlation_matrix_historical as _e_correlation_matrix_historical
from engine.volatility import dcc_garch_dynamic_correlation as _e_dcc_garch_dynamic_correlation
from engine.volatility import egarch_volatility_model as _e_egarch_volatility_model
from engine.volatility import garch_11_volatility_forecast as _e_garch_11_volatility_forecast
from engine.volatility import gjr_garch_asymmetric_model as _e_gjr_garch_asymmetric_model
from engine.volatility import realised_volatility as _e_realised_volatility
from engine.volatility import risk_factor_pca_decomposition as _e_risk_factor_pca_decomposition
from engine.volatility import volatility_surface_implied_vol as _e_volatility_surface_implied_vol
from schemas.market_risk import (
    BaselCapitalAddonMultiplierRequest,
    BaselCapitalAddonMultiplierResponse,
    CharmDeltaDecayRequest,
    CharmDeltaDecayResponse,
    ChristoffersenIndependenceTestRequest,
    ChristoffersenIndependenceTestResponse,
    CombinedBacktestingRequest,
    CombinedBacktestingResponse,
    ComponentVarRequest,
    ComponentVarResponse,
    ComputeBreachesRequest,
    ComputeBreachesResponse,
    ComputeCvarRequest,
    ComputeCvarResponse,
    ComputeLossPercentilesRequest,
    ComputeLossPercentilesResponse,
    ComputeRollingVarRequest,
    ComputeRollingVarResponse,
    ConditionalVarEsRequest,
    ConditionalVarEsResponse,
    ContagionStressScenarioRequest,
    ContagionStressScenarioResponse,
    CornishFisherVarRequest,
    CornishFisherVarResponse,
    CorrelationMatrixHistoricalRequest,
    CorrelationMatrixHistoricalResponse,
    CreditPnlAttributionRequest,
    CreditPnlAttributionResponse,
    Cs01CreditSpreadRequest,
    Cs01CreditSpreadResponse,
    CvarDecompositionEulerRequest,
    CvarDecompositionEulerResponse,
    DccGarchDynamicCorrelationRequest,
    DccGarchDynamicCorrelationResponse,
    Dv01Pv01BucketedRequest,
    Dv01Pv01BucketedResponse,
    EgarchVolatilityModelRequest,
    EgarchVolatilityModelResponse,
    EsAtMultipleConfidenceLevelsRequest,
    EsAtMultipleConfidenceLevelsResponse,
    ExpectedShortfallContributionRequest,
    ExpectedShortfallContributionResponse,
    ExtremeValueTheoryVarRequest,
    ExtremeValueTheoryVarResponse,
    FilteredHistoricalSimulationVarRequest,
    FilteredHistoricalSimulationVarResponse,
    FrtbImaAggregateCapitalChargeRequest,
    FrtbImaAggregateCapitalChargeResponse,
    FrtbImaExpectedShortfallRequest,
    FrtbImaExpectedShortfallResponse,
    FrtbImaNonModellableRiskFactorsRequest,
    FrtbImaNonModellableRiskFactorsResponse,
    FrtbImaStressedPeriodFinderRequest,
    FrtbImaStressedPeriodFinderResponse,
    FrtbSaDefaultRiskChargeRequest,
    FrtbSaDefaultRiskChargeResponse,
    FrtbSaResidualRiskAddonRequest,
    FrtbSaResidualRiskAddonResponse,
    FrtbSaSensitivityBasedMethodRequest,
    FrtbSaSensitivityBasedMethodResponse,
    FxPnlAttributionRequest,
    FxPnlAttributionResponse,
    GammaCrossGammaMatrixRequest,
    GammaCrossGammaMatrixResponse,
    GammaPnlAttributionRequest,
    GammaPnlAttributionResponse,
    Garch11VolatilityForecastRequest,
    Garch11VolatilityForecastResponse,
    GjrGarchAsymmetricModelRequest,
    GjrGarchAsymmetricModelResponse,
    GreeksBasedPnlExplainRequest,
    GreeksBasedPnlExplainResponse,
    HistoricalExpectedShortfallRequest,
    HistoricalExpectedShortfallResponse,
    HistoricalScenarioReplayRequest,
    HistoricalScenarioReplayResponse,
    HistoricalSimulationVarRequest,
    HistoricalSimulationVarResponse,
    HypotheticalMultiFactorScenarioRequest,
    HypotheticalMultiFactorScenarioResponse,
    IncrementalVarRequest,
    IncrementalVarResponse,
    KupiecPofTestRequest,
    KupiecPofTestResponse,
    LiquidityAdjustedEsRequest,
    LiquidityAdjustedEsResponse,
    MacroScenarioGeneratorRequest,
    MacroScenarioGeneratorResponse,
    MarginalVarRequest,
    MarginalVarResponse,
    MonteCarloExpectedShortfallRequest,
    MonteCarloExpectedShortfallResponse,
    ParametricDeltaNormalVarRequest,
    ParametricDeltaNormalVarResponse,
    PnlAttributionTestFrtbPatRequest,
    PnlAttributionTestFrtbPatResponse,
    PortfolioDeltaAggregatedRequest,
    PortfolioDeltaAggregatedResponse,
    RatesPnlAttributionRequest,
    RatesPnlAttributionResponse,
    RealisedVolatilityRequest,
    RealisedVolatilityResponse,
    ResidualPnlUnexplainedRequest,
    ResidualPnlUnexplainedResponse,
    ReverseStressTestingRequest,
    ReverseStressTestingResponse,
    RhoInterestRateRequest,
    RhoInterestRateResponse,
    RiskFactorPcaDecompositionRequest,
    RiskFactorPcaDecompositionResponse,
    RollingVarBacktestRequest,
    RollingVarBacktestResponse,
    SectorStressScenarioRequest,
    SectorStressScenarioResponse,
    SensitivityStressProfileRequest,
    SensitivityStressProfileResponse,
    SpectralRiskMeasureRequest,
    SpectralRiskMeasureResponse,
    StressedExpectedShortfallRequest,
    StressedExpectedShortfallResponse,
    ThetaCarryAttributionRequest,
    ThetaCarryAttributionResponse,
    ThetaTimeDecayRequest,
    ThetaTimeDecayResponse,
    TrafficLightBacktestingRequest,
    TrafficLightBacktestingResponse,
    VannaDeltaVegaCrossRequest,
    VannaDeltaVegaCrossResponse,
    VarBreachClusterAnalysisRequest,
    VarBreachClusterAnalysisResponse,
    VarByRiskFactorRequest,
    VarByRiskFactorResponse,
    VarFanChartRequest,
    VarFanChartResponse,
    VegaPnlAttributionRequest,
    VegaPnlAttributionResponse,
    VegaSurfaceBucketedRequest,
    VegaSurfaceBucketedResponse,
    VolatilitySurfaceImpliedVolRequest,
    VolatilitySurfaceImpliedVolResponse,
    VolgaVegaConvexityRequest,
    VolgaVegaConvexityResponse,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/market-risk", tags=["market-risk"])

# Engine input errors → HTTP 422. Explicit tuple (no bare except) covers
# bad numeric domains, singular matrices, and shape/key mismatches.
_INPUT_ERRORS = (
    ValueError,
    TypeError,
    KeyError,
    IndexError,
    ArithmeticError,
    AssertionError,
    np.linalg.LinAlgError,
)


@router.post(
    "/historical_simulation_var",
    response_model=HistoricalSimulationVarResponse,
    summary="Historical Simulation Var",
)
async def historical_simulation_var(
    body: HistoricalSimulationVarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_historical_simulation_var(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/filtered_historical_simulation_var",
    response_model=FilteredHistoricalSimulationVarResponse,
    summary="Filtered Historical Simulation Var",
)
async def filtered_historical_simulation_var(
    body: FilteredHistoricalSimulationVarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_filtered_historical_simulation_var(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/parametric_delta_normal_var",
    response_model=ParametricDeltaNormalVarResponse,
    summary="Parametric Delta Normal Var",
)
async def parametric_delta_normal_var(
    body: ParametricDeltaNormalVarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_parametric_delta_normal_var(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/cornish_fisher_var",
    response_model=CornishFisherVarResponse,
    summary="Cornish Fisher Var",
)
async def cornish_fisher_var(
    body: CornishFisherVarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_cornish_fisher_var(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/marginal_var",
    response_model=MarginalVarResponse,
    summary="Marginal Var",
)
async def marginal_var(
    body: MarginalVarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_marginal_var(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/component_var",
    response_model=ComponentVarResponse,
    summary="Component Var",
)
async def component_var(
    body: ComponentVarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_component_var(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/incremental_var",
    response_model=IncrementalVarResponse,
    summary="Incremental Var",
)
async def incremental_var(
    body: IncrementalVarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_incremental_var(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/var_by_risk_factor",
    response_model=VarByRiskFactorResponse,
    summary="Var By Risk Factor",
)
async def var_by_risk_factor(
    body: VarByRiskFactorRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["factor_exposures"] = np.asarray(kwargs["factor_exposures"], dtype=np.float64)
    kwargs["factor_cov"] = np.asarray(kwargs["factor_cov"], dtype=np.float64)
    try:
        result: Any = _e_var_by_risk_factor(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/var_fan_chart",
    response_model=VarFanChartResponse,
    summary="Var Fan Chart",
)
async def var_fan_chart(
    body: VarFanChartRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    kwargs["confidence_levels"] = tuple(kwargs["confidence_levels"])
    try:
        result: Any = _e_var_fan_chart(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/conditional_var_es",
    response_model=ConditionalVarEsResponse,
    summary="Conditional Var Es",
)
async def conditional_var_es(
    body: ConditionalVarEsRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_conditional_var_es(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/historical_expected_shortfall",
    response_model=HistoricalExpectedShortfallResponse,
    summary="Historical Expected Shortfall",
)
async def historical_expected_shortfall(
    body: HistoricalExpectedShortfallRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_historical_expected_shortfall(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/monte_carlo_expected_shortfall",
    response_model=MonteCarloExpectedShortfallResponse,
    summary="Monte Carlo Expected Shortfall",
)
async def monte_carlo_expected_shortfall(
    body: MonteCarloExpectedShortfallRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    if body.n_simulations > user.max_simulations:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=(
                f"Your {user.tier!r} tier allows a maximum of "
                f"{user.max_simulations:,} simulations. "
                f"Requested: {body.n_simulations:,}."
            ),
        )
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_monte_carlo_expected_shortfall(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/cvar_decomposition_euler",
    response_model=CvarDecompositionEulerResponse,
    summary="Cvar Decomposition Euler",
)
async def cvar_decomposition_euler(
    body: CvarDecompositionEulerRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_cvar_decomposition_euler(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/stressed_expected_shortfall",
    response_model=StressedExpectedShortfallResponse,
    summary="Stressed Expected Shortfall",
)
async def stressed_expected_shortfall(
    body: StressedExpectedShortfallRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_stressed_expected_shortfall(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/liquidity_adjusted_es",
    response_model=LiquidityAdjustedEsResponse,
    summary="Liquidity Adjusted Es",
)
async def liquidity_adjusted_es(
    body: LiquidityAdjustedEsRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_liquidity_adjusted_es(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/es_at_multiple_confidence_levels",
    response_model=EsAtMultipleConfidenceLevelsResponse,
    summary="Es At Multiple Confidence Levels",
)
async def es_at_multiple_confidence_levels(
    body: EsAtMultipleConfidenceLevelsRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    kwargs["confidence_levels"] = tuple(kwargs["confidence_levels"])
    try:
        result: Any = _e_es_at_multiple_confidence_levels(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/expected_shortfall_contribution",
    response_model=ExpectedShortfallContributionResponse,
    summary="Expected Shortfall Contribution",
)
async def expected_shortfall_contribution(
    body: ExpectedShortfallContributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_returns"] = np.asarray(kwargs["asset_returns"], dtype=np.float64)
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    try:
        result: Any = _e_expected_shortfall_contribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/historical_scenario_replay",
    response_model=HistoricalScenarioReplayResponse,
    summary="Historical Scenario Replay",
)
async def historical_scenario_replay(
    body: HistoricalScenarioReplayRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["exposures"] = np.asarray(kwargs["exposures"], dtype=np.float64)
    kwargs["historical_factor_returns"] = np.asarray(
        kwargs["historical_factor_returns"], dtype=np.float64
    )
    try:
        result: Any = _e_historical_scenario_replay(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/hypothetical_multi_factor_scenario",
    response_model=HypotheticalMultiFactorScenarioResponse,
    summary="Hypothetical Multi Factor Scenario",
)
async def hypothetical_multi_factor_scenario(
    body: HypotheticalMultiFactorScenarioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["exposures"] = np.asarray(kwargs["exposures"], dtype=np.float64)
    kwargs["shocks"] = np.asarray(kwargs["shocks"], dtype=np.float64)
    try:
        result: Any = _e_hypothetical_multi_factor_scenario(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/reverse_stress_testing",
    response_model=ReverseStressTestingResponse,
    summary="Reverse Stress Testing",
)
async def reverse_stress_testing(
    body: ReverseStressTestingRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["exposures"] = np.asarray(kwargs["exposures"], dtype=np.float64)
    kwargs["factor_cov"] = np.asarray(kwargs["factor_cov"], dtype=np.float64)
    try:
        result: Any = _e_reverse_stress_testing(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/sensitivity_stress_profile",
    response_model=SensitivityStressProfileResponse,
    summary="Sensitivity Stress Profile",
)
async def sensitivity_stress_profile(
    body: SensitivityStressProfileRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["exposures"] = np.asarray(kwargs["exposures"], dtype=np.float64)
    kwargs["shock_grid"] = np.asarray(kwargs["shock_grid"], dtype=np.float64)
    try:
        result: Any = _e_sensitivity_stress_profile(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/sector_stress_scenario",
    response_model=SectorStressScenarioResponse,
    summary="Sector Stress Scenario",
)
async def sector_stress_scenario(
    body: SectorStressScenarioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["sector_exposures"] = np.asarray(kwargs["sector_exposures"], dtype=np.float64)
    kwargs["sector_shocks"] = np.asarray(kwargs["sector_shocks"], dtype=np.float64)
    try:
        result: Any = _e_sector_stress_scenario(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/macro_scenario_generator",
    response_model=MacroScenarioGeneratorResponse,
    summary="Macro Scenario Generator",
)
async def macro_scenario_generator(
    body: MacroScenarioGeneratorRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["factor_cov"] = np.asarray(kwargs["factor_cov"], dtype=np.float64)
    try:
        result: Any = _e_macro_scenario_generator(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/contagion_stress_scenario",
    response_model=ContagionStressScenarioResponse,
    summary="Contagion Stress Scenario",
)
async def contagion_stress_scenario(
    body: ContagionStressScenarioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["initial_shock"] = np.asarray(kwargs["initial_shock"], dtype=np.float64)
    kwargs["contagion_matrix"] = np.asarray(kwargs["contagion_matrix"], dtype=np.float64)
    try:
        result: Any = _e_contagion_stress_scenario(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/portfolio_delta_aggregated",
    response_model=PortfolioDeltaAggregatedResponse,
    summary="Portfolio Delta Aggregated",
)
async def portfolio_delta_aggregated(
    body: PortfolioDeltaAggregatedRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["deltas"] = np.asarray(kwargs["deltas"], dtype=np.float64)
    kwargs["quantities"] = np.asarray(kwargs["quantities"], dtype=np.float64)
    if kwargs["spot_prices"] is not None:
        kwargs["spot_prices"] = np.asarray(kwargs["spot_prices"], dtype=np.float64)
    try:
        result: Any = _e_portfolio_delta_aggregated(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/gamma_cross_gamma_matrix",
    response_model=GammaCrossGammaMatrixResponse,
    summary="Gamma Cross Gamma Matrix",
)
async def gamma_cross_gamma_matrix(
    body: GammaCrossGammaMatrixRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["own_gammas"] = np.asarray(kwargs["own_gammas"], dtype=np.float64)
    if kwargs["cross_gammas"] is not None:
        kwargs["cross_gammas"] = np.asarray(kwargs["cross_gammas"], dtype=np.float64)
    try:
        result: Any = _e_gamma_cross_gamma_matrix(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/vega_surface_bucketed",
    response_model=VegaSurfaceBucketedResponse,
    summary="Vega Surface Bucketed",
)
async def vega_surface_bucketed(
    body: VegaSurfaceBucketedRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["vegas"] = np.asarray(kwargs["vegas"], dtype=np.float64)
    kwargs["expiry_buckets"] = np.asarray(kwargs["expiry_buckets"], dtype=np.float64)
    kwargs["strike_buckets"] = np.asarray(kwargs["strike_buckets"], dtype=np.float64)
    try:
        result: Any = _e_vega_surface_bucketed(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/dv01_pv01_bucketed",
    response_model=Dv01Pv01BucketedResponse,
    summary="Dv01 Pv01 Bucketed",
)
async def dv01_pv01_bucketed(
    body: Dv01Pv01BucketedRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["cashflows"] = np.asarray(kwargs["cashflows"], dtype=np.float64)
    kwargs["times"] = np.asarray(kwargs["times"], dtype=np.float64)
    kwargs["bucket_indices"] = np.asarray(kwargs["bucket_indices"], dtype=np.float64)
    try:
        result: Any = _e_dv01_pv01_bucketed(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/cs01_credit_spread",
    response_model=Cs01CreditSpreadResponse,
    summary="Cs01 Credit Spread",
)
async def cs01_credit_spread(
    body: Cs01CreditSpreadRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["cashflows"] = np.asarray(kwargs["cashflows"], dtype=np.float64)
    kwargs["times"] = np.asarray(kwargs["times"], dtype=np.float64)
    try:
        result: Any = _e_cs01_credit_spread(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/rho_interest_rate",
    response_model=RhoInterestRateResponse,
    summary="Rho Interest Rate",
)
async def rho_interest_rate(
    body: RhoInterestRateRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_rho_interest_rate(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/theta_time_decay",
    response_model=ThetaTimeDecayResponse,
    summary="Theta Time Decay",
)
async def theta_time_decay(
    body: ThetaTimeDecayRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_theta_time_decay(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/charm_delta_decay",
    response_model=CharmDeltaDecayResponse,
    summary="Charm Delta Decay",
)
async def charm_delta_decay(
    body: CharmDeltaDecayRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_charm_delta_decay(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/volga_vega_convexity",
    response_model=VolgaVegaConvexityResponse,
    summary="Volga Vega Convexity",
)
async def volga_vega_convexity(
    body: VolgaVegaConvexityRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_volga_vega_convexity(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/vanna_delta_vega_cross",
    response_model=VannaDeltaVegaCrossResponse,
    summary="Vanna Delta Vega Cross",
)
async def vanna_delta_vega_cross(
    body: VannaDeltaVegaCrossRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_vanna_delta_vega_cross(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/greeks_based_pnl_explain",
    response_model=GreeksBasedPnlExplainResponse,
    summary="Greeks Based Pnl Explain",
)
async def greeks_based_pnl_explain(
    body: GreeksBasedPnlExplainRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_greeks_based_pnl_explain(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/pnl_attribution_test_frtb_pat",
    response_model=PnlAttributionTestFrtbPatResponse,
    summary="Pnl Attribution Test Frtb Pat",
)
async def pnl_attribution_test_frtb_pat(
    body: PnlAttributionTestFrtbPatRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["risk_theoretical_pnl"] = np.asarray(kwargs["risk_theoretical_pnl"], dtype=np.float64)
    kwargs["hypothetical_pnl"] = np.asarray(kwargs["hypothetical_pnl"], dtype=np.float64)
    try:
        result: Any = _e_pnl_attribution_test_frtb_pat(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/theta_carry_attribution",
    response_model=ThetaCarryAttributionResponse,
    summary="Theta Carry Attribution",
)
async def theta_carry_attribution(
    body: ThetaCarryAttributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_theta_carry_attribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/gamma_pnl_attribution",
    response_model=GammaPnlAttributionResponse,
    summary="Gamma Pnl Attribution",
)
async def gamma_pnl_attribution(
    body: GammaPnlAttributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_gamma_pnl_attribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/vega_pnl_attribution",
    response_model=VegaPnlAttributionResponse,
    summary="Vega Pnl Attribution",
)
async def vega_pnl_attribution(
    body: VegaPnlAttributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_vega_pnl_attribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/fx_pnl_attribution",
    response_model=FxPnlAttributionResponse,
    summary="Fx Pnl Attribution",
)
async def fx_pnl_attribution(
    body: FxPnlAttributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["fx_deltas"] = np.asarray(kwargs["fx_deltas"], dtype=np.float64)
    kwargs["fx_moves"] = np.asarray(kwargs["fx_moves"], dtype=np.float64)
    try:
        result: Any = _e_fx_pnl_attribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/rates_pnl_attribution",
    response_model=RatesPnlAttributionResponse,
    summary="Rates Pnl Attribution",
)
async def rates_pnl_attribution(
    body: RatesPnlAttributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["key_rate_sensitivities"] = np.asarray(
        kwargs["key_rate_sensitivities"], dtype=np.float64
    )
    kwargs["yield_moves_bp"] = np.asarray(kwargs["yield_moves_bp"], dtype=np.float64)
    try:
        result: Any = _e_rates_pnl_attribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/credit_pnl_attribution",
    response_model=CreditPnlAttributionResponse,
    summary="Credit Pnl Attribution",
)
async def credit_pnl_attribution(
    body: CreditPnlAttributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["cs01_sensitivities"] = np.asarray(kwargs["cs01_sensitivities"], dtype=np.float64)
    kwargs["spread_moves_bp"] = np.asarray(kwargs["spread_moves_bp"], dtype=np.float64)
    try:
        result: Any = _e_credit_pnl_attribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/residual_pnl_unexplained",
    response_model=ResidualPnlUnexplainedResponse,
    summary="Residual Pnl Unexplained",
)
async def residual_pnl_unexplained(
    body: ResidualPnlUnexplainedRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["explained_components"] = np.asarray(kwargs["explained_components"], dtype=np.float64)
    try:
        result: Any = _e_residual_pnl_unexplained(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/traffic_light_backtesting",
    response_model=TrafficLightBacktestingResponse,
    summary="Traffic Light Backtesting",
)
async def traffic_light_backtesting(
    body: TrafficLightBacktestingRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["actual_returns"] = np.asarray(kwargs["actual_returns"], dtype=np.float64)
    kwargs["var_estimates"] = np.asarray(kwargs["var_estimates"], dtype=np.float64)
    try:
        result: Any = _e_traffic_light_backtesting(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/kupiec_pof_test",
    response_model=KupiecPofTestResponse,
    summary="Kupiec Pof Test",
)
async def kupiec_pof_test(
    body: KupiecPofTestRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_kupiec_pof_test(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/christoffersen_independence_test",
    response_model=ChristoffersenIndependenceTestResponse,
    summary="Christoffersen Independence Test",
)
async def christoffersen_independence_test(
    body: ChristoffersenIndependenceTestRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["breaches"] = np.asarray(kwargs["breaches"], dtype=np.float64)
    try:
        result: Any = _e_christoffersen_independence_test(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/combined_backtesting",
    response_model=CombinedBacktestingResponse,
    summary="Combined Backtesting",
)
async def combined_backtesting(
    body: CombinedBacktestingRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["breaches"] = np.asarray(kwargs["breaches"], dtype=np.float64)
    try:
        result: Any = _e_combined_backtesting(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/basel_capital_addon_multiplier",
    response_model=BaselCapitalAddonMultiplierResponse,
    summary="Basel Capital Addon Multiplier",
)
async def basel_capital_addon_multiplier(
    body: BaselCapitalAddonMultiplierRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_basel_capital_addon_multiplier(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/rolling_var_backtest",
    response_model=RollingVarBacktestResponse,
    summary="Rolling Var Backtest",
)
async def rolling_var_backtest(
    body: RollingVarBacktestRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_rolling_var_backtest(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/var_breach_cluster_analysis",
    response_model=VarBreachClusterAnalysisResponse,
    summary="Var Breach Cluster Analysis",
)
async def var_breach_cluster_analysis(
    body: VarBreachClusterAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["breaches"] = np.asarray(kwargs["breaches"], dtype=np.float64)
    try:
        result: Any = _e_var_breach_cluster_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/volatility_surface_implied_vol",
    response_model=VolatilitySurfaceImpliedVolResponse,
    summary="Volatility Surface Implied Vol",
)
async def volatility_surface_implied_vol(
    body: VolatilitySurfaceImpliedVolRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["market_prices"] = np.asarray(kwargs["market_prices"], dtype=np.float64)
    kwargs["strikes"] = np.asarray(kwargs["strikes"], dtype=np.float64)
    kwargs["expiries"] = np.asarray(kwargs["expiries"], dtype=np.float64)
    try:
        result: Any = _e_volatility_surface_implied_vol(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/garch_11_volatility_forecast",
    response_model=Garch11VolatilityForecastResponse,
    summary="Garch 11 Volatility Forecast",
)
async def garch_11_volatility_forecast(
    body: Garch11VolatilityForecastRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_garch_11_volatility_forecast(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/egarch_volatility_model",
    response_model=EgarchVolatilityModelResponse,
    summary="Egarch Volatility Model",
)
async def egarch_volatility_model(
    body: EgarchVolatilityModelRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_egarch_volatility_model(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/gjr_garch_asymmetric_model",
    response_model=GjrGarchAsymmetricModelResponse,
    summary="Gjr Garch Asymmetric Model",
)
async def gjr_garch_asymmetric_model(
    body: GjrGarchAsymmetricModelRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_gjr_garch_asymmetric_model(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/realised_volatility",
    response_model=RealisedVolatilityResponse,
    summary="Realised Volatility",
)
async def realised_volatility(
    body: RealisedVolatilityRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_realised_volatility(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/correlation_matrix_historical",
    response_model=CorrelationMatrixHistoricalResponse,
    summary="Correlation Matrix Historical",
)
async def correlation_matrix_historical(
    body: CorrelationMatrixHistoricalRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns_matrix"] = np.asarray(kwargs["returns_matrix"], dtype=np.float64)
    try:
        result: Any = _e_correlation_matrix_historical(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/dcc_garch_dynamic_correlation",
    response_model=DccGarchDynamicCorrelationResponse,
    summary="Dcc Garch Dynamic Correlation",
)
async def dcc_garch_dynamic_correlation(
    body: DccGarchDynamicCorrelationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns_matrix"] = np.asarray(kwargs["returns_matrix"], dtype=np.float64)
    try:
        result: Any = _e_dcc_garch_dynamic_correlation(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/risk_factor_pca_decomposition",
    response_model=RiskFactorPcaDecompositionResponse,
    summary="Risk Factor Pca Decomposition",
)
async def risk_factor_pca_decomposition(
    body: RiskFactorPcaDecompositionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns_matrix"] = np.asarray(kwargs["returns_matrix"], dtype=np.float64)
    try:
        result: Any = _e_risk_factor_pca_decomposition(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_sa_sensitivity_based_method",
    response_model=FrtbSaSensitivityBasedMethodResponse,
    summary="Frtb Sa Sensitivity Based Method",
)
async def frtb_sa_sensitivity_based_method(
    body: FrtbSaSensitivityBasedMethodRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_frtb_sa_sensitivity_based_method(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_sa_default_risk_charge",
    response_model=FrtbSaDefaultRiskChargeResponse,
    summary="Frtb Sa Default Risk Charge",
)
async def frtb_sa_default_risk_charge(
    body: FrtbSaDefaultRiskChargeRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["jtd_long"] = np.asarray(kwargs["jtd_long"], dtype=np.float64)
    kwargs["jtd_short"] = np.asarray(kwargs["jtd_short"], dtype=np.float64)
    kwargs["risk_weights"] = np.asarray(kwargs["risk_weights"], dtype=np.float64)
    try:
        result: Any = _e_frtb_sa_default_risk_charge(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_sa_residual_risk_addon",
    response_model=FrtbSaResidualRiskAddonResponse,
    summary="Frtb Sa Residual Risk Addon",
)
async def frtb_sa_residual_risk_addon(
    body: FrtbSaResidualRiskAddonRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["notionals"] = np.asarray(kwargs["notionals"], dtype=np.float64)
    kwargs["rrao_weights"] = np.asarray(kwargs["rrao_weights"], dtype=np.float64)
    try:
        result: Any = _e_frtb_sa_residual_risk_addon(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_ima_expected_shortfall",
    response_model=FrtbImaExpectedShortfallResponse,
    summary="Frtb Ima Expected Shortfall",
)
async def frtb_ima_expected_shortfall(
    body: FrtbImaExpectedShortfallRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_frtb_ima_expected_shortfall(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_ima_stressed_period_finder",
    response_model=FrtbImaStressedPeriodFinderResponse,
    summary="Frtb Ima Stressed Period Finder",
)
async def frtb_ima_stressed_period_finder(
    body: FrtbImaStressedPeriodFinderRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_frtb_ima_stressed_period_finder(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_ima_non_modellable_risk_factors",
    response_model=FrtbImaNonModellableRiskFactorsResponse,
    summary="Frtb Ima Non Modellable Risk Factors",
)
async def frtb_ima_non_modellable_risk_factors(
    body: FrtbImaNonModellableRiskFactorsRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["individual_ses"] = np.asarray(kwargs["individual_ses"], dtype=np.float64)
    try:
        result: Any = _e_frtb_ima_non_modellable_risk_factors(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_ima_aggregate_capital_charge",
    response_model=FrtbImaAggregateCapitalChargeResponse,
    summary="Frtb Ima Aggregate Capital Charge",
)
async def frtb_ima_aggregate_capital_charge(
    body: FrtbImaAggregateCapitalChargeRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_frtb_ima_aggregate_capital_charge(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/extreme_value_theory_var",
    response_model=ExtremeValueTheoryVarResponse,
    summary="Extreme Value Theory Var",
)
async def extreme_value_theory_var(
    body: ExtremeValueTheoryVarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_extreme_value_theory_var(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/spectral_risk_measure",
    response_model=SpectralRiskMeasureResponse,
    summary="Spectral Risk Measure",
)
async def spectral_risk_measure(
    body: SpectralRiskMeasureRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_spectral_risk_measure(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/compute_cvar",
    response_model=ComputeCvarResponse,
    summary="Compute Cvar",
)
async def compute_cvar(
    body: ComputeCvarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["sorted_losses"] = np.asarray(kwargs["sorted_losses"], dtype=np.float64)
    try:
        result: Any = _e_compute_cvar(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/compute_loss_percentiles",
    response_model=ComputeLossPercentilesResponse,
    summary="Compute Loss Percentiles",
)
async def compute_loss_percentiles(
    body: ComputeLossPercentilesRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["sorted_losses"] = np.asarray(kwargs["sorted_losses"], dtype=np.float64)
    try:
        result: Any = _e_compute_loss_percentiles(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/compute_rolling_var",
    response_model=ComputeRollingVarResponse,
    summary="Compute Rolling Var",
)
async def compute_rolling_var(
    body: ComputeRollingVarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_compute_rolling_var(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/compute_breaches",
    response_model=ComputeBreachesResponse,
    summary="Compute Breaches",
)
async def compute_breaches(
    body: ComputeBreachesRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["actual_returns"] = np.asarray(kwargs["actual_returns"], dtype=np.float64)
    kwargs["var_estimates"] = np.asarray(kwargs["var_estimates"], dtype=np.float64)
    try:
        result: Any = _e_compute_breaches(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)
