"""api/routes/portfolio.py — auto-generated FastAPI routes for the portfolio domain.

Generated by scripts/gen_p3.py. Each route validates its request, converts
list payloads to NumPy arrays, calls the engine wrapper (the single source
of truth), and returns the result dict via OrjsonResponse. No business logic
lives here.
"""

from __future__ import annotations

import logging
from typing import Any

import numpy as np
from fastapi import APIRouter, Depends, HTTPException, status

from api.middleware.auth import TokenPayload, get_current_user
from api.responses import OrjsonResponse
from engine.portfolio_attribution import currency_attribution as _e_currency_attribution
from engine.portfolio_attribution import (
    factor_exposure_analysis_barra as _e_factor_exposure_analysis_barra,
)
from engine.portfolio_attribution import factor_return_attribution as _e_factor_return_attribution
from engine.portfolio_attribution import gics_sector_exposure as _e_gics_sector_exposure
from engine.portfolio_attribution import return_attribution_brinson as _e_return_attribution_brinson
from engine.portfolio_attribution import sector_attribution as _e_sector_attribution
from engine.portfolio_drawdown import average_drawdown as _e_average_drawdown
from engine.portfolio_drawdown import (
    conditional_drawdown_at_risk as _e_conditional_drawdown_at_risk,
)
from engine.portfolio_drawdown import drawdown_duration as _e_drawdown_duration
from engine.portfolio_drawdown import maximum_drawdown as _e_maximum_drawdown
from engine.portfolio_esg import carbon_footprint_attribution as _e_carbon_footprint_attribution
from engine.portfolio_esg import esg_score_integration as _e_esg_score_integration
from engine.portfolio_esg import rebalancing_optimiser as _e_rebalancing_optimiser
from engine.portfolio_factor import carhart_4_factor_model as _e_carhart_4_factor_model
from engine.portfolio_factor import correlation_clustering as _e_correlation_clustering
from engine.portfolio_factor import fama_french_3_factor_model as _e_fama_french_3_factor_model
from engine.portfolio_factor import fama_french_5_factor_model as _e_fama_french_5_factor_model
from engine.portfolio_factor import principal_component_analysis as _e_principal_component_analysis
from engine.portfolio_factor import regime_detection_hmm as _e_regime_detection_hmm
from engine.portfolio_optimisation import black_litterman_model as _e_black_litterman_model
from engine.portfolio_optimisation import (
    cvar_constrained_optimisation as _e_cvar_constrained_optimisation,
)
from engine.portfolio_optimisation import equal_weight_portfolio as _e_equal_weight_portfolio
from engine.portfolio_optimisation import factor_based_optimisation as _e_factor_based_optimisation
from engine.portfolio_optimisation import (
    maximum_sharpe_ratio_portfolio as _e_maximum_sharpe_ratio_portfolio,
)
from engine.portfolio_optimisation import (
    mean_variance_optimisation as _e_mean_variance_optimisation,
)
from engine.portfolio_optimisation import (
    minimum_variance_portfolio as _e_minimum_variance_portfolio,
)
from engine.portfolio_optimisation import (
    resampled_efficient_frontier as _e_resampled_efficient_frontier,
)
from engine.portfolio_optimisation import risk_parity_portfolio as _e_risk_parity_portfolio
from engine.portfolio_optimisation import (
    robust_portfolio_optimisation as _e_robust_portfolio_optimisation,
)
from engine.portfolio_ratios import calmar_ratio as _e_calmar_ratio
from engine.portfolio_ratios import information_ratio as _e_information_ratio
from engine.portfolio_ratios import jensens_alpha as _e_jensens_alpha
from engine.portfolio_ratios import omega_ratio as _e_omega_ratio
from engine.portfolio_ratios import sharpe_ratio as _e_sharpe_ratio
from engine.portfolio_ratios import sortino_ratio as _e_sortino_ratio
from engine.portfolio_ratios import tail_ratio as _e_tail_ratio
from engine.portfolio_ratios import treynor_ratio as _e_treynor_ratio
from engine.portfolio_ratios import ulcer_index as _e_ulcer_index
from engine.portfolio_risk import active_share as _e_active_share
from engine.portfolio_risk import concentration_risk_hhi as _e_concentration_risk_hhi
from engine.portfolio_risk import correlation_matrix_portfolio as _e_correlation_matrix_portfolio
from engine.portfolio_risk import diversification_ratio as _e_diversification_ratio
from engine.portfolio_risk import (
    liquidity_adjusted_portfolio_var as _e_liquidity_adjusted_portfolio_var,
)
from engine.portfolio_risk import marginal_contribution_to_risk as _e_marginal_contribution_to_risk
from engine.portfolio_risk import (
    monte_carlo_portfolio_simulation as _e_monte_carlo_portfolio_simulation,
)
from engine.portfolio_risk import portfolio_beta as _e_portfolio_beta
from engine.portfolio_risk import portfolio_turnover as _e_portfolio_turnover
from engine.portfolio_risk import residual_risk as _e_residual_risk
from engine.portfolio_risk import tracking_error as _e_tracking_error
from engine.portfolio_risk import transaction_cost_analysis as _e_transaction_cost_analysis
from schemas.portfolio import (
    ActiveShareRequest,
    ActiveShareResponse,
    AverageDrawdownRequest,
    AverageDrawdownResponse,
    BlackLittermanModelRequest,
    BlackLittermanModelResponse,
    CalmarRatioRequest,
    CalmarRatioResponse,
    CarbonFootprintAttributionRequest,
    CarbonFootprintAttributionResponse,
    Carhart4FactorModelRequest,
    Carhart4FactorModelResponse,
    ConcentrationRiskHhiRequest,
    ConcentrationRiskHhiResponse,
    ConditionalDrawdownAtRiskRequest,
    ConditionalDrawdownAtRiskResponse,
    CorrelationClusteringRequest,
    CorrelationClusteringResponse,
    CorrelationMatrixPortfolioRequest,
    CorrelationMatrixPortfolioResponse,
    CurrencyAttributionRequest,
    CurrencyAttributionResponse,
    CvarConstrainedOptimisationRequest,
    CvarConstrainedOptimisationResponse,
    DiversificationRatioRequest,
    DiversificationRatioResponse,
    DrawdownDurationRequest,
    DrawdownDurationResponse,
    EqualWeightPortfolioRequest,
    EqualWeightPortfolioResponse,
    EsgScoreIntegrationRequest,
    EsgScoreIntegrationResponse,
    FactorBasedOptimisationRequest,
    FactorBasedOptimisationResponse,
    FactorExposureAnalysisBarraRequest,
    FactorExposureAnalysisBarraResponse,
    FactorReturnAttributionRequest,
    FactorReturnAttributionResponse,
    FamaFrench3FactorModelRequest,
    FamaFrench3FactorModelResponse,
    FamaFrench5FactorModelRequest,
    FamaFrench5FactorModelResponse,
    GicsSectorExposureRequest,
    GicsSectorExposureResponse,
    InformationRatioRequest,
    InformationRatioResponse,
    JensensAlphaRequest,
    JensensAlphaResponse,
    LiquidityAdjustedPortfolioVarRequest,
    LiquidityAdjustedPortfolioVarResponse,
    MarginalContributionToRiskRequest,
    MarginalContributionToRiskResponse,
    MaximumDrawdownRequest,
    MaximumDrawdownResponse,
    MaximumSharpeRatioPortfolioRequest,
    MaximumSharpeRatioPortfolioResponse,
    MeanVarianceOptimisationRequest,
    MeanVarianceOptimisationResponse,
    MinimumVariancePortfolioRequest,
    MinimumVariancePortfolioResponse,
    MonteCarloPortfolioSimulationRequest,
    MonteCarloPortfolioSimulationResponse,
    OmegaRatioRequest,
    OmegaRatioResponse,
    PortfolioBetaRequest,
    PortfolioBetaResponse,
    PortfolioTurnoverRequest,
    PortfolioTurnoverResponse,
    PrincipalComponentAnalysisRequest,
    PrincipalComponentAnalysisResponse,
    RebalancingOptimiserRequest,
    RebalancingOptimiserResponse,
    RegimeDetectionHmmRequest,
    RegimeDetectionHmmResponse,
    ResampledEfficientFrontierRequest,
    ResampledEfficientFrontierResponse,
    ResidualRiskRequest,
    ResidualRiskResponse,
    ReturnAttributionBrinsonRequest,
    ReturnAttributionBrinsonResponse,
    RiskParityPortfolioRequest,
    RiskParityPortfolioResponse,
    RobustPortfolioOptimisationRequest,
    RobustPortfolioOptimisationResponse,
    SectorAttributionRequest,
    SectorAttributionResponse,
    SharpeRatioRequest,
    SharpeRatioResponse,
    SortinoRatioRequest,
    SortinoRatioResponse,
    TailRatioRequest,
    TailRatioResponse,
    TrackingErrorRequest,
    TrackingErrorResponse,
    TransactionCostAnalysisRequest,
    TransactionCostAnalysisResponse,
    TreynorRatioRequest,
    TreynorRatioResponse,
    UlcerIndexRequest,
    UlcerIndexResponse,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/portfolio", tags=["portfolio"])

# Engine input errors → HTTP 422. Explicit tuple (no bare except) covers
# bad numeric domains, singular matrices, and shape/key mismatches.
_INPUT_ERRORS = (
    ValueError,
    TypeError,
    KeyError,
    IndexError,
    ArithmeticError,
    AssertionError,
    np.linalg.LinAlgError,
)


@router.post(
    "/mean_variance_optimisation",
    response_model=MeanVarianceOptimisationResponse,
    summary="Mean Variance Optimisation",
)
async def mean_variance_optimisation(
    body: MeanVarianceOptimisationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["mean_returns"] = np.asarray(kwargs["mean_returns"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_mean_variance_optimisation(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/minimum_variance_portfolio",
    response_model=MinimumVariancePortfolioResponse,
    summary="Minimum Variance Portfolio",
)
async def minimum_variance_portfolio(
    body: MinimumVariancePortfolioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    if kwargs["mean_returns"] is not None:
        kwargs["mean_returns"] = np.asarray(kwargs["mean_returns"], dtype=np.float64)
    try:
        result: Any = _e_minimum_variance_portfolio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/maximum_sharpe_ratio_portfolio",
    response_model=MaximumSharpeRatioPortfolioResponse,
    summary="Maximum Sharpe Ratio Portfolio",
)
async def maximum_sharpe_ratio_portfolio(
    body: MaximumSharpeRatioPortfolioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["mean_returns"] = np.asarray(kwargs["mean_returns"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_maximum_sharpe_ratio_portfolio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/risk_parity_portfolio",
    response_model=RiskParityPortfolioResponse,
    summary="Risk Parity Portfolio",
)
async def risk_parity_portfolio(
    body: RiskParityPortfolioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    if kwargs["mean_returns"] is not None:
        kwargs["mean_returns"] = np.asarray(kwargs["mean_returns"], dtype=np.float64)
    try:
        result: Any = _e_risk_parity_portfolio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/equal_weight_portfolio",
    response_model=EqualWeightPortfolioResponse,
    summary="Equal Weight Portfolio",
)
async def equal_weight_portfolio(
    body: EqualWeightPortfolioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    if kwargs["mean_returns"] is not None:
        kwargs["mean_returns"] = np.asarray(kwargs["mean_returns"], dtype=np.float64)
    if kwargs["cov_matrix"] is not None:
        kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_equal_weight_portfolio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/black_litterman_model",
    response_model=BlackLittermanModelResponse,
    summary="Black Litterman Model",
)
async def black_litterman_model(
    body: BlackLittermanModelRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["market_weights"] = np.asarray(kwargs["market_weights"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    kwargs["p_matrix"] = np.asarray(kwargs["p_matrix"], dtype=np.float64)
    kwargs["q_views"] = np.asarray(kwargs["q_views"], dtype=np.float64)
    if kwargs["omega"] is not None:
        kwargs["omega"] = np.asarray(kwargs["omega"], dtype=np.float64)
    try:
        result: Any = _e_black_litterman_model(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/resampled_efficient_frontier",
    response_model=ResampledEfficientFrontierResponse,
    summary="Resampled Efficient Frontier",
)
async def resampled_efficient_frontier(
    body: ResampledEfficientFrontierRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["mean_returns"] = np.asarray(kwargs["mean_returns"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_resampled_efficient_frontier(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/robust_portfolio_optimisation",
    response_model=RobustPortfolioOptimisationResponse,
    summary="Robust Portfolio Optimisation",
)
async def robust_portfolio_optimisation(
    body: RobustPortfolioOptimisationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["mean_returns"] = np.asarray(kwargs["mean_returns"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_robust_portfolio_optimisation(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/cvar_constrained_optimisation",
    response_model=CvarConstrainedOptimisationResponse,
    summary="Cvar Constrained Optimisation",
)
async def cvar_constrained_optimisation(
    body: CvarConstrainedOptimisationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["scenario_returns"] = np.asarray(kwargs["scenario_returns"], dtype=np.float64)
    if kwargs["mean_returns"] is not None:
        kwargs["mean_returns"] = np.asarray(kwargs["mean_returns"], dtype=np.float64)
    try:
        result: Any = _e_cvar_constrained_optimisation(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/factor_based_optimisation",
    response_model=FactorBasedOptimisationResponse,
    summary="Factor Based Optimisation",
)
async def factor_based_optimisation(
    body: FactorBasedOptimisationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["factor_exposures"] = np.asarray(kwargs["factor_exposures"], dtype=np.float64)
    kwargs["factor_cov"] = np.asarray(kwargs["factor_cov"], dtype=np.float64)
    kwargs["specific_var"] = np.asarray(kwargs["specific_var"], dtype=np.float64)
    if kwargs["target_exposures"] is not None:
        kwargs["target_exposures"] = np.asarray(kwargs["target_exposures"], dtype=np.float64)
    try:
        result: Any = _e_factor_based_optimisation(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/sharpe_ratio",
    response_model=SharpeRatioResponse,
    summary="Sharpe Ratio",
)
async def sharpe_ratio(
    body: SharpeRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_sharpe_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/sortino_ratio",
    response_model=SortinoRatioResponse,
    summary="Sortino Ratio",
)
async def sortino_ratio(
    body: SortinoRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_sortino_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/calmar_ratio",
    response_model=CalmarRatioResponse,
    summary="Calmar Ratio",
)
async def calmar_ratio(
    body: CalmarRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_calmar_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/information_ratio",
    response_model=InformationRatioResponse,
    summary="Information Ratio",
)
async def information_ratio(
    body: InformationRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    kwargs["benchmark_returns"] = np.asarray(kwargs["benchmark_returns"], dtype=np.float64)
    try:
        result: Any = _e_information_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/treynor_ratio",
    response_model=TreynorRatioResponse,
    summary="Treynor Ratio",
)
async def treynor_ratio(
    body: TreynorRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    kwargs["benchmark_returns"] = np.asarray(kwargs["benchmark_returns"], dtype=np.float64)
    try:
        result: Any = _e_treynor_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/jensens_alpha",
    response_model=JensensAlphaResponse,
    summary="Jensens Alpha",
)
async def jensens_alpha(
    body: JensensAlphaRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    kwargs["benchmark_returns"] = np.asarray(kwargs["benchmark_returns"], dtype=np.float64)
    try:
        result: Any = _e_jensens_alpha(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/omega_ratio",
    response_model=OmegaRatioResponse,
    summary="Omega Ratio",
)
async def omega_ratio(
    body: OmegaRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_omega_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/tail_ratio",
    response_model=TailRatioResponse,
    summary="Tail Ratio",
)
async def tail_ratio(
    body: TailRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_tail_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/ulcer_index",
    response_model=UlcerIndexResponse,
    summary="Ulcer Index",
)
async def ulcer_index(
    body: UlcerIndexRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_ulcer_index(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/maximum_drawdown",
    response_model=MaximumDrawdownResponse,
    summary="Maximum Drawdown",
)
async def maximum_drawdown(
    body: MaximumDrawdownRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_maximum_drawdown(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/average_drawdown",
    response_model=AverageDrawdownResponse,
    summary="Average Drawdown",
)
async def average_drawdown(
    body: AverageDrawdownRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_average_drawdown(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/drawdown_duration",
    response_model=DrawdownDurationResponse,
    summary="Drawdown Duration",
)
async def drawdown_duration(
    body: DrawdownDurationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_drawdown_duration(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/conditional_drawdown_at_risk",
    response_model=ConditionalDrawdownAtRiskResponse,
    summary="Conditional Drawdown At Risk",
)
async def conditional_drawdown_at_risk(
    body: ConditionalDrawdownAtRiskRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_conditional_drawdown_at_risk(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/return_attribution_brinson",
    response_model=ReturnAttributionBrinsonResponse,
    summary="Return Attribution Brinson",
)
async def return_attribution_brinson(
    body: ReturnAttributionBrinsonRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["portfolio_weights"] = np.asarray(kwargs["portfolio_weights"], dtype=np.float64)
    kwargs["benchmark_weights"] = np.asarray(kwargs["benchmark_weights"], dtype=np.float64)
    kwargs["portfolio_returns"] = np.asarray(kwargs["portfolio_returns"], dtype=np.float64)
    kwargs["benchmark_returns"] = np.asarray(kwargs["benchmark_returns"], dtype=np.float64)
    try:
        result: Any = _e_return_attribution_brinson(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/factor_return_attribution",
    response_model=FactorReturnAttributionResponse,
    summary="Factor Return Attribution",
)
async def factor_return_attribution(
    body: FactorReturnAttributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["factor_exposures"] = np.asarray(kwargs["factor_exposures"], dtype=np.float64)
    kwargs["factor_returns"] = np.asarray(kwargs["factor_returns"], dtype=np.float64)
    try:
        result: Any = _e_factor_return_attribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/sector_attribution",
    response_model=SectorAttributionResponse,
    summary="Sector Attribution",
)
async def sector_attribution(
    body: SectorAttributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["portfolio_weights"] = np.asarray(kwargs["portfolio_weights"], dtype=np.float64)
    kwargs["benchmark_weights"] = np.asarray(kwargs["benchmark_weights"], dtype=np.float64)
    kwargs["portfolio_returns"] = np.asarray(kwargs["portfolio_returns"], dtype=np.float64)
    kwargs["benchmark_returns"] = np.asarray(kwargs["benchmark_returns"], dtype=np.float64)
    try:
        result: Any = _e_sector_attribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/currency_attribution",
    response_model=CurrencyAttributionResponse,
    summary="Currency Attribution",
)
async def currency_attribution(
    body: CurrencyAttributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["local_returns"] = np.asarray(kwargs["local_returns"], dtype=np.float64)
    kwargs["fx_returns"] = np.asarray(kwargs["fx_returns"], dtype=np.float64)
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    if kwargs.get("local_risk_free") is not None:
        kwargs["local_risk_free"] = np.asarray(kwargs["local_risk_free"], dtype=np.float64)
    try:
        result: Any = _e_currency_attribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/gics_sector_exposure",
    response_model=GicsSectorExposureResponse,
    summary="Gics Sector Exposure",
)
async def gics_sector_exposure(
    body: GicsSectorExposureRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    try:
        result: Any = _e_gics_sector_exposure(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/factor_exposure_analysis_barra",
    response_model=FactorExposureAnalysisBarraResponse,
    summary="Factor Exposure Analysis Barra",
)
async def factor_exposure_analysis_barra(
    body: FactorExposureAnalysisBarraRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["asset_exposures"] = np.asarray(kwargs["asset_exposures"], dtype=np.float64)
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    try:
        result: Any = _e_factor_exposure_analysis_barra(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/fama_french_3_factor_model",
    response_model=FamaFrench3FactorModelResponse,
    summary="Fama French 3 Factor Model",
)
async def fama_french_3_factor_model(
    body: FamaFrench3FactorModelRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["excess_returns"] = np.asarray(kwargs["excess_returns"], dtype=np.float64)
    kwargs["factors"] = np.asarray(kwargs["factors"], dtype=np.float64)
    try:
        result: Any = _e_fama_french_3_factor_model(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/carhart_4_factor_model",
    response_model=Carhart4FactorModelResponse,
    summary="Carhart 4 Factor Model",
)
async def carhart_4_factor_model(
    body: Carhart4FactorModelRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["excess_returns"] = np.asarray(kwargs["excess_returns"], dtype=np.float64)
    kwargs["factors"] = np.asarray(kwargs["factors"], dtype=np.float64)
    try:
        result: Any = _e_carhart_4_factor_model(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/fama_french_5_factor_model",
    response_model=FamaFrench5FactorModelResponse,
    summary="Fama French 5 Factor Model",
)
async def fama_french_5_factor_model(
    body: FamaFrench5FactorModelRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["excess_returns"] = np.asarray(kwargs["excess_returns"], dtype=np.float64)
    kwargs["factors"] = np.asarray(kwargs["factors"], dtype=np.float64)
    try:
        result: Any = _e_fama_french_5_factor_model(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/principal_component_analysis",
    response_model=PrincipalComponentAnalysisResponse,
    summary="Principal Component Analysis",
)
async def principal_component_analysis(
    body: PrincipalComponentAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns_matrix"] = np.asarray(kwargs["returns_matrix"], dtype=np.float64)
    try:
        result: Any = _e_principal_component_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/correlation_clustering",
    response_model=CorrelationClusteringResponse,
    summary="Correlation Clustering",
)
async def correlation_clustering(
    body: CorrelationClusteringRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns_matrix"] = np.asarray(kwargs["returns_matrix"], dtype=np.float64)
    try:
        result: Any = _e_correlation_clustering(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/regime_detection_hmm",
    response_model=RegimeDetectionHmmResponse,
    summary="Regime Detection Hmm",
)
async def regime_detection_hmm(
    body: RegimeDetectionHmmRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_regime_detection_hmm(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/portfolio_beta",
    response_model=PortfolioBetaResponse,
    summary="Portfolio Beta",
)
async def portfolio_beta(
    body: PortfolioBetaRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    kwargs["benchmark_returns"] = np.asarray(kwargs["benchmark_returns"], dtype=np.float64)
    try:
        result: Any = _e_portfolio_beta(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/active_share",
    response_model=ActiveShareResponse,
    summary="Active Share",
)
async def active_share(
    body: ActiveShareRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["benchmark_weights"] = np.asarray(kwargs["benchmark_weights"], dtype=np.float64)
    try:
        result: Any = _e_active_share(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/tracking_error",
    response_model=TrackingErrorResponse,
    summary="Tracking Error",
)
async def tracking_error(
    body: TrackingErrorRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    kwargs["benchmark_returns"] = np.asarray(kwargs["benchmark_returns"], dtype=np.float64)
    try:
        result: Any = _e_tracking_error(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/residual_risk",
    response_model=ResidualRiskResponse,
    summary="Residual Risk",
)
async def residual_risk(
    body: ResidualRiskRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    kwargs["benchmark_returns"] = np.asarray(kwargs["benchmark_returns"], dtype=np.float64)
    try:
        result: Any = _e_residual_risk(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/portfolio_turnover",
    response_model=PortfolioTurnoverResponse,
    summary="Portfolio Turnover",
)
async def portfolio_turnover(
    body: PortfolioTurnoverRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights_before"] = np.asarray(kwargs["weights_before"], dtype=np.float64)
    kwargs["weights_after"] = np.asarray(kwargs["weights_after"], dtype=np.float64)
    try:
        result: Any = _e_portfolio_turnover(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/transaction_cost_analysis",
    response_model=TransactionCostAnalysisResponse,
    summary="Transaction Cost Analysis",
)
async def transaction_cost_analysis(
    body: TransactionCostAnalysisRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["trade_prices"] = np.asarray(kwargs["trade_prices"], dtype=np.float64)
    kwargs["benchmark_prices"] = np.asarray(kwargs["benchmark_prices"], dtype=np.float64)
    kwargs["trade_quantities"] = np.asarray(kwargs["trade_quantities"], dtype=np.float64)
    if isinstance(kwargs.get("decision_price"), list):
        kwargs["decision_price"] = np.asarray(kwargs["decision_price"], dtype=np.float64)
    try:
        result: Any = _e_transaction_cost_analysis(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/marginal_contribution_to_risk",
    response_model=MarginalContributionToRiskResponse,
    summary="Marginal Contribution To Risk",
)
async def marginal_contribution_to_risk(
    body: MarginalContributionToRiskRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_marginal_contribution_to_risk(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/diversification_ratio",
    response_model=DiversificationRatioResponse,
    summary="Diversification Ratio",
)
async def diversification_ratio(
    body: DiversificationRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_diversification_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/correlation_matrix_portfolio",
    response_model=CorrelationMatrixPortfolioResponse,
    summary="Correlation Matrix Portfolio",
)
async def correlation_matrix_portfolio(
    body: CorrelationMatrixPortfolioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns_matrix"] = np.asarray(kwargs["returns_matrix"], dtype=np.float64)
    try:
        result: Any = _e_correlation_matrix_portfolio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/concentration_risk_hhi",
    response_model=ConcentrationRiskHhiResponse,
    summary="Concentration Risk Hhi",
)
async def concentration_risk_hhi(
    body: ConcentrationRiskHhiRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    try:
        result: Any = _e_concentration_risk_hhi(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/liquidity_adjusted_portfolio_var",
    response_model=LiquidityAdjustedPortfolioVarResponse,
    summary="Liquidity Adjusted Portfolio Var",
)
async def liquidity_adjusted_portfolio_var(
    body: LiquidityAdjustedPortfolioVarRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    kwargs["bid_ask_spreads"] = np.asarray(kwargs["bid_ask_spreads"], dtype=np.float64)
    try:
        result: Any = _e_liquidity_adjusted_portfolio_var(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/monte_carlo_portfolio_simulation",
    response_model=MonteCarloPortfolioSimulationResponse,
    summary="Monte Carlo Portfolio Simulation",
)
async def monte_carlo_portfolio_simulation(
    body: MonteCarloPortfolioSimulationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    if body.n_simulations > user.max_simulations:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail=(
                f"Your {user.tier!r} tier allows a maximum of "
                f"{user.max_simulations:,} simulations. "
                f"Requested: {body.n_simulations:,}."
            ),
        )
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["mean_returns"] = np.asarray(kwargs["mean_returns"], dtype=np.float64)
    kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_monte_carlo_portfolio_simulation(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/rebalancing_optimiser",
    response_model=RebalancingOptimiserResponse,
    summary="Rebalancing Optimiser",
)
async def rebalancing_optimiser(
    body: RebalancingOptimiserRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["current_weights"] = np.asarray(kwargs["current_weights"], dtype=np.float64)
    kwargs["target_weights"] = np.asarray(kwargs["target_weights"], dtype=np.float64)
    kwargs["cost_bps"] = np.asarray(kwargs["cost_bps"], dtype=np.float64)
    if kwargs.get("asset_volatility") is not None:
        kwargs["asset_volatility"] = np.asarray(kwargs["asset_volatility"], dtype=np.float64)
    try:
        result: Any = _e_rebalancing_optimiser(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/esg_score_integration",
    response_model=EsgScoreIntegrationResponse,
    summary="Esg Score Integration",
)
async def esg_score_integration(
    body: EsgScoreIntegrationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["esg_scores"] = np.asarray(kwargs["esg_scores"], dtype=np.float64)
    if kwargs["cov_matrix"] is not None:
        kwargs["cov_matrix"] = np.asarray(kwargs["cov_matrix"], dtype=np.float64)
    try:
        result: Any = _e_esg_score_integration(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/carbon_footprint_attribution",
    response_model=CarbonFootprintAttributionResponse,
    summary="Carbon Footprint Attribution",
)
async def carbon_footprint_attribution(
    body: CarbonFootprintAttributionRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["weights"] = np.asarray(kwargs["weights"], dtype=np.float64)
    kwargs["carbon_intensities"] = np.asarray(kwargs["carbon_intensities"], dtype=np.float64)
    if kwargs.get("company_total_emissions") is not None:
        kwargs["company_total_emissions"] = np.asarray(
            kwargs["company_total_emissions"], dtype=np.float64
        )
    if kwargs.get("company_value") is not None:
        kwargs["company_value"] = np.asarray(kwargs["company_value"], dtype=np.float64)
    try:
        result: Any = _e_carbon_footprint_attribution(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)
