"""api/routes/regulatory.py — auto-generated FastAPI routes for the regulatory domain.

Generated by scripts/gen_p3.py. Each route validates its request, converts
list payloads to NumPy arrays, calls the engine wrapper (the single source
of truth), and returns the result dict via OrjsonResponse. No business logic
lives here.
"""

from __future__ import annotations

import logging
from typing import Any

import numpy as np
from fastapi import APIRouter, Depends, HTTPException, status

from api.middleware.auth import TokenPayload, get_current_user
from api.responses import OrjsonResponse
from engine.reg_basel_capital import basel_iii_cet1_ratio as _e_basel_iii_cet1_ratio
from engine.reg_basel_capital import basel_iii_leverage_ratio as _e_basel_iii_leverage_ratio
from engine.reg_basel_capital import basel_iii_tier1_ratio as _e_basel_iii_tier1_ratio
from engine.reg_basel_capital import (
    basel_iii_total_capital_ratio as _e_basel_iii_total_capital_ratio,
)
from engine.reg_basel_capital import basel_iv_output_floor as _e_basel_iv_output_floor
from engine.reg_basel_capital import capital_conservation_buffer as _e_capital_conservation_buffer
from engine.reg_basel_capital import combined_buffer_requirement as _e_combined_buffer_requirement
from engine.reg_basel_capital import (
    countercyclical_capital_buffer as _e_countercyclical_capital_buffer,
)
from engine.reg_basel_capital import crr2_large_exposure_limit as _e_crr2_large_exposure_limit
from engine.reg_basel_capital import icaap_capital_assessment as _e_icaap_capital_assessment
from engine.reg_basel_capital import pillar_2a_capital as _e_pillar_2a_capital
from engine.reg_basel_capital import pillar_2b_stress_buffer as _e_pillar_2b_stress_buffer
from engine.reg_basel_capital import srep_capital_add_on as _e_srep_capital_add_on
from engine.reg_frtb import frtb_ima_market_risk_capital as _e_frtb_ima_market_risk_capital
from engine.reg_frtb import frtb_pl_attribution_test as _e_frtb_pl_attribution_test
from engine.reg_frtb import frtb_sa_market_risk_capital as _e_frtb_sa_market_risk_capital
from engine.reg_frtb import frtb_trading_desk_aggregation as _e_frtb_trading_desk_aggregation
from engine.reg_mifid_emir import (
    emir_clearing_obligation_check as _e_emir_clearing_obligation_check,
)
from engine.reg_mifid_emir import emir_margin_requirement as _e_emir_margin_requirement
from engine.reg_mifid_emir import emir_trade_repository_report as _e_emir_trade_repository_report
from engine.reg_mifid_emir import (
    mifid_ii_algorithm_documentation as _e_mifid_ii_algorithm_documentation,
)
from engine.reg_mifid_emir import (
    mifid_ii_best_execution_metric as _e_mifid_ii_best_execution_metric,
)
from engine.reg_mifid_emir import (
    mifid_ii_post_trade_transparency as _e_mifid_ii_post_trade_transparency,
)
from engine.reg_mifid_emir import (
    mifid_ii_pre_trade_transparency as _e_mifid_ii_pre_trade_transparency,
)
from engine.reg_mifid_emir import (
    mifid_ii_transaction_report_validator as _e_mifid_ii_transaction_report_validator,
)
from engine.reg_mifid_emir import (
    sftr_securities_finance_report as _e_sftr_securities_finance_report,
)
from engine.reg_solvency import aifmd_risk_metrics as _e_aifmd_risk_metrics
from engine.reg_solvency import solvency_ii_scr_credit_risk as _e_solvency_ii_scr_credit_risk
from engine.reg_solvency import solvency_ii_scr_market_risk as _e_solvency_ii_scr_market_risk
from engine.reg_solvency import ucits_kiid_risk_indicator as _e_ucits_kiid_risk_indicator
from schemas.regulatory import (
    AifmdRiskMetricsRequest,
    AifmdRiskMetricsResponse,
    BaselIiiCet1RatioRequest,
    BaselIiiCet1RatioResponse,
    BaselIiiLeverageRatioRequest,
    BaselIiiLeverageRatioResponse,
    BaselIiiTier1RatioRequest,
    BaselIiiTier1RatioResponse,
    BaselIiiTotalCapitalRatioRequest,
    BaselIiiTotalCapitalRatioResponse,
    BaselIvOutputFloorRequest,
    BaselIvOutputFloorResponse,
    CapitalConservationBufferRequest,
    CapitalConservationBufferResponse,
    CombinedBufferRequirementRequest,
    CombinedBufferRequirementResponse,
    CountercyclicalCapitalBufferRequest,
    CountercyclicalCapitalBufferResponse,
    Crr2LargeExposureLimitRequest,
    Crr2LargeExposureLimitResponse,
    EmirClearingObligationCheckRequest,
    EmirClearingObligationCheckResponse,
    EmirMarginRequirementRequest,
    EmirMarginRequirementResponse,
    EmirTradeRepositoryReportRequest,
    EmirTradeRepositoryReportResponse,
    FrtbImaMarketRiskCapitalRequest,
    FrtbImaMarketRiskCapitalResponse,
    FrtbPlAttributionTestRequest,
    FrtbPlAttributionTestResponse,
    FrtbSaMarketRiskCapitalRequest,
    FrtbSaMarketRiskCapitalResponse,
    FrtbTradingDeskAggregationRequest,
    FrtbTradingDeskAggregationResponse,
    IcaapCapitalAssessmentRequest,
    IcaapCapitalAssessmentResponse,
    MifidIiAlgorithmDocumentationRequest,
    MifidIiAlgorithmDocumentationResponse,
    MifidIiBestExecutionMetricRequest,
    MifidIiBestExecutionMetricResponse,
    MifidIiPostTradeTransparencyRequest,
    MifidIiPostTradeTransparencyResponse,
    MifidIiPreTradeTransparencyRequest,
    MifidIiPreTradeTransparencyResponse,
    MifidIiTransactionReportValidatorRequest,
    MifidIiTransactionReportValidatorResponse,
    Pillar2aCapitalRequest,
    Pillar2aCapitalResponse,
    Pillar2bStressBufferRequest,
    Pillar2bStressBufferResponse,
    SftrSecuritiesFinanceReportRequest,
    SftrSecuritiesFinanceReportResponse,
    SolvencyIiScrCreditRiskRequest,
    SolvencyIiScrCreditRiskResponse,
    SolvencyIiScrMarketRiskRequest,
    SolvencyIiScrMarketRiskResponse,
    SrepCapitalAddOnRequest,
    SrepCapitalAddOnResponse,
    UcitsKiidRiskIndicatorRequest,
    UcitsKiidRiskIndicatorResponse,
)

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/regulatory", tags=["regulatory"])

# Engine input errors → HTTP 422. Explicit tuple (no bare except) covers
# bad numeric domains, singular matrices, and shape/key mismatches.
_INPUT_ERRORS = (
    ValueError,
    TypeError,
    KeyError,
    IndexError,
    ArithmeticError,
    AssertionError,
    np.linalg.LinAlgError,
)


@router.post(
    "/basel_iii_cet1_ratio",
    response_model=BaselIiiCet1RatioResponse,
    summary="Basel Iii Cet1 Ratio",
)
async def basel_iii_cet1_ratio(
    body: BaselIiiCet1RatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_basel_iii_cet1_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/basel_iii_tier1_ratio",
    response_model=BaselIiiTier1RatioResponse,
    summary="Basel Iii Tier1 Ratio",
)
async def basel_iii_tier1_ratio(
    body: BaselIiiTier1RatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_basel_iii_tier1_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/basel_iii_total_capital_ratio",
    response_model=BaselIiiTotalCapitalRatioResponse,
    summary="Basel Iii Total Capital Ratio",
)
async def basel_iii_total_capital_ratio(
    body: BaselIiiTotalCapitalRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_basel_iii_total_capital_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/basel_iii_leverage_ratio",
    response_model=BaselIiiLeverageRatioResponse,
    summary="Basel Iii Leverage Ratio",
)
async def basel_iii_leverage_ratio(
    body: BaselIiiLeverageRatioRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_basel_iii_leverage_ratio(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/basel_iv_output_floor",
    response_model=BaselIvOutputFloorResponse,
    summary="Basel Iv Output Floor",
)
async def basel_iv_output_floor(
    body: BaselIvOutputFloorRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_basel_iv_output_floor(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/icaap_capital_assessment",
    response_model=IcaapCapitalAssessmentResponse,
    summary="Icaap Capital Assessment",
)
async def icaap_capital_assessment(
    body: IcaapCapitalAssessmentRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["risk_capital_components"] = np.asarray(
        kwargs["risk_capital_components"], dtype=np.float64
    )
    try:
        result: Any = _e_icaap_capital_assessment(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/srep_capital_add_on",
    response_model=SrepCapitalAddOnResponse,
    summary="Srep Capital Add On",
)
async def srep_capital_add_on(
    body: SrepCapitalAddOnRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_srep_capital_add_on(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/pillar_2a_capital",
    response_model=Pillar2aCapitalResponse,
    summary="Pillar 2A Capital",
)
async def pillar_2a_capital(
    body: Pillar2aCapitalRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["risk_addons"] = np.asarray(kwargs["risk_addons"], dtype=np.float64)
    try:
        result: Any = _e_pillar_2a_capital(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/pillar_2b_stress_buffer",
    response_model=Pillar2bStressBufferResponse,
    summary="Pillar 2B Stress Buffer",
)
async def pillar_2b_stress_buffer(
    body: Pillar2bStressBufferRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_pillar_2b_stress_buffer(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/combined_buffer_requirement",
    response_model=CombinedBufferRequirementResponse,
    summary="Combined Buffer Requirement",
)
async def combined_buffer_requirement(
    body: CombinedBufferRequirementRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_combined_buffer_requirement(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/capital_conservation_buffer",
    response_model=CapitalConservationBufferResponse,
    summary="Capital Conservation Buffer",
)
async def capital_conservation_buffer(
    body: CapitalConservationBufferRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_capital_conservation_buffer(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/countercyclical_capital_buffer",
    response_model=CountercyclicalCapitalBufferResponse,
    summary="Countercyclical Capital Buffer",
)
async def countercyclical_capital_buffer(
    body: CountercyclicalCapitalBufferRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["exposure_amounts"] = np.asarray(kwargs["exposure_amounts"], dtype=np.float64)
    kwargs["country_ccyb_rates"] = np.asarray(kwargs["country_ccyb_rates"], dtype=np.float64)
    try:
        result: Any = _e_countercyclical_capital_buffer(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/crr2_large_exposure_limit",
    response_model=Crr2LargeExposureLimitResponse,
    summary="Crr2 Large Exposure Limit",
)
async def crr2_large_exposure_limit(
    body: Crr2LargeExposureLimitRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_crr2_large_exposure_limit(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_sa_market_risk_capital",
    response_model=FrtbSaMarketRiskCapitalResponse,
    summary="Frtb Sa Market Risk Capital",
)
async def frtb_sa_market_risk_capital(
    body: FrtbSaMarketRiskCapitalRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_frtb_sa_market_risk_capital(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_ima_market_risk_capital",
    response_model=FrtbImaMarketRiskCapitalResponse,
    summary="Frtb Ima Market Risk Capital",
)
async def frtb_ima_market_risk_capital(
    body: FrtbImaMarketRiskCapitalRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_frtb_ima_market_risk_capital(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_pl_attribution_test",
    response_model=FrtbPlAttributionTestResponse,
    summary="Frtb Pl Attribution Test",
)
async def frtb_pl_attribution_test(
    body: FrtbPlAttributionTestRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["risk_theoretical_pnl"] = np.asarray(kwargs["risk_theoretical_pnl"], dtype=np.float64)
    kwargs["hypothetical_pnl"] = np.asarray(kwargs["hypothetical_pnl"], dtype=np.float64)
    try:
        result: Any = _e_frtb_pl_attribution_test(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/frtb_trading_desk_aggregation",
    response_model=FrtbTradingDeskAggregationResponse,
    summary="Frtb Trading Desk Aggregation",
)
async def frtb_trading_desk_aggregation(
    body: FrtbTradingDeskAggregationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["desk_sa_charges"] = np.asarray(kwargs["desk_sa_charges"], dtype=np.float64)
    kwargs["desk_ima_charges"] = np.asarray(kwargs["desk_ima_charges"], dtype=np.float64)
    kwargs["desk_ima_eligible"] = np.asarray(kwargs["desk_ima_eligible"], dtype=np.float64)
    try:
        result: Any = _e_frtb_trading_desk_aggregation(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/mifid_ii_transaction_report_validator",
    response_model=MifidIiTransactionReportValidatorResponse,
    summary="Mifid Ii Transaction Report Validator",
)
async def mifid_ii_transaction_report_validator(
    body: MifidIiTransactionReportValidatorRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_mifid_ii_transaction_report_validator(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/mifid_ii_pre_trade_transparency",
    response_model=MifidIiPreTradeTransparencyResponse,
    summary="Mifid Ii Pre Trade Transparency",
)
async def mifid_ii_pre_trade_transparency(
    body: MifidIiPreTradeTransparencyRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_mifid_ii_pre_trade_transparency(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/mifid_ii_post_trade_transparency",
    response_model=MifidIiPostTradeTransparencyResponse,
    summary="Mifid Ii Post Trade Transparency",
)
async def mifid_ii_post_trade_transparency(
    body: MifidIiPostTradeTransparencyRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_mifid_ii_post_trade_transparency(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/mifid_ii_best_execution_metric",
    response_model=MifidIiBestExecutionMetricResponse,
    summary="Mifid Ii Best Execution Metric",
)
async def mifid_ii_best_execution_metric(
    body: MifidIiBestExecutionMetricRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["executed_prices"] = np.asarray(kwargs["executed_prices"], dtype=np.float64)
    kwargs["benchmark_prices"] = np.asarray(kwargs["benchmark_prices"], dtype=np.float64)
    kwargs["quantities"] = np.asarray(kwargs["quantities"], dtype=np.float64)
    try:
        result: Any = _e_mifid_ii_best_execution_metric(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/mifid_ii_algorithm_documentation",
    response_model=MifidIiAlgorithmDocumentationResponse,
    summary="Mifid Ii Algorithm Documentation",
)
async def mifid_ii_algorithm_documentation(
    body: MifidIiAlgorithmDocumentationRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_mifid_ii_algorithm_documentation(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/emir_trade_repository_report",
    response_model=EmirTradeRepositoryReportResponse,
    summary="Emir Trade Repository Report",
)
async def emir_trade_repository_report(
    body: EmirTradeRepositoryReportRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_emir_trade_repository_report(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/emir_clearing_obligation_check",
    response_model=EmirClearingObligationCheckResponse,
    summary="Emir Clearing Obligation Check",
)
async def emir_clearing_obligation_check(
    body: EmirClearingObligationCheckRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_emir_clearing_obligation_check(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/emir_margin_requirement",
    response_model=EmirMarginRequirementResponse,
    summary="Emir Margin Requirement",
)
async def emir_margin_requirement(
    body: EmirMarginRequirementRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_emir_margin_requirement(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/sftr_securities_finance_report",
    response_model=SftrSecuritiesFinanceReportResponse,
    summary="Sftr Securities Finance Report",
)
async def sftr_securities_finance_report(
    body: SftrSecuritiesFinanceReportRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_sftr_securities_finance_report(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/aifmd_risk_metrics",
    response_model=AifmdRiskMetricsResponse,
    summary="Aifmd Risk Metrics",
)
async def aifmd_risk_metrics(
    body: AifmdRiskMetricsRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    try:
        result: Any = _e_aifmd_risk_metrics(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/ucits_kiid_risk_indicator",
    response_model=UcitsKiidRiskIndicatorResponse,
    summary="Ucits Kiid Risk Indicator",
)
async def ucits_kiid_risk_indicator(
    body: UcitsKiidRiskIndicatorRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["returns"] = np.asarray(kwargs["returns"], dtype=np.float64)
    try:
        result: Any = _e_ucits_kiid_risk_indicator(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/solvency_ii_scr_market_risk",
    response_model=SolvencyIiScrMarketRiskResponse,
    summary="Solvency Ii Scr Market Risk",
)
async def solvency_ii_scr_market_risk(
    body: SolvencyIiScrMarketRiskRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["sub_module_charges"] = np.asarray(kwargs["sub_module_charges"], dtype=np.float64)
    kwargs["correlation_matrix"] = np.asarray(kwargs["correlation_matrix"], dtype=np.float64)
    try:
        result: Any = _e_solvency_ii_scr_market_risk(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)


@router.post(
    "/solvency_ii_scr_credit_risk",
    response_model=SolvencyIiScrCreditRiskResponse,
    summary="Solvency Ii Scr Credit Risk",
)
async def solvency_ii_scr_credit_risk(
    body: SolvencyIiScrCreditRiskRequest,
    user: TokenPayload = Depends(get_current_user),
) -> OrjsonResponse:
    kwargs = body.model_dump()
    kwargs["exposures"] = np.asarray(kwargs["exposures"], dtype=np.float64)
    kwargs["loss_given_default"] = np.asarray(kwargs["loss_given_default"], dtype=np.float64)
    kwargs["default_probabilities"] = np.asarray(kwargs["default_probabilities"], dtype=np.float64)
    try:
        result: Any = _e_solvency_ii_scr_credit_risk(**kwargs)
    except _INPUT_ERRORS as exc:
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail=str(exc),
        ) from exc
    if not isinstance(result, dict):
        result = {"result": result}
    return OrjsonResponse(content=result)
